// Dataset fittizio condiviso tra LatestPositionsTable (UI sotto il globo)
// e HeroGlobe (pin sul mappamondo). Single source of truth: ogni offerta
// porta con sé le coordinate lon/lat → i pin si piazzano esattamente
// sulle location citate nella tabella.

export type LuxuryPosition = {
  id: string;
  legacy_id?: number | null;
  title: string;
  company: string;
  location?: string | null;
  // Coordinate per pin globo (lon, lat) — required per ogni mock.
  lon: number;
  lat: number;
  status: string;
  source?: string | null;
  score?: number | null;
  found_at: string;
  found_by?: string | null;
  last_checked?: string | null;
  scored_at?: string | null;
  last_action_at?: string;
  last_action_by?: string;
  last_action_actor?: string;
  voto?: number | null;
  url?: string | null;
  remote_type?: string | null;
  salary_declared_min?: number | null;
  salary_declared_max?: number | null;
};

const MINUTES = 60_000;
const HOURS = 60 * MINUTES;
const now = Date.now();
const iso = (msAgo: number) => new Date(now - msAgo).toISOString();

export const LUXURY_POSITIONS: LuxuryPosition[] = [
  {
    id: "p01",
    title: "Head Sommelier",
    company: "The Connaught",
    location: "Mayfair, London, UK",
    lon: -0.1471,
    lat: 51.5108,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(8 * MINUTES),
    found_by: "scout",
    last_action_at: iso(8 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 58000,
    salary_declared_max: 72000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p02",
    title: "Chef de Rang — Fine Dining",
    company: "Hôtel de Crillon, A Rosewood Hotel",
    location: "Paris, France",
    lon: 2.3212,
    lat: 48.8675,
    status: "checked",
    source: "linkedin.com",
    score: 86,
    voto: null,
    found_at: iso(34 * MINUTES),
    found_by: "scout",
    last_action_at: iso(12 * MINUTES),
    last_action_actor: "analista",
    salary_declared_min: 38000,
    salary_declared_max: 46000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p03",
    title: "Yacht Chief Stewardess",
    company: "M/Y Aurora — Charter 67m",
    location: "Monaco / Mediterranean",
    lon: 7.4246,
    lat: 43.7384,
    status: "scored",
    source: "yotspot.com",
    score: 91,
    voto: 8.4,
    found_at: iso(1 * HOURS),
    found_by: "scout",
    last_action_at: iso(22 * MINUTES),
    last_action_actor: "scorer",
    salary_declared_min: 54000,
    salary_declared_max: 66000,
    remote_type: "live-aboard",
    url: "#",
  },
  {
    id: "p04",
    title: "Sommelier — Rooftop & Garden",
    company: "16 Roof — Pera Palace",
    location: "Istanbul, Türkiye",
    lon: 28.9744,
    lat: 41.0306,
    status: "new",
    source: "caterer.com",
    score: null,
    voto: null,
    found_at: iso(46 * MINUTES),
    found_by: "scout",
    last_action_at: iso(46 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 32000,
    salary_declared_max: 41000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p05",
    title: "Chef de Rang — Safari Lodge",
    company: "andBeyond Bateleur Camp",
    location: "Maasai Mara, Kenya",
    lon: 35.1438,
    lat: -1.5014,
    status: "writing",
    source: "luxuryjobs.com",
    score: 88,
    voto: 7.9,
    found_at: iso(2 * HOURS),
    found_by: "scout",
    last_action_at: iso(14 * MINUTES),
    last_action_actor: "scrittore",
    salary_declared_min: 30000,
    salary_declared_max: 38000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p06",
    title: "Senior Waiter",
    company: "Marbella Club Hotel",
    location: "Marbella, Spain",
    lon: -4.8855,
    lat: 36.5089,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(1.5 * HOURS),
    found_by: "scout",
    last_action_at: iso(1.5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 28000,
    salary_declared_max: 35000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p07",
    title: "Maître d'Hôtel",
    company: "Belmond Hotel Splendido",
    location: "Portofino, Italy",
    lon: 9.2099,
    lat: 44.3034,
    status: "checked",
    source: "linkedin.com",
    score: 84,
    voto: null,
    found_at: iso(3 * HOURS),
    found_by: "scout",
    last_action_at: iso(40 * MINUTES),
    last_action_actor: "analista",
    salary_declared_min: 44000,
    salary_declared_max: 58000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p08",
    title: "Sommelier",
    company: "Aman New York",
    location: "Manhattan, New York, USA",
    lon: -73.9762,
    lat: 40.7644,
    status: "ready",
    source: "indeed.com",
    score: 93,
    voto: 8.6,
    found_at: iso(5 * HOURS),
    found_by: "scout",
    last_action_at: iso(28 * MINUTES),
    last_action_actor: "scrittore",
    salary_declared_min: 72000,
    salary_declared_max: 95000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p09",
    title: "Chef de Rang — Beach Restaurant",
    company: "Soneva Fushi",
    location: "Baa Atoll, Maldives",
    lon: 73.1085,
    lat: 5.1846,
    status: "scored",
    source: "luxuryjobs.com",
    score: 89,
    voto: 8.1,
    found_at: iso(4 * HOURS),
    found_by: "scout",
    last_action_at: iso(33 * MINUTES),
    last_action_actor: "scorer",
    salary_declared_min: 26000,
    salary_declared_max: 34000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p10",
    title: "Chef de Rang — Tasting Menu",
    company: "Disfrutar (3*)",
    location: "Barcelona, Spain",
    lon: 2.1547,
    lat: 41.3879,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(20 * MINUTES),
    found_by: "scout",
    last_action_at: iso(20 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 34000,
    salary_declared_max: 42000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p11",
    title: "Yacht Steward / Sommelier dual role",
    company: "M/Y Octopus — Caribbean Season",
    location: "St. Maarten / Caribbean",
    lon: -63.0501,
    lat: 18.0425,
    status: "review",
    source: "yotspot.com",
    score: 90,
    voto: 8.2,
    found_at: iso(6 * HOURS),
    found_by: "scout",
    last_action_at: iso(18 * MINUTES),
    last_action_actor: "critico",
    salary_declared_min: 56000,
    salary_declared_max: 70000,
    remote_type: "live-aboard",
    url: "#",
  },
  {
    id: "p12",
    title: "Senior Sommelier",
    company: "Bulgari Hotel Roma",
    location: "Rome, Italy",
    lon: 12.4828,
    lat: 41.9028,
    status: "new",
    source: "linkedin.com",
    score: null,
    voto: null,
    found_at: iso(55 * MINUTES),
    found_by: "scout",
    last_action_at: iso(55 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 42000,
    salary_declared_max: 54000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p13",
    title: "Chef de Rang — Safari Fine Dining",
    company: "Singita Ebony Lodge",
    location: "Sabi Sand Reserve, South Africa",
    lon: 31.4042,
    lat: -24.8506,
    status: "checked",
    source: "luxuryjobs.com",
    score: 85,
    voto: null,
    found_at: iso(7 * HOURS),
    found_by: "scout",
    last_action_at: iso(50 * MINUTES),
    last_action_actor: "analista",
    salary_declared_min: 25000,
    salary_declared_max: 32000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p14",
    title: "Sommelier — Beach Club",
    company: "Estiatorio Milos",
    location: "Mykonos, Greece",
    lon: 25.3289,
    lat: 37.4467,
    status: "applied",
    source: "hosco.com",
    score: 87,
    voto: 7.7,
    found_at: iso(9 * HOURS),
    found_by: "scout",
    last_action_at: iso(11 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 36000,
    salary_declared_max: 44000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p15",
    title: "Head Waiter — Michelin Garden",
    company: "Borgo Egnazia",
    location: "Savelletri, Puglia, Italy",
    lon: 17.7106,
    lat: 40.8408,
    status: "new",
    source: "caterer.com",
    score: null,
    voto: null,
    found_at: iso(2.2 * HOURS),
    found_by: "scout",
    last_action_at: iso(2.2 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 32000,
    salary_declared_max: 40000,
    remote_type: "on-site",
    url: "#",
  },
];
