// Dataset fittizio condiviso tra LatestPositionsTable (UI sotto il globo)
// e HeroGlobe (pin sul mappamondo). Single source of truth: ogni offerta
// porta con sé le coordinate lon/lat → i pin si piazzano esattamente
// sulle location citate nella tabella.
//
// Due fasi di pipeline:
//   - Pin 0-13: emisfero nord (lat > 35°), pipeline completa Scout →
//     Analyst → Scorer → Writer.
//   - Pin 14-23: globali (incluso sud), round 2 dove lo Scout trova
//     nuove offerte mentre il globo continua a girare.

export type LuxuryPosition = {
  id: string;
  legacy_id?: number | null;
  title: string;
  company: string;
  location?: string | null;
  lon: number;
  lat: number;
  status: string;
  source?: string | null;
  score?: number | null;
  found_at: string;
  found_by?: string | null;
  last_checked?: string | null;
  scored_at?: string | null;
  last_action_at?: string;
  last_action_by?: string;
  last_action_actor?: string;
  voto?: number | null;
  url?: string | null;
  remote_type?: string | null;
  salary_declared_min?: number | null;
  salary_declared_max?: number | null;
};

const MINUTES = 60_000;
const HOURS = 60 * MINUTES;
const now = Date.now();
const iso = (msAgo: number) => new Date(now - msAgo).toISOString();

export const LUXURY_POSITIONS: LuxuryPosition[] = [
  {
    id: "p01",
    title: "Head Sommelier",
    company: "The Connaught",
    location: "Mayfair, London, UK",
    lon: -0.1471,
    lat: 51.5108,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(8 * MINUTES),
    found_by: "scout",
    last_action_at: iso(8 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 58000,
    salary_declared_max: 72000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p02",
    title: "Chef de Rang — Fine Dining",
    company: "Hôtel de Crillon, A Rosewood Hotel",
    location: "Paris, France",
    lon: 2.3212,
    lat: 48.8675,
    status: "checked",
    source: "linkedin.com",
    score: 86,
    voto: null,
    found_at: iso(34 * MINUTES),
    found_by: "scout",
    last_action_at: iso(12 * MINUTES),
    last_action_actor: "analista",
    salary_declared_min: 38000,
    salary_declared_max: 46000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p03",
    title: "Maître d'Hôtel",
    company: "Hotel Sacher Wien",
    location: "Vienna, Austria",
    lon: 16.3697,
    lat: 48.2050,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(46 * MINUTES),
    found_by: "scout",
    last_action_at: iso(46 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 40000,
    salary_declared_max: 52000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p04",
    title: "Sommelier — Royal Opera Restaurant",
    company: "Operakällaren",
    location: "Stockholm, Sweden",
    lon: 18.0707,
    lat: 59.3293,
    status: "scored",
    source: "luxuryjobs.com",
    score: 88,
    voto: 8.0,
    found_at: iso(1 * HOURS),
    found_by: "scout",
    last_action_at: iso(22 * MINUTES),
    last_action_actor: "scorer",
    salary_declared_min: 48000,
    salary_declared_max: 58000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p05",
    title: "Senior Sommelier — Imàgo",
    company: "Hassler Roma",
    location: "Rome, Italy",
    lon: 12.4823,
    lat: 41.9028,
    status: "checked",
    source: "linkedin.com",
    score: 87,
    voto: null,
    found_at: iso(2 * HOURS),
    found_by: "scout",
    last_action_at: iso(40 * MINUTES),
    last_action_actor: "analista",
    salary_declared_min: 42000,
    salary_declared_max: 54000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p06",
    title: "Sommelier — 16 Roof",
    company: "Pera Palace Hotel",
    location: "Istanbul, Türkiye",
    lon: 28.9744,
    lat: 41.0306,
    status: "new",
    source: "caterer.com",
    score: null,
    voto: null,
    found_at: iso(1.5 * HOURS),
    found_by: "scout",
    last_action_at: iso(1.5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 32000,
    salary_declared_max: 41000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p07",
    title: "Maître d'Hôtel",
    company: "Café Pushkin",
    location: "Moscow, Russia",
    lon: 37.6173,
    lat: 55.7558,
    status: "writing",
    source: "luxuryjobs.com",
    score: 85,
    voto: 7.8,
    found_at: iso(3 * HOURS),
    found_by: "scout",
    last_action_at: iso(14 * MINUTES),
    last_action_actor: "scrittore",
    salary_declared_min: 36000,
    salary_declared_max: 48000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p08",
    title: "Chef de Rang — Imperial Cuisine",
    company: "Aman Summer Palace",
    location: "Beijing, China",
    lon: 116.4074,
    lat: 39.9042,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(55 * MINUTES),
    found_by: "scout",
    last_action_at: iso(55 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 46000,
    salary_declared_max: 62000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p09",
    title: "Sommelier — Korean Fine Dining",
    company: "The Shilla",
    location: "Seoul, South Korea",
    lon: 127.0042,
    lat: 37.5559,
    status: "scored",
    source: "linkedin.com",
    score: 89,
    voto: 8.2,
    found_at: iso(4 * HOURS),
    found_by: "scout",
    last_action_at: iso(33 * MINUTES),
    last_action_actor: "scorer",
    salary_declared_min: 50000,
    salary_declared_max: 64000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p10",
    title: "Senior Sommelier",
    company: "Aman Tokyo — Otemachi",
    location: "Tokyo, Japan",
    lon: 139.7639,
    lat: 35.6868,
    status: "ready",
    source: "luxuryjobs.com",
    score: 92,
    voto: 8.5,
    found_at: iso(5 * HOURS),
    found_by: "scout",
    last_action_at: iso(28 * MINUTES),
    last_action_actor: "scrittore",
    salary_declared_min: 56000,
    salary_declared_max: 72000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p11",
    title: "Chef de Rang — Michelin 3★",
    company: "Quince",
    location: "San Francisco, USA",
    lon: -122.4068,
    lat: 37.7867,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(20 * MINUTES),
    found_by: "scout",
    last_action_at: iso(20 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 60000,
    salary_declared_max: 78000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p12",
    title: "Sommelier — Fine Dining Strip",
    company: "Wynn Las Vegas",
    location: "Las Vegas, USA",
    lon: -115.1641,
    lat: 36.1147,
    status: "checked",
    source: "indeed.com",
    score: 84,
    voto: null,
    found_at: iso(6 * HOURS),
    found_by: "scout",
    last_action_at: iso(18 * MINUTES),
    last_action_actor: "analista",
    salary_declared_min: 54000,
    salary_declared_max: 68000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p13",
    title: "Chef de Rang — Tasting Menu",
    company: "Alinea",
    location: "Chicago, USA",
    lon: -87.6479,
    lat: 41.9131,
    status: "review",
    source: "linkedin.com",
    score: 90,
    voto: 8.3,
    found_at: iso(7 * HOURS),
    found_by: "scout",
    last_action_at: iso(11 * MINUTES),
    last_action_actor: "critico",
    salary_declared_min: 58000,
    salary_declared_max: 74000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p14",
    title: "Senior Sommelier",
    company: "Aman New York",
    location: "Manhattan, New York, USA",
    lon: -73.9762,
    lat: 40.7644,
    status: "applied",
    source: "indeed.com",
    score: 93,
    voto: 8.6,
    found_at: iso(9 * HOURS),
    found_by: "scout",
    last_action_at: iso(48 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 72000,
    salary_declared_max: 95000,
    remote_type: "on-site",
    url: "#",
  },
  // ── Pin 14-23: round 2, locations globali (incluso emisfero sud) ──
  {
    id: "p15",
    title: "Chef de Rang — Brazilian Fine Dining",
    company: "D.O.M. — Alex Atala",
    location: "São Paulo, Brazil",
    lon: -46.6333,
    lat: -23.5505,
    status: "new",
    source: "luxuryjobs.com",
    score: null,
    voto: null,
    found_at: iso(50 * MINUTES),
    found_by: "scout",
    last_action_at: iso(50 * MINUTES),
    last_action_actor: "scout",
    salary_declared_min: 28000,
    salary_declared_max: 38000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p16",
    title: "Senior Sommelier",
    company: "Wasabi by Morimoto — Taj Mahal Palace",
    location: "Mumbai, India",
    lon: 72.8347,
    lat: 18.9217,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(1.2 * HOURS),
    found_by: "scout",
    last_action_at: iso(1.2 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 36000,
    salary_declared_max: 46000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p17",
    title: "Chef de Rang — Michelin 3★",
    company: "Odette",
    location: "Singapore",
    lon: 103.8512,
    lat: 1.2916,
    status: "new",
    source: "luxuryjobs.com",
    score: null,
    voto: null,
    found_at: iso(2.5 * HOURS),
    found_by: "scout",
    last_action_at: iso(2.5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 52000,
    salary_declared_max: 68000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p18",
    title: "Maître d'Hôtel — French Fine Dining",
    company: "Le Normandie — Mandarin Oriental",
    location: "Bangkok, Thailand",
    lon: 100.5167,
    lat: 13.7237,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(3.5 * HOURS),
    found_by: "scout",
    last_action_at: iso(3.5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 38000,
    salary_declared_max: 50000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p19",
    title: "Senior Sommelier — Harbour View",
    company: "Quay Restaurant",
    location: "Sydney, Australia",
    lon: 151.2093,
    lat: -33.8568,
    status: "new",
    source: "luxuryjobs.com",
    score: null,
    voto: null,
    found_at: iso(4.2 * HOURS),
    found_by: "scout",
    last_action_at: iso(4.2 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 48000,
    salary_declared_max: 60000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p20",
    title: "Chef de Rang — Vineyards Tasting",
    company: "The Test Kitchen",
    location: "Cape Town, South Africa",
    lon: 18.4232,
    lat: -33.9249,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(5 * HOURS),
    found_by: "scout",
    last_action_at: iso(5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 30000,
    salary_declared_max: 40000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p21",
    title: "Sommelier — Mexican Haute Cuisine",
    company: "Pujol",
    location: "Mexico City, Mexico",
    lon: -99.1332,
    lat: 19.4326,
    status: "new",
    source: "luxuryjobs.com",
    score: null,
    voto: null,
    found_at: iso(6 * HOURS),
    found_by: "scout",
    last_action_at: iso(6 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 32000,
    salary_declared_max: 42000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p22",
    title: "Chef de Rang — Andean Tasting Menu",
    company: "Central",
    location: "Lima, Peru",
    lon: -77.0282,
    lat: -12.0432,
    status: "new",
    source: "hosco.com",
    score: null,
    voto: null,
    found_at: iso(7.5 * HOURS),
    found_by: "scout",
    last_action_at: iso(7.5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 30000,
    salary_declared_max: 40000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p23",
    title: "Maître d'Hôtel",
    company: "Tegui — Palermo",
    location: "Buenos Aires, Argentina",
    lon: -58.4267,
    lat: -34.5895,
    status: "new",
    source: "luxuryjobs.com",
    score: null,
    voto: null,
    found_at: iso(8.5 * HOURS),
    found_by: "scout",
    last_action_at: iso(8.5 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 32000,
    salary_declared_max: 42000,
    remote_type: "on-site",
    url: "#",
  },
  {
    id: "p24",
    title: "Sommelier — Royal Restaurant",
    company: "Burj Al Arab Jumeirah",
    location: "Dubai, UAE",
    lon: 55.1853,
    lat: 25.1412,
    status: "new",
    source: "luxuryjobs.com",
    score: null,
    voto: null,
    found_at: iso(10 * HOURS),
    found_by: "scout",
    last_action_at: iso(10 * HOURS),
    last_action_actor: "scout",
    salary_declared_min: 48000,
    salary_declared_max: 62000,
    remote_type: "on-site",
    url: "#",
  },
];
