#!/usr/bin/env python3
"""Writes src/db/schema.sql: the jobs.db schema exactly as the TUI agents create it.

The TUI agents' database is born in `shared/skills/_db.py`: `ensure_schema`
creates every table, index and trigger, running its migrations on the way.
The harness does not port that code — it would drift the day someone adds a
column. It replays the result instead: this script runs `ensure_schema` on an
empty file and writes what SQLite recorded, statement by statement, in the
order SQLite created them. The harness executes that file on a new jobs.db,
so its database is the TUI's, byte for byte in `sqlite_master`.

Usage (from agent-harness/runtime):

    python3 scripts/dump-jobs-schema.py <dir holding _db.py> <source label> [out]

    git archive origin/master shared/skills | tar -x -C /tmp/src
    python3 scripts/dump-jobs-schema.py /tmp/src/shared/skills "origin/master $(git rev-parse --short=9 origin/master)"

Rerun it whenever `_db.py` changes on the branch the TUI image is built from;
tests/jobs-db.test.ts fails while the file and its source disagree.
"""
import hashlib
import os
import sys
import tempfile


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print(__doc__, file=sys.stderr)
        return 2
    source_dir, label = sys.argv[1], sys.argv[2]
    out = sys.argv[3] if len(sys.argv) == 4 else None

    db_py = os.path.join(source_dir, "_db.py")
    with open(db_py, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()

    with tempfile.TemporaryDirectory() as tmp:
        os.environ["JHT_DB"] = os.path.join(tmp, "jobs.db")
        sys.path.insert(0, source_dir)
        import _db  # noqa: E402  (the path is only known at run time)

        conn = _db.get_db()
        _db.ensure_schema(conn)
        conn.commit()
        rows = conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY rowid"
        ).fetchall()
        user_version = conn.execute("PRAGMA user_version").fetchone()[0]
        conn.close()

    lines = [
        "-- jobs.db schema, as shared/skills/_db.py ensure_schema() creates it.",
        "-- GENERATED by scripts/dump-jobs-schema.py: do not edit, regenerate.",
        f"-- source: {label}",
        f"-- _db.py sha256: {digest}",
        "",
    ]
    for name, sql in rows:
        # SQLite makes this one itself, with the first AUTOINCREMENT table.
        if name == "sqlite_sequence":
            continue
        lines.append(f"{sql};")
        lines.append("")
    lines.append(f"PRAGMA user_version = {user_version};")
    text = "\n".join(lines) + "\n"

    if out:
        with open(out, "w", encoding="utf-8") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
