"""O-89 real PostgreSQL 16 oracles for the two atomic state boundaries."""

from __future__ import annotations

import pathlib
import subprocess
import time
import uuid
from concurrent.futures import ThreadPoolExecutor

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
MIG_077 = ROOT / "supabase/migrations/077_application_mark_undo_hotfix.sql"
MIG_083 = ROOT / "supabase/migrations/083_position_ticket_state_model.sql"
USER_A = "11111111-1111-4111-8111-111111111111"
USER_B = "22222222-2222-4222-8222-222222222222"
POSITION_A = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
POSTGRES_READY_MARKER = "database system is ready to accept connections"


def _final_postgres_server_is_ready(logs: str) -> bool:
    """Reject initdb's temporary server and accept only the final restart."""
    return logs.count(POSTGRES_READY_MARKER) >= 2


def _docker(*args: str, input_text: str | None = None, check: bool = True):
    return subprocess.run(
        ["docker", *args],
        input=input_text,
        text=True,
        capture_output=True,
        check=check,
    )


@pytest.fixture(scope="module")
def postgres16():
    if subprocess.run(["docker", "info"], capture_output=True).returncode != 0:
        pytest.skip("Docker unavailable")
    name = f"jht-o89-{uuid.uuid4().hex[:10]}"
    started = _docker(
        "run", "-d", "--name", name,
        "--tmpfs", "/var/lib/postgresql/data:rw,size=512m",
        "-e", "POSTGRES_PASSWORD=o89-local-only",
        "postgres:16-alpine",
    ).stdout.strip()
    assert started
    try:
        for _ in range(100):
            logs_result = _docker("logs", name, check=False)
            logs = logs_result.stdout + logs_result.stderr
            if _final_postgres_server_is_ready(logs):
                probe = _docker(
                    "exec", "-i", name, "psql", "-X", "-q", "-At",
                    "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres",
                    input_text="CREATE TEMP TABLE o89_readiness_probe(id integer); DROP TABLE o89_readiness_probe;",
                    check=False,
                )
                if probe.returncode == 0:
                    break
            time.sleep(0.2)
        else:
            pytest.fail("PostgreSQL 16 final server did not become ready")

        schema = f"""
        CREATE ROLE anon NOLOGIN;
        CREATE ROLE authenticated NOLOGIN;
        CREATE ROLE service_role NOLOGIN;
        CREATE SCHEMA auth;
        CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
          $$ SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
        CREATE TABLE public.positions (
          id uuid PRIMARY KEY, user_id uuid NOT NULL, legacy_id integer NOT NULL,
          status text NOT NULL DEFAULT 'new', last_actor text,
          UNIQUE(user_id, legacy_id)
        );
        CREATE UNIQUE INDEX positions_user_id_id_uidx ON public.positions(user_id,id);
        CREATE TABLE public.applications (
          id bigserial PRIMARY KEY, user_id uuid NOT NULL, position_id uuid NOT NULL UNIQUE,
          status text NOT NULL DEFAULT 'draft', applied boolean DEFAULT false,
          applied_at timestamptz, applied_via text, critic_notes text,
          cv_path text, cv_pdf_path text, updated_at timestamptz DEFAULT now()
        );
        CREATE TABLE public.scores (id bigserial PRIMARY KEY, user_id uuid, position_id uuid);
        CREATE TABLE public.position_transitions (
          id bigserial PRIMARY KEY, user_id uuid, position_legacy_id integer,
          from_state text, to_state text, ts timestamptz, by_agent text, notes text,
          UNIQUE(user_id, position_legacy_id, ts, by_agent, to_state)
        );
        CREATE TABLE public.position_tickets (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id uuid NOT NULL, position_legacy_id integer NOT NULL,
          request_text text NOT NULL, kind text NOT NULL DEFAULT 'custom',
          status text NOT NULL DEFAULT 'open', assigned_agent text, response_text text,
          created_at timestamptz NOT NULL DEFAULT now(), assigned_at timestamptz,
          resolved_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE UNIQUE INDEX idx_position_tickets_active_rescore
          ON public.position_tickets(user_id, position_legacy_id, kind)
          WHERE kind='rescore' AND status IN ('open','assigned');
        GRANT INSERT, UPDATE ON public.position_tickets TO authenticated, service_role;
        INSERT INTO public.positions(id,user_id,legacy_id,status)
          VALUES ('{POSITION_A}','{USER_A}',5,'review');
        INSERT INTO public.position_tickets(user_id,position_legacy_id,request_text)
          VALUES ('{USER_A}',5,'existing synthetic ticket');
        """
        _psql(name, schema)
        _psql(name, MIG_077.read_text())
        _psql(name, MIG_083.read_text())
        _psql(name, MIG_083.read_text())
        yield name
    finally:
        _docker("rm", "-f", name, check=False)


def test_pg16_readiness_rejects_temporary_initdb_server():
    first_start = f"{POSTGRES_READY_MARKER}\n"
    final_restart = f"{first_start}{POSTGRES_READY_MARKER}\n"

    assert not _final_postgres_server_is_ready(first_start)
    assert _final_postgres_server_is_ready(final_restart)


def _psql(container: str, sql: str, *, check: bool = True) -> str:
    result = _docker(
        "exec", "-i", container, "psql", "-X", "-q", "-At",
        "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres",
        input_text=sql, check=False,
    )
    if check and result.returncode:
        raise AssertionError(f"psql failed with code {result.returncode}")
    return result.stdout.strip()


def _as_user(container: str, user: str, statement: str, *, check: bool = True) -> str:
    lines = _psql(
        container,
        f"SELECT set_config('request.jwt.claim.sub','{user}',false); {statement}",
        check=check,
    ).splitlines()
    return lines[-1] if lines else ""


def test_backfill_and_tenant_fk_are_exact(postgres16):
    value = _psql(
        postgres16,
        "SELECT position_id::text FROM position_tickets WHERE request_text='existing synthetic ticket';",
    )
    assert value == POSITION_A
    invalid = _psql(
        postgres16,
        f"INSERT INTO position_tickets(user_id,position_id,position_legacy_id,request_text) "
        f"VALUES ('{USER_B}','{POSITION_A}',5,'cross tenant');",
        check=False,
    )
    assert invalid == ""
    assert _psql(postgres16, "SELECT count(*) FROM position_tickets WHERE request_text='cross tenant';") == "0"
    _psql(
        postgres16,
        f"INSERT INTO position_tickets(user_id,position_id,position_legacy_id,request_text) "
        f"VALUES ('{USER_A}','{POSITION_A}',6,'mismatched legacy');",
        check=False,
    )
    assert _psql(postgres16, "SELECT count(*) FROM position_tickets WHERE request_text='mismatched legacy';") == "0"
    privileges = _psql(
        postgres16,
        "SELECT has_table_privilege('authenticated','position_tickets','INSERT'),"
        "has_table_privilege('authenticated','position_tickets','UPDATE'),"
        "has_table_privilege('service_role','position_tickets','INSERT'),"
        "has_table_privilege('service_role','position_tickets','UPDATE');",
    )
    assert privileges == "f|f|f|t"
    function_privileges = _psql(
        postgres16,
        "SELECT has_function_privilege('authenticated','create_position_ticket(integer,text,text)','EXECUTE'),"
        "has_function_privilege('service_role','create_position_ticket(integer,text,text)','EXECUTE'),"
        "has_function_privilege('service_role','sync_create_position_ticket(uuid,integer,text,text,text,text,text,timestamptz,timestamptz,timestamptz)','EXECUTE');",
    )
    assert function_privileges == "t|f|t"


def test_ticket_rpc_rollback_and_concurrent_rescore(postgres16):
    _psql(postgres16, "DELETE FROM position_tickets;")
    _psql(
        postgres16,
        "CREATE FUNCTION fail_ticket() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'synthetic'; END$$;"
        "CREATE TRIGGER fail_ticket BEFORE INSERT ON position_tickets FOR EACH ROW EXECUTE FUNCTION fail_ticket();",
    )
    _as_user(
        postgres16, USER_A,
        "SELECT create_position_ticket(5,'synthetic rollback','custom');",
        check=False,
    )
    assert _psql(postgres16, "SELECT count(*) FROM position_tickets;") == "0"
    assert _psql(postgres16, f"SELECT status FROM positions WHERE id='{POSITION_A}';") == "review"
    _psql(postgres16, "DROP TRIGGER fail_ticket ON position_tickets; DROP FUNCTION fail_ticket();")

    def create() -> str:
        return _as_user(
            postgres16, USER_A,
            "SELECT create_position_ticket(5,'synthetic concurrent','rescore');",
        )

    with ThreadPoolExecutor(max_workers=2) as pool:
        receipts = list(pool.map(lambda _: create(), range(2)))
    assert len(receipts) == 2
    assert _psql(postgres16, "SELECT count(*) FROM position_tickets;") == "1"
    assert _psql(postgres16, "SELECT count(DISTINCT id) FROM position_tickets;") == "1"
    assert any('"deduplicated": false' in receipt for receipt in receipts)
    assert any('"deduplicated": true' in receipt for receipt in receipts)


def test_position_application_atomic_rollback_and_concurrency(postgres16):
    _psql(postgres16, "DELETE FROM applications; DELETE FROM position_transitions; UPDATE positions SET status='ready';")
    _psql(
        postgres16,
        "CREATE FUNCTION fail_applied_position() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN "
        "IF NEW.status='applied' THEN RAISE EXCEPTION 'synthetic'; END IF; RETURN NEW; END$$;"
        "CREATE TRIGGER fail_applied_position BEFORE UPDATE ON positions FOR EACH ROW EXECUTE FUNCTION fail_applied_position();",
    )
    _as_user(
        postgres16, USER_A,
        "SELECT mark_position_applied(5,clock_timestamp(),'user_manual',NULL);",
        check=False,
    )
    assert _psql(postgres16, "SELECT count(*) FROM applications;") == "0"
    assert _psql(postgres16, f"SELECT status FROM positions WHERE id='{POSITION_A}';") == "ready"
    _psql(postgres16, "DROP TRIGGER fail_applied_position ON positions; DROP FUNCTION fail_applied_position();")

    def mark() -> str:
        return _as_user(
            postgres16, USER_A,
            "SELECT mark_position_applied(5,clock_timestamp(),'user_manual',NULL);",
        )

    with ThreadPoolExecutor(max_workers=2) as pool:
        list(pool.map(lambda _: mark(), range(2)))
    assert _psql(postgres16, "SELECT status FROM positions;") == "applied"
    assert _psql(postgres16, "SELECT count(*) FROM applications WHERE status='applied' AND applied;") == "1"
    assert _psql(postgres16, "SELECT count(*) FROM position_transitions WHERE to_state='applied';") == "1"
