'use client'

import Link from 'next/link'
import { LandingI18nProvider, useLandingI18n } from '../components/landing/LandingI18n'
import LandingNav from '../components/landing/LandingNav'
import { LandingFooter } from '../components/landing/LandingCTA'
import ScrollToTop from '../components/landing/ScrollToTop'

const T = {
  it: {
    title: 'Termini di Servizio',
    updated: 'Ultimo aggiornamento: Aprile 2026',
    intro: 'Utilizzando Job Hunter Team (JHT) accetti i seguenti termini e condizioni.',
    s1_title: 'Licenza',
    s1_body: 'JHT e distribuito sotto licenza MIT. Puoi usarlo, modificarlo e redistribuirlo liberamente, purche la licenza originale sia inclusa. Il software e fornito "cosi com\'e", senza garanzie di alcun tipo.',
    s2_title: 'Uso consentito',
    s2_body: 'JHT e progettato per assistere nella ricerca di lavoro attraverso agenti AI. L\'uso del software per attivita illegali, spam, frode o per violare i termini di servizio di piattaforme terze (LinkedIn, Indeed, ecc.) e espressamente vietato.',
    s3_title: 'API di terze parti',
    s3_body: 'L\'utilizzo delle API AI (Anthropic, OpenAI, ecc.) e soggetto ai rispettivi termini di servizio e ai costi associati. Sei responsabile delle tue chiavi API e dei relativi addebiti. JHT non e responsabile per costi derivanti dall\'uso delle API.',
    s4_title: 'Responsabilita',
    s4_body: 'JHT genera contenuti (CV, cover letter, risposte) tramite intelligenza artificiale. Il contenuto generato potrebbe contenere errori o imprecisioni. Sei l\'unico responsabile della revisione e dell\'invio di qualsiasi materiale generato dal sistema.',
    s5_title: 'Dati personali',
    s5_body: 'Tutti i dati restano in locale sul tuo computer. Non raccogliamo ne trasmettiamo dati personali. Per maggiori dettagli, consulta la nostra Privacy Policy.',
    s6_title: 'Modifiche ai termini',
    s6_body: 'Ci riserviamo il diritto di aggiornare questi termini in qualsiasi momento. Le modifiche saranno pubblicate su questa pagina con la data di aggiornamento.',
    s7_title: 'Contatti',
    s7_body: 'Per domande sui termini di servizio, scrivi a info@jobhunterteam.ai.',
  },
  en: {
    title: 'Terms of Service',
    updated: 'Last updated: April 2026',
    intro: 'By using Job Hunter Team (JHT) you agree to the following terms and conditions.',
    s1_title: 'License',
    s1_body: 'JHT is distributed under the MIT License. You can use, modify, and redistribute it freely, provided the original license is included. The software is provided "as is", without warranties of any kind.',
    s2_title: 'Permitted use',
    s2_body: 'JHT is designed to assist in job searching through AI agents. Using the software for illegal activities, spam, fraud, or to violate the terms of service of third-party platforms (LinkedIn, Indeed, etc.) is expressly prohibited.',
    s3_title: 'Third-party APIs',
    s3_body: 'Use of AI APIs (Anthropic, OpenAI, etc.) is subject to their respective terms of service and associated costs. You are responsible for your API keys and related charges. JHT is not responsible for costs arising from API usage.',
    s4_title: 'Liability',
    s4_body: 'JHT generates content (CVs, cover letters, responses) through artificial intelligence. Generated content may contain errors or inaccuracies. You are solely responsible for reviewing and submitting any material generated by the system.',
    s5_title: 'Personal data',
    s5_body: 'All data stays locally on your computer. We do not collect or transmit personal data. For more details, see our Privacy Policy.',
    s6_title: 'Changes to terms',
    s6_body: 'We reserve the right to update these terms at any time. Changes will be posted on this page with the update date.',
    s7_title: 'Contact',
    s7_body: 'For questions about the terms of service, write to info@jobhunterteam.ai.',
  },
}

type TKey = keyof typeof T.it

function Section({ title, body }: { title: string; body: string }) {
  return (
    <div className="mb-6">
      <h2 className="text-[14px] font-bold text-[var(--color-white)] mb-2">{title}</h2>
      <p className="text-[12px] text-[var(--color-muted)] leading-relaxed">{body}</p>
    </div>
  )
}

function TermsContent() {
  const { lang } = useLandingI18n()
  const tx = T[lang as 'it' | 'en'] ?? T.it
  const t = (k: TKey) => tx[k] ?? k

  const sections: [TKey, TKey][] = [
    ['s1_title', 's1_body'], ['s2_title', 's2_body'], ['s3_title', 's3_body'],
    ['s4_title', 's4_body'], ['s5_title', 's5_body'], ['s6_title', 's6_body'],
    ['s7_title', 's7_body'],
  ]

  return (
    <main style={{ position: 'relative', zIndex: 1 }}>
      <LandingNav />
      <div className="max-w-3xl mx-auto px-5 pt-32 pb-20">
        <div className="mb-8 pb-6 border-b border-[var(--color-border)]">
          <div className="flex items-center gap-2 mb-3">
            <Link href="/" className="text-[10px] text-[var(--color-dim)] hover:text-[var(--color-muted)] no-underline transition-colors">Home</Link>
            <span className="text-[var(--color-border)]">/</span>
            <span className="text-[10px] text-[var(--color-muted)]">Terms</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-[var(--color-white)]">{t('title')}</h1>
          <p className="text-[var(--color-dim)] text-[10px] mt-2">{t('updated')}</p>
          <p className="text-[var(--color-muted)] text-[12px] mt-3 leading-relaxed">{t('intro')}</p>
        </div>

        {sections.map(([titleKey, bodyKey]) => (
          <Section key={titleKey} title={t(titleKey)} body={t(bodyKey)} />
        ))}

        <div className="mt-12 pt-6 border-t border-[var(--color-border)] flex items-center justify-between">
          <Link href="/privacy" className="text-[11px] text-[var(--color-dim)] hover:text-[var(--color-green)] transition-colors no-underline">
            &larr; Privacy Policy
          </Link>
          <Link href="/faq" className="text-[11px] text-[var(--color-dim)] hover:text-[var(--color-green)] transition-colors no-underline">
            FAQ &rarr;
          </Link>
        </div>
      </div>
      <LandingFooter />
      <ScrollToTop />
    </main>
  )
}

export default function TermsPage() {
  return (
    <LandingI18nProvider>
      <TermsContent />
    </LandingI18nProvider>
  )
}
