class_name UIStrings
## Tutte le stringhe UI del gioco, centralizzate. L'italiano (S, sotto)
## è la lingua di riferimento; le altre 6 lingue del web (en, hu, es,
## de, fr, pt) vivono in scripts/i18n/ui_<lang>.gd con le STESSE chiavi
## e fanno fallback sull'italiano se una chiave manca.

const LANGS := {
	"it": "Italiano", "en": "English", "hu": "Magyar", "es": "Español",
	"de": "Deutsch", "fr": "Français", "pt": "Português",
}
const LANG_CFG := "user://lang.cfg"

static var lang := "it"

static func _static_init() -> void:
	# TEST-AUTO: JHT_LANG forza la lingua per gli shot
	var forced := OS.get_environment("JHT_LANG")
	if LANGS.has(forced):
		lang = forced
		return
	var cfg := ConfigFile.new()
	if cfg.load(LANG_CFG) == OK:
		var saved := str(cfg.get_value("ui", "lang", "it"))
		if LANGS.has(saved):
			lang = saved

static func set_lang(l: String) -> void:
	if not LANGS.has(l):
		return
	lang = l
	var cfg := ConfigFile.new()
	cfg.set_value("ui", "lang", l)
	cfg.save(LANG_CFG)

static func t(key: String) -> String:
	if lang != "it":
		var d: Dictionary = _translations().get(lang, {})
		if d.has(key):
			return d[key]
	return S.get(key, key)

## I dizionari tradotti, caricati pigramente (i preload in const
## creerebbero un ciclo di parse se un file i18n mancasse in dev).
static var _tr_cache := {}

static func _translations() -> Dictionary:
	if _tr_cache.is_empty():
		for l in LANGS:
			if l == "it":
				continue
			var path := "res://scripts/i18n/ui_%s.gd" % l
			if ResourceLoader.exists(path):
				var script: GDScript = load(path)
				_tr_cache[l] = script.get_script_constant_map().get("S", {})
	return _tr_cache

const S := {
	# ── Title screen ──────────────────────────────────────────────
	"title.wordmark": "JOB HUNTER TEAM",
	"title.name_title": "Presentiamoci",
	"title.name_sub": "Come ti chiami? Il team ti chiamerà per nome.",
	"title.name_first": "Nome",
	"title.name_last": "Cognome (facoltativo)",
	"title.name_enter": "ENTRA IN UFFICIO",
	"title.name_skip": "Preferisco non dirlo, entriamo",
	"title.press_enter": "▶ PREMI INVIO",
	"title.footer": "prototipo — dati mock, nessun backend",
	"title.hint_pause": "ESC menu",

	# ── Menu pausa ────────────────────────────────────────────────
	"pause.title": "PAUSA",
	"pause.resume": "RIPRENDI",
	"pause.window": "FINESTRA / SCHERMO INTERO",
	"pause.quit": "ESCI DAL GIOCO",
	"pause.shutdown": "FERMO IL TEAM E CHIUDO…",
	"pause.detaching": "ESCO · IL TEAM CONTINUA A LAVORARE",
	"shutdown.title": "STAI PER CHIUDERE LA FINESTRA",
	"shutdown.lead": "Gli agenti lavorano nel container, non in questa finestra. Adesso ne stanno lavorando %d: scegli cosa ne faccio.",
	"shutdown.graceful": "FERMA IL TEAM E CHIUDI",
	"shutdown.graceful_hint": "Ogni agente annota dove è arrivato, poi il team si ferma e il container si spegne. Alla riapertura si riprende da lì.",
	"shutdown.forced": "CHIUDI TUTTO SUBITO",
	"shutdown.forced_hint": "Non aspetta nessuno: chi sta lavorando non fa in tempo a salvare il punto in cui è arrivato.",
	"shutdown.forced_now": "NON ASPETTARE · CHIUDI SUBITO",
	"shutdown.cancel": "ANNULLA",
	"shutdown.detach": "ESCI · IL TEAM CONTINUA A LAVORARE",
	"shutdown.detach_hint": "Si chiude solo la finestra: gli agenti restano al lavoro nel container e il budget continua a scorrere.",
	"shutdown.detach_body": "Chiudo solo la finestra: il container resta acceso e gli agenti continuano a cercare, valutare e scrivere anche stanotte. Continuano anche a consumare budget, esattamente come se fossi qui a guardarli.",
	"shutdown.detach_back": "Riapri il gioco quando vuoi e ritrovi l'ufficio al punto in cui è arrivato. Per fermare il team basta rientrare e, chiudendo, scegliere di fermarlo.",
	"shutdown.detach_confirm": "ESCI COSÌ, LI LASCIO LAVORARE",
	"shutdown.ordered": "Ho chiesto al Capitano di chiudere la giornata: ogni agente annota dove era arrivato, poi si ferma.",
	"shutdown.waiting": "Ancora %d agenti al lavoro · %d s. Puoi aspettare o chiudere subito.",
	"shutdown.done": "Team fermo. Chiudo.",
	"headless.back": "○ IL TEAM HA LAVORATO SENZA DI TE PER %s · ORA SONO %d IN UFFICIO",
	"headless.dur_min": "%d min",
	"headless.dur_hour": "%dh %dm",

	# ── HUD ───────────────────────────────────────────────────────
	"hud.team": "TEAM",
	"hud.positions_today": "POSIZIONI OGGI",
	"hud.avg_score": "SCORE MEDIO",
	"hud.budget": "BUDGET",
	"hud.registry_hint": "TAB registro",
	"hud.team_default": "Team JHT",

	# ── Registro candidature ──────────────────────────────────────────
	"registry.title": "REGISTRO CANDIDATURE",
	"registry.streak": "STREAK %d giorni · %d freeze",
	"registry.empty": "nessuna candidatura ancora — parla col reparto Ricerca",
	"registry.stage_0": "inviata",
	"registry.stage_1": "screening",
	"registry.stage_2": "colloquio",
	"registry.stage_3": "offerta",
	"registry.close": "[TAB] chiudi",

	# ── Archivio CV (click sullo scaffale output) ─────────────────
	"cv.title": "ARCHIVIO CV SCRITTI",
	"cv.subtitle": "Documenti del reparto Candidature e del Controllo qualità",
	"cv.total": "CV SCRITTI",
	"cv.pass": "PASS",
	"cv.review": "DA RIVEDERE",
	"cv.avg_score": "SCORE MEDIO",
	"cv.list": "ELENCO CV",
	"cv.detail": "PANORAMICA CV",
	"cv.empty": "Nessun CV scritto è ancora presente nello snapshot.",
	"cv.select": "Seleziona un CV dall’elenco per vedere la panoramica.",
	"cv.written_by": "SCRITTO DA",
	"cv.reviewed_by": "REVISIONATO DA",
	"cv.artifacts": "DOCUMENTI PRODOTTI",
	"cv.match": "MATCH POSIZIONE",
	"cv.open_position": "APRI SCHEDA COMPLETA DELLA POSIZIONE",
	"cv.close": "ESC o click fuori per chiudere",
	"cv.preview": "ANTEPRIMA",
	"cv.preview_title": "ANTEPRIMA DOCUMENTO",
	"cv.doc_loading": "Recupero il documento dal container…",
	"cv.doc_error": "Documento non disponibile: ",
	"cv.doc_pdf_only": "Per questo documento esiste solo il PDF: aprilo qui sotto.",
	"cv.open_pdf": "APRI PDF",
	"cv.opening_pdf": "SCARICO…",
	"cv.doc_close": "ESC o click fuori per tornare all'archivio",
	"cv.tab_text": "TESTO",
	"cv.tab_pdf": "ANTEPRIMA PDF",
	"cv.pdf_rendering": "Preparo l'anteprima del PDF…",
	"cv.pdf_no_tool": "Nessun renderizzatore PDF locale: usa APRI PDF per il viewer di sistema.",
	"cv.pdf_first_page_only": "Anteprima limitata alla prima pagina (renderizzatore ridotto).",
	"cv.reveal": "MOSTRA NELLA CARTELLA",
	"cv.reveal_done": "Copia salvata in ",
	"cv.open_failed": "Apertura fallita: ",

	# ── Code delle pile di reparto ───────────────────────────────
	"queue.title": "CODA %s",
	"queue.subtitle": "Posizioni nello stato operativo rappresentato da questa pila",
	"queue.count": "%d POSIZIONI IN CODA",
	"queue.list": "POSIZIONI DA ELABORARE",
	"queue.detail": "PANORAMICA POSIZIONE",
	"queue.empty": "La coda è vuota: nessuna posizione attende in questa fase.",
	"queue.select": "Seleziona una posizione per vedere i dettagli.",
	"queue.open_position": "APRI SCHEDA COMPLETA",
	"queue.close": "ESC o click fuori per chiudere",
	"queue.phase.to_analyze": "DA ANALIZZARE",
	"queue.phase.analyzed": "ANALIZZATE · ATTESA SCORE",
	"queue.phase.with_score": "CON SCORE · ATTESA SCRITTORI",
	"queue.phase.to_write": "CV DA SCRIVERE / REVISIONARE",
	"queue.phase.written": "CV SCRITTI · ATTESA ESITO",
	"hud.dialogue_next": "[INVIO] continua",
	"hud.dialogue_skip": "[ESC] chiudi",

	"tour.title": "TOUR DELL'UFFICIO",
	"tour.step_assistant": "Saluta l'Assistente",
	"tour.step_depts": "Il giro dei reparti",
	"tour.step_doctor": "Una visita al Dottore",
	"tour.step_mentor": "La chiacchierata col Mentor",
	"tour.step_coordinator": "Il Coordinatore e il setup",
	"tour.step_launch": "Prepara il lancio",
	"tour.chk_container": "Container attivo",
	"tour.chk_provider": "Provider collegato",
	"tour.chk_profile": "Profilo completo",
	"tour.hint_talk": "Clicca l'Assistente col diamante per iniziare il giro.",
	"tour.hint_follow": "L'Assistente ti fa strada: seguila, pensa a tutto lei.",
	"tour.hint_free": "Giro libero: clicca chi ha il diamante, in qualsiasi ordine.",
	"tour.hint_launch": "Completa i tre requisiti: il pulsante giallo in alto apre la checklist.",
	"tour.skip": "SALTA IL TOUR",
	"tour.done": "TOUR COMPLETATO ✓",

	# ── Pannello reparto ──────────────────────────────────────────
	"dept.desks": "POSTAZIONI",
	"dept.desk_free": "postazione libera",
	"dept.close": "click fuori per chiudere",
	"dept.inbox": "Inbox: %d fogli in attesa",

	# ── Scheda agente ─────────────────────────────────────────────
	"agent.activity": "ULTIME ATTIVITÀ",
	"agent.activity_none": "nessuna attività registrata",
	"agent.talk": "▶ PARLA",
	"agent.chat": "▶ CHAT COL TEAM",
	"agent.pile": "Fogli sulla scrivania: %d",
	"agent.thinking": "◉ MOSTRA ATTIVITÀ INTERNA",
	"agent.thinking_tooltip": "Osserva lo stream tmux dell'agente in sola lettura",
	"agent.thinking_unavailable": "Disponibile quando l'agente reale è attivo",
	"agent.thinking_title": "ATTIVITÀ INTERNA — %s",
	"agent.thinking_subtitle": "Stream live della sessione tmux dell'agente",
	"agent.thinking_loading": "● COLLEGAMENTO…",
	"agent.thinking_waiting": "Attendo il primo snapshot del terminale…",
	"agent.thinking_readonly": "SOLA LETTURA · NESSUN TASTO VIENE INVIATO",
	"agent.thinking_bottom": "↓ TORNA IN FONDO",
	"agent.thinking_error": "STREAM NON DISPONIBILE",
	"agent.thinking_live": "STREAM LIVE",
	"agent.thinking_empty": "La sessione è attiva ma non ha ancora prodotto output.",
	"coord.open": "◆ CONSOLE COORDINATORE",
	"coord.open_tip": "Modalità operative, automazioni e ordini permanenti del team",
	"coord.title": "CONSOLE DEL COORDINATORE",
	"coord.subtitle": "Policy applicate a codice, code operative e ordini al Capitano",
	"coord.nav_control": "◆ CONTROLLO E ORDINI",
	"coord.nav_monitor": "▥ MONITORAGGIO",
	"coord.nav_thinking": "◉ ATTIVITÀ INTERNA",
	"coord.nav_chat": "▶ CHAT COL COORDINATORE",
	"coord.view_control": "CONTROLLO OPERATIVO",
	"coord.view_monitor": "MONITORAGGIO COORDINATORE",
	"coord.coordinator": "Coordinatore",
	"coord.monitor_title": "Monitoraggio del Coordinatore",
	"coord.monitor_desc": "Stato live e storico completo delle risorse del Capitano",
	"coord.monitor_live": "Risorse live",
	"coord.monitor_live_desc": "Ultimo campione dal processo tmux e dal token-meter della VPS.",
	"coord.monitor_history": "Storico e consumo",
	"coord.monitor_history_desc": "Token, quote 5h e weekly, throttle, azioni DB, CPU e RAM sullo stesso asse temporale.",
	"coord.m_status": "Stato",
	"coord.m_session": "Sessione",
	"coord.m_ram": "RAM live",
	"coord.m_tokens": "Token finestra",
	"coord.m_ram_live": "RAM processo · ultimi campioni",
	"coord.m_token_buckets": "Token · bucket recenti",
	"coord.monitor_no_detail": "Nessuna attività dettagliata disponibile.",
	"coord.loading": "CARICAMENTO…",
	"coord.refresh": "Aggiorna dati e code",
	"coord.queues": "Panoramica code",
	"coord.queues_desc": "Carico reale del team in questo momento",
	"coord.mode": "Modalità di lavoro",
	"coord.mode_desc": "Cambia obiettivo all’intero team con una policy persistente.",
	"coord.maintenance": "Modalità manutenzione del portfolio",
	"coord.maintenance_tip": "Ferma il sourcing autonomo e cura le posizioni esistenti",
	"coord.normal_note": "In modalità ricerca attiva il Coordinatore bilancia normalmente scouting, analisi e scoring.",
	"coord.stop_search": "Ferma la ricerca di nuove posizioni",
	"coord.expired": "Scarta le posizioni scadute a rotazione",
	"coord.cv_score": "Score minimo per scrivere un CV",
	"coord.precheck": "Verifica che l'offerta sia viva prima del CV",
	"coord.automation": "Automazioni e budget",
	"coord.automation_desc": "Decidi quali arricchimenti possono consumare budget in autonomia.",
	"coord.economy": "Risparmio token: spegni enrichment autonomo",
	"coord.economy_tip": "Le richieste esplicite dell'utente restano sempre eseguibili",
	"coord.geo": "Geolocalizza automaticamente gli uffici",
	"coord.geo_desc": "Completa la mappa per offerte con sede fisica e score sufficiente.",
	"coord.min_score": "Score minimo geolocalizzazione",
	"coord.zero_all": "0 = nessuna soglia",
	"coord.non_remote": "Solo posizioni non remote",
	"coord.logo": "Scarica automaticamente i loghi aziendali",
	"coord.logo_desc": "Arricchisce le schede delle aziende che superano la soglia.",
	"coord.min_score_logo": "Score minimo logo",
	"coord.recheck": "Ricontrolla periodicamente le posizioni",
	"coord.recheck_desc": "Verifica che le offerte migliori siano ancora aperte dopo N giorni.",
	"coord.score": "Score minimo",
	"coord.days": "Più vecchie di giorni",
	"coord.save": "SALVA POLICY E AVVISA IL COORDINATORE",
	"coord.orders": "Ordini rapidi",
	"coord.orders_desc": "Azioni una tantum: partono subito ma non cambiano la policy permanente.",
	"coord.preset_scout": "SOLO SCOUTING PER IL PROSSIMO CICLO",
	"coord.preset_balance": "RIBILANCIA TUTTA LA PIPELINE",
	"coord.preset_reanalyze": "RIANALIZZA LE POSIZIONI OBSOLETE",
	"coord.preset_maintenance": "ESEGUI UN GIRO DI MANUTENZIONE",
	"coord.preset_scout_desc": "Concentra temporaneamente capacità e budget sulla ricerca di nuove offerte.",
	"coord.preset_balance_desc": "Analizza i colli di bottiglia e sposta gli agenti sulla coda più urgente.",
	"coord.preset_reanalyze_desc": "Usa le soglie configurate sopra per aggiornare le offerte obsolete.",
	"coord.preset_maintenance_desc": "Smaltisce scadute, geocoding, loghi e recheck attualmente abilitati.",
	"coord.execute": "ESEGUI ORA",
	"coord.custom": "Ordine personalizzato",
	"coord.prompt_scout": "Per il prossimo ciclo concentra il budget sugli Scout: cerca nuove posizioni coerenti col profilo, senza avviare lavoro accessorio. Verifica prima il pacing e scala gradualmente.",
	"coord.prompt_balance": "Controlla tutte le code e ribilancia il team sulla fase che sta bloccando la pipeline. Rispetta il budget, non duplicare agenti occupati e spiegami in chat cosa hai deciso.",
	"coord.prompt_reanalyze": "Fai rianalizzare agli Analisti tutte le posizioni vive non controllate da più di %d giorni con score almeno %d. Distribuisci la coda senza duplicati e cadenzala sul budget.",
	"coord.prompt_maintenance": "Esegui ora un giro delle code di manutenzione abilitate: scadute, recheck, geocoding e loghi. Assegna code diverse agli Analisti e fermati quando sono vuote.",
	"coord.command_placeholder": "Scrivi un ordine specifico al Coordinatore…",
	"coord.permanent": "Rendi questa istruzione una direttiva permanente",
	"coord.send": "INVIA ORDINE",
	"coord.board": "Bacheca permanente del team",
	"coord.board_tip": "Queste direttive sopravvivono ai riavvii e prevalgono sui comportamenti predefiniti.",
	"coord.close": "ESC o click fuori per chiudere",
	"coord.saving": "SALVATAGGIO…",
	"coord.empty_order": "Scrivi prima un ordine",
	"coord.sending": "INVIO AL COORDINATORE…",
	"coord.mode_maintenance": "MANUTENZIONE",
	"coord.mode_normal": "RICERCA ATTIVA",
	"coord.ready": "POLICY E CODE AGGIORNATE",
	"coord.q_new": "NUOVE",
	"coord.q_analysis": "ANALISI",
	"coord.q_scored": "SCORATE",
	"coord.q_geo": "GEO",
	"coord.q_logo": "LOGHI",
	"coord.q_recheck": "RECHECK",
	"coord.q_expired": "SCADUTE",
	"coord.board_empty": "Nessuna direttiva permanente attiva.",
	"coord.archive": "ARCHIVIA",
	"coord.saved": "MODIFICA APPLICATA",
	"coord.error": "ERRORE: %s",
	"coord.sent": "ORDINE CONSEGNATO",

	# ── Pannello chat con l'agente ────────────────────────────────
	"chat.title": "CHAT — %s",
	"chat.placeholder": "scrivi un messaggio…",
	"chat.send": "INVIA",
	"chat.you": "TU",
	"chat.empty": "nessun messaggio ancora: scrivi tu per primo",
	"chat.waiting": "in attesa della risposta",
	"chat.besteffort": "◐ questo agente legge i messaggi ma potrebbe non rispondere in chat",
	"chat.menu": "CHAT AGENTI",
	"chat.replies": "risponde in chat",
	"chat.maybe": "legge, risposta non garantita",
	"guided.choose": "SCEGLI UNA RISPOSTA",
	"guided.choice_placeholder": "scegli una delle risposte qui sopra…",
	"guided.free_placeholder": "scrivi liberamente oppure usa una risposta suggerita…",
	"guided.offline_note": "◆ conversazione guidata offline — nessun token e nessun LLM necessario",
	"guided.hybrid_note": "◆ guida attiva — puoi anche scrivere liberamente all’agente collegato",
	"guided.agent_unavailable": "◆ provider collegato — avvia il team per usare la chat reale",
	"guided.ai_suggestions": "RISPOSTE SUGGERITE DALL’AGENTE",
	"chat.expand": "SCHERMO INTERO",
	"chat.shrink": "RIDUCI",

	# ── Wizard onboarding (foto badge con l'Assistente) ───────────
	"wizard.title": "CONFIGURA IL TUO PROFILO",
	"wizard.subtitle": "Parla con l'Assistente: il badge a sinistra si compila da solo mentre vi confrontate. Carica il CV per fare prima.",
	"wizard.profile": "BADGE PROFILO",
	"wizard.progress": "%d/%d campi",
	"wizard.assistant": "ASSISTENTE",
	"wizard.chat_empty": "l'Assistente sta arrivando: intanto puoi scrivere tu o caricare il CV",
	"wizard.upload": "CARICA CV",
	"wizard.uploading": "carico %s…",
	"wizard.upload_fail": "upload fallito: %s",
	"wizard.attach_msg": "Ti ho caricato un documento: puoi estrarre da qui il mio profilo?",
	"wizard.connecting": "connessione al team…",
	"wizard.booting_assistant": "avvio dell'assistente in corso (può volerci un minuto)…",
	"wizard.sim_badge": "SIMULAZIONE — nessuna VPS collegata",
	"wizard.waiting_profile": "completa il badge con l'Assistente per entrare in ufficio",
	"wizard.ready_note": "badge completo: il team ti aspetta",
	"wizard.enter_office": "ENTRA IN UFFICIO →",
	"wizard.back_office": "← TORNA IN UFFICIO",
	"wizard.profile_done_back": "✓ PROFILO COMPLETO · TORNA IN UFFICIO",
	"wizard.setup_required": "attiva container e provider dall’ufficio per parlare con l’Assistente",
	"wizard.f.name": "Nome",
	"wizard.f.email": "Email",
	"wizard.f.target_role": "Ruolo target",
	"wizard.f.location": "Località",
	"wizard.f.experience_years": "Anni di esperienza",
	"wizard.f.seniority_target": "Seniority",
	"wizard.f.skills": "Competenze (≥2)",
	"wizard.f.languages": "Lingue (≥1)",

	# ── Impostazioni → Collega VPS ────────────────────────────────
	"vps.intro": "Collega la VPS del tuo team: IP e chiave SSH, al resto pensa il gioco.",
	"vps.ip": "IP DELLA VPS",
	"vps.user": "UTENTE SSH",
	"vps.user_note": "Utente con cui il provider apre la VPS: root su Hetzner, ubuntu su OVH e AWS, il nome dell'account su Google Cloud e Azure. Vuoto vale root.",
	"vps.key": "CHIAVE SSH (privata)",
	"vps.key_browse": "SFOGLIA…",
	"vps.connect": "▶ COLLEGA",
	"vps.disconnect": "■ SCOLLEGA",
	"vps.state_disconnected": "non collegato",
	"vps.state_connecting": "collegamento in corso…",
	"vps.state_connected": "COLLEGATO",
	"vps.state_error": "ERRORE",
	"vps.missing_fields": "inserisci IP e chiave SSH",
	"vps.agents_live": "AGENTI ATTIVI SULLA VPS",
	"vps.agents_none": "nessun agente attivo in questo momento",
	"vps.steps": "1  Crea la chiave  →  2  aggiungila alla VPS  →  3  verifica SSH  →  4  prepara e collega",
	"vps.key_section": "1 · CHIAVE SSH DEDICATA",
	"vps.key_generate": "GENERA CHIAVE",
	"vps.key_copy": "COPIA PUBBLICA",
	"vps.key_open": "APRI CARTELLA",
	"vps.key_note": "La chiave privata resta sul computer; al provider va incollata soltanto la riga .pub.",
	"vps.key_fingerprint_none": "Fingerprint: non disponibile per la chiave selezionata — non c'è niente da confrontare con il provider.",
	"vps.destination": "2 · SERVER DI DESTINAZIONE",
	"vps.fingerprint_note": "VERIFICA SSH mostra il fingerprint host: confrontalo con quello indicato dal provider.",
	"vps.connect_existing": "COLLEGA SENZA INSTALLARE",
	"vps.verify_ssh": "VERIFICA SSH",
	"vps.prepare": "PREPARA E COLLEGA AUTOMATICAMENTE",
	"vps.advanced": "CONSOLE AVANZATA",
	"vps.migration_title": "3 · MIGRAZIONE COMPLETA (OPZIONALE)",
	"vps.migration_desc": "Trasferisce database, profilo, documenti, configurazione, login provider e pairing cloud. Chiavi SSH e runtime restano sulla macchina a cui appartengono. Snapshot, checksum e backup vengono verificati prima dello scambio.",
	"vps.source_local": "DA QUESTO COMPUTER",
	"vps.source_saved": "DALLA VPS ATTUALMENTE SALVATA",
	"vps.migrate_to_vps": "MIGRA TUTTO SULLA NUOVA VPS  →",
	"vps.migrate_to_local": "←  MIGRA DALLA VPS A QUESTO COMPUTER",
	"vps.migration_note": "La sorgente viene fermata e disarmata soltanto dopo la verifica della destinazione. Qualunque errore ripristina sorgente e destinazione.",
	"vps.confirm_vps_title": "Migrare tutto sulla nuova VPS?",
	"vps.confirm_source_local": "La sorgente è questo computer.",
	"vps.confirm_source_vps": "La sorgente è la VPS attualmente salvata.",
	"vps.confirm_body": "Il team verrà fermato durante lo snapshot. I dati non saranno cancellati: la destinazione riceverà una copia verificata e conserverà un backup pre-migrazione.",
	"vps.confirm_vps_ok": "FERMA, COPIA E ATTIVA LA NUOVA VPS",
	"vps.confirm_local_title": "Riportare tutto su questo computer?",
	"vps.confirm_local_body": "La VPS verrà fermata, copiata e verificata prima di attivare il team locale. I dati locali attuali avranno un backup e saranno ripristinati automaticamente se qualcosa fallisce.",
	"vps.confirm_local_ok": "FERMA LA VPS, COPIA E ATTIVA IN LOCALE",

	# ── Posizioni (vista web migrata) ─────────────────────────────
	"pos.need_vps": "Collega la VPS per vedere le posizioni reali del team (Impostazioni → Collega VPS).",
	"pos.count": "%d posizioni · %d visibili",
	"pos.clear": "✕ PULISCI FILTRI",
	"pos.filters": "FILTRI (%d)",
	"pos.filters_hide": "NASCONDI FILTRI",
	"pos.all": "TUTTI",
	"pos.selected": "%d SELEZIONATI",
	"pos.rows": "RIGHE",
	"pos.range": "%d–%d di %d",
	"pos.page": "PAGINA %d / %d",
	"pos.previous": "◀ PRECEDENTE",
	"pos.next": "SUCCESSIVA ▶",
	"pos.no_match": "nessuna posizione con questi filtri",
	"pos.f_status": "STATO",
	"pos.f_family": "FAMIGLIA DI RUOLO",
	"pos.f_country": "PAESE",
	"pos.f_mode": "MODALITÀ",
	"pos.uncategorized": "senza categoria",

	# ── Dettaglio posizione ───────────────────────────────────────
	"pos.back": "◀ POSIZIONI",
	"pos.salary": "STIPENDIO",
	"pos.salary_estimated": "stima del team",
	"pos.salary_declared": "dichiarato nell'annuncio",
	"pos.summary": "RIASSUNTO DELL'ANNUNCIO",
	"pos.score_title": "SCORE — %d/100",
	"pos.score_none": "non ancora studiata dal reparto Compatibilità",
	"pos.score_rationale": "RAZIONALE DELLO SCORER",
	"pos.critic_title": "VOTO DEL CRITICO — %.1f/10",
	"pos.critic_none": "nessun controllo qualità ancora completato",
	"pos.highlights": "PUNTI CHIAVE",
	"pos.actions": "AZIONI RICHIESTE AL TEAM",
	"pos.act_write": "Scrittura CV",
	"pos.act_geocode": "Geocodifica ufficio",
	"pos.act_recheck": "Verifica annuncio ancora aperto",
	"pos.act_requested": "richiesta",
	"pos.act_not_requested": "non richiesta",
	"pos.act_note": "// le azioni le esegue il team sulla VPS — per chiedere qualcosa apri un ticket qui sotto",
	"pos.excluded_title": "ESCLUSA DALL'UTENTE",
	"pos.tickets": "TICKET APERTI COL TEAM",
	"pos.ticket_none": "nessun ticket per questa posizione",
	"pos.ticket_placeholder": "scrivi una richiesta al team su questa posizione…",
	"pos.ticket_send": "APRI TICKET",
	"pos.ticket_sending": "invio del ticket alla VPS…",
	"pos.ticket_ok": "✔ ticket aperto — il Coordinatore lo prenderà in carico",
	"pos.ticket_err": "✘ ticket non creato: %s",
	"pos.ticket_need_vps": "// collega la VPS per aprire ticket col team",
	"pos.found": "trovata da %s · %s",
	"pos.open_url": "apri l'annuncio nel browser",
	"pos.open_yes": "annuncio APERTO all'ultima verifica",
	"pos.open_no": "annuncio NON PIÙ APERTO",
	"pos.office_address": "INDIRIZZO",
	"pos.office_verified": "verificato dagli Analisti",
	"pos.office_approx": "non verificato · centro città",

	# ── Candidature e Notifiche (dati reali) ──────────────────────
	"apps.ready": "CV pronto",
	"apps.applied": "inviata",
	"apps.response": "risposta ricevuta",
	"apps.empty_live": "nessuna candidatura ancora — i CV pronti compariranno qui",
	"notifs.ticket_resolved": "ticket risolto: %s",
	"notifs.ticket_assigned": "ticket in lavorazione: %s",
	"notifs.scored": "studiata dal reparto Compatibilità: %s",
	"notifs.cv_ready": "CV scritto: %s",
	"notifs.applied": "candidatura inviata: %s",
	"notifs.response": "risposta ricevuta: %s",
	"notifs.empty": "nessuna notifica recente dal team",
	"agents.comms": "COMUNICAZIONI NEL TEAM",
	"agents.no_comms": "nessuna comunicazione recente",
	"agents.chat_besteffort": "(risposta non garantita: protocollo chat non nel suo prompt)",

	# ── GlobalSearch (Cmd+K) ──────────────────────────────────────
	"search.placeholder": "cerca posizioni: titolo, azienda, città…  (ESC chiude)",
	"search.no_match": "nessuna posizione trovata",
	"search.need_vps": "collega la VPS per cercare tra le posizioni reali",

	# ── Profilo (editabile: paradigma desktop app) ────────────────
	"prof.name": "Nome",
	"prof.email": "Email",
	"prof.target_role": "Ruolo target",
	"prof.location": "Località",
	"prof.experience": "Anni di esperienza",
	"prof.seniority": "Seniority target",
	"prof.industry": "Settore",
	"prof.nationality": "Nazionalità",
	"prof.languages": "LINGUE (separate da virgola)",
	"prof.skills": "SKILL PRIMARIE (separate da virgola)",
	"prof.salary": "SALARY TARGET (min / max / valuta)",
	"prof.save": "▶ SALVA PROFILO",
	"prof.saving": "salvataggio sulla VPS…",
	"prof.saved": "✔ profilo salvato — il team lo userà dal prossimo giro",
	"prof.save_err": "✘ salvataggio fallito: %s",

	# ── Mappa OSM ─────────────────────────────────────────────────
	"map.hint": "trascina per muoverti · rotella/pinch per lo zoom · click su un pin per le sue posizioni",
	"map.globe_hint": "trascina per ruotare il mondo · click su un pin per atterrarci · avvicinati per la mappa",
	"map.filters": "FILTRI",
	"map.f_score": "SCORE",
	"map.f_city": "CITTÀ",
	"map.score_none": "senza punteggio",
	"map.overview": "PANORAMICA",
	"map.card_hint": "click su una posizione per aprire la scheda",
	"map.card_hint_all": "%d posizioni · scorri l’elenco e clicca per aprire la scheda",
	"map.cluster": "%d posizioni · %d località",
	"map.pin_approx": "pin sul centro città: indirizzo esatto non verificato",

	# ── Orari di lavoro (editabili, con stima dinamica) ───────────
	"hours.intro": "Le finestre in cui il team lavora: modifica e salva, il pacing si adegua.",
	"hours.tz": "Timezone",
	"hours.windows": "FINESTRE (giorni · dalle → alle)",
	"hours.add": "+ AGGIUNGI FINESTRA",
	"hours.presets": "PARTI DA QUI",
	"hours.preset_office": "Orario d'ufficio",
	"hours.preset_evening": "Sera e weekend",
	"hours.preset_always": "Sempre attivo",
	"hours.first_time": "Non hai ancora scelto gli orari: parti da una di queste proposte e correggila come vuoi.",
	"hours.need_team": "Per impostare gli orari serve il team acceso: torna al passo 01 e avvia il container.",
	"hours.estimate": "≈ %.0f ore attive/settimana → stima ~%.1f posizioni nuove/giorno · budget riproporzionato al %d%% dell'attuale",
	"hours.invalid": "✘ finestra non valida: giorni mon…sun e orari HH:MM",
	"hours.save": "▶ SALVA ORARI",
	"hours.saved": "✔ orari salvati — il pacing del team si adegua dal prossimo tick",

	# ── Impostazioni → Lingua ─────────────────────────────────────
	"lang.intro": "Lingua dell'interfaccia — le 7 lingue del sito.",
	"lang.note": "// si applica subito ai pannelli; riapri quelli già aperti per vederli tradotti",

	# ── Statistiche: grafici cross-filter (come la dashboard web) ─
	"stats.hint": "// click su una barra per filtrare: gli altri grafici si aggiornano",
	"stats.filters": "FILTRI ATTIVI: %d",
	"stats.reset": "✕ AZZERA",
	"stats.types": "TIPI DI RUOLO",
	"stats.countries": "PAESI",
	"stats.cities": "CITTÀ",
	"stats.scores": "SCORE (fasce da 5)",
	"stats.salaries": "STIPENDI (fasce da 20k €)",
	"stats.matches": "POSIZIONI CORRISPONDENTI — %d",
	"stats.no_city": "· senza città: %d",
	"stats.no_country": "(senza paese)",
	"stats.empty": "nessun dato con questi filtri",
	"stats.need_vps": "collega la VPS per i grafici sui dati reali",

	# ── Monitoraggio risorse: usage nel tempo + consumi agenti ────
	"side.usage_history": "Usage",
	"side.usage_agents": "Consumi agenti",
	"usage.no_data": "nessun dato nella finestra",
	"usage.loading": "◌ carico lo storico…",
	"usage.loading_veil": "CARICO LO STORICO",
	"usage.donut_back": "◀ torna al totale",
	"usage.donut_hint": "// hover per i dettagli · click su (altri) per approfondire",
	"usage.role_pooled": "×%d istanze",
	"usage.error": "✘ storico non disponibile: %s",
	"usage.to_now": "ORA",
	"usage.hint": "// finestra %s · legenda cliccabile per nascondere una serie",
	"usage.group_quota": "QUOTE %",
	"usage.group_velocity": "VELOCITÀ",
	"usage.group_tokens": "TOKEN",
	"usage.group_events": "EVENTI",
	"usage.series_usage": "usage 5h %",
	"usage.series_weekly": "weekly %",
	"usage.series_projection": "proiezione %",
	"usage.series_velocity": "velocità %/h",
	"usage.series_velocity_ideal": "velocità ideale %/h",
	"usage.series_weighted": "token pesati · finestra 5h",
	"usage.series_events": "eventi API · finestra 5h",
	"usage.series_throttle": "pause pacing · s per bucket",
	"usage.stacked": "CHI CONSUMA QUANDO — kT per bucket, impilati",
	"usage.ranking": "CLASSIFICA CONSUMI — kT nel periodo",
	"usage.share": "QUOTA SUL TOTALE",
	"usage.heatmap": "MAPPA ORARIA — kT per ora × giorno",
	"usage.heatmap_hint": "// intensità = kT consumati in quell'ora di quel giorno",
	"usage.others": "(altri)",
	"usage.total": "totale %s kT",
	"usage.no_agents": "nessun consumo per-agente nel periodo (i log CLI coprono ~10 giorni)",
	"agent.stats": "▤ SCHEDA E GRAFICI",
	"agent.history_title": "STORICO CONSUMI E AZIONI",
	"agent.history_hint": "// ogni serie ha la sua scala (max in legenda) · click sulla legenda per accendere/spegnere",
	"agent.history_all": "TUTTE",
	"agent.history_none": "NESSUNA",
	"agent.hs_tokens": "token kt",
	"agent.hs_pct5h": "usage finestra 5h %",
	"agent.hs_pctweek": "usage weekly %",
	"agent.hs_day": "consumo di oggi · % weekly cum.",
	"agent.hs_throttle": "throttle s",
	"agent.hs_db": "azioni db",
	"agent.hs_cpu_agent": "cpu agente %",
	"agent.hs_ram_agent": "ram agente MB",
	"agent.hs_cpu": "cpu container %",
	"agent.hs_ram": "ram container %",
	"agent.history_ctx_note": "// cpu/ram agente = sampler agent-vitals (dal prossimo lancio team); container = contesto",

	# ── Dashboard: pipeline del flusso reale ──────────────────────
	"dash.pipeline": "PIPELINE",
	"dash.pl_to_analyze": "Da analizzare",
	"dash.pl_analyzed": "Analizzate",
	"dash.pl_with_score": "Con lo score",
	"dash.pl_to_write": "Da scrivere",
	"dash.pl_written": "Scritte",
	"dash.pl_hint": "// click su un box per aprire le posizioni filtrate",

	# ── Comuni (liste troncate, note sola-lettura, attese dati) ───────
	"common.more": "… e altre %d",
	"common.readonly_desktop": "// sola lettura in questa vista",
	"common.readonly_chat": "// sola lettura — usa la chat nativa dell'agente",
	"common.data_incoming": "// dati in arrivo dalla VPS…",
	"common.updated": "aggiornato: %s",

	# ── Badge simulazione / dati reali ────────────────────────────────
	"sim.live_vps": "● DATI REALI — VPS",
	"sim.live_local": "● DATI REALI — QUESTO COMPUTER",
	# ── Finestra di lavoro esaurita ───────────────────────────────────
	"budget.exhausted": "Il team ha esaurito la finestra di lavoro — riprende %s",
	"budget.near_limit": "Finestra di lavoro al %d%% — il team rallenta, si riapre %s",
	"budget.in_minutes": "fra %d min",
	"budget.in_hours": "fra %dh %02dm",
	"sim.mock": "◐ SIMULAZIONE — dati non reali",

	# ── Ufficio (hint camera) ─────────────────────────────────────────
	"office.camera_hint": "trascina o WASD per la camera · zoom con rotella, pinch o +/- · click su agenti e reparti · TAB registro · ESC menu",

	# ── Sidebar: gruppi e voci (specchio della desktop app) ───────────
	"side.group_team": "Team",
	"side.group_work": "Lavoro",
	"side.group_settings": "Impostazioni",
	"side.group_help": "Assistenza",
	"side.activation": "Attiva team",
	"side.team": "Team",
	"side.agents": "Agenti",
	"side.chat": "Chat",
	"side.notifs": "Notifiche",
	"side.dashboard": "Dashboard",
	"side.positions": "Posizioni",
	"side.stats": "Statistiche",
	"side.apps": "Candidature",
	"side.map": "Mappa",
	"side.activity": "Attività",
	"side.vps": "Collega VPS",
	"side.profile": "Profilo",
	"side.hours": "Orari",
	"side.provider": "Provider",
	"side.docker": "Docker",
	"side.account": "Account",
	"side.email": "Email",
	"side.appearance": "Aspetto",
	"side.graphics": "Grafica",
	"side.language": "Lingua",
	"side.advanced": "Avanzate",
	"side.feedback": "Segnala un problema",

	# ── Impostazioni → Segnala un problema ───────────────────────
	"feedback.intro": "Raccontaci cosa è andato storto: bastano due frasi. Alla parte tecnica pensiamo noi — il gioco allega una diagnostica già ripulita dai tuoi dati personali, che puoi leggere prima di inviare.",
	"feedback.q_doing": "COSA STAVI FACENDO",
	"feedback.ph_doing": "es. stavo attivando il team dopo aver collegato la VPS",
	"feedback.q_happened": "COSA È SUCCESSO",
	"feedback.ph_happened": "es. la schermata è rimasta ferma su «collegamento» per dieci minuti",
	"feedback.q_expected": "COSA TI ASPETTAVI",
	"feedback.ph_expected": "es. che il team partisse e comparissero gli agenti",
	"feedback.q_contact": "EMAIL PER LA RISPOSTA (facoltativa)",
	"feedback.ph_contact": "senza indirizzo non possiamo farti sapere com'è finita",
	"feedback.contact_hint": "// usata solo per rispondere a questa segnalazione",
	"feedback.attach_diag": "Allega la diagnostica del computer",
	"feedback.attach_container": "Allega i log del runtime",
	"feedback.collecting": "Raccolgo la diagnostica…",
	"feedback.redacted_none": "Nessun dato personale trovato negli allegati.",
	"feedback.redacted_count": "%d dati personali rimossi dagli allegati prima dell'invio.",
	"feedback.send": "INVIA SEGNALAZIONE",
	"feedback.preview_btn": "VEDI COSA STAI INVIANDO",
	"feedback.open_folder": "APRI CARTELLA REPORT",
	"feedback.preview_title": "Questo è esattamente il contenuto che parte insieme al tuo racconto. Niente altro lascia il computer.",
	"feedback.back": "◂ TORNA AL MODULO",
	"feedback.sending": "Invio in corso…",
	"feedback.sent": "Segnalazione inviata. Grazie: la leggiamo davvero.",
	"feedback.failed": "Invio non riuscito.",
	"feedback.offline": "Nessuna connessione all'assistenza.",
	"feedback.too_many": "Troppe segnalazioni ravvicinate: riprova tra qualche minuto.",
	"feedback.ticket": "riferimento %s",
	"feedback.saved_copy": "Una copia è salvata in %s: puoi allegarla a una mail.",

	# ── Impostazioni → Aspetto ───────────────────────────────────
	"appearance.intro": "Scegli l’aspetto dell’interfaccia. Il mondo dell’ufficio mantiene la sua illuminazione; menu, finestre, dialoghi e grafici cambiano insieme.",
	"appearance.current": "TEMA ATTIVO: %s",
	"appearance.light": "Chiaro",
	"appearance.dark": "Scuro",
	"appearance.light_desc": "Finestre bianche, testo scuro e accenti ad alto contrasto",
	"appearance.dark_desc": "Interfaccia terminale scura con accenti luminosi",
	"appearance.note": "// la preferenza viene salvata su questo dispositivo",

	# ── Impostazioni → Grafica ───────────────────────────────────
	"gfx.intro": "Il gioco misura da sé quanti fotogrammi riesce a fare e alleggerisce la grafica quando serve. Se preferisci decidere tu, scegli un profilo: da quel momento comanda la tua scelta e la misura automatica non tocca più niente.",
	"gfx.current": "PROFILO ATTIVO: %s",
	"gfx.state": "mondo disegnato al %d%% · scenografia %s",
	"gfx.scenery_on": "accesa",
	"gfx.scenery_off": "spenta",
	"gfx.auto": "Automatico",
	"gfx.auto_desc": "Il gioco misura gli fps e si adatta mentre giochi",
	"gfx.full": "Massima",
	"gfx.full_desc": "Mondo a risoluzione piena, scenografia completa",
	"gfx.balanced": "Equilibrata",
	"gfx.balanced_desc": "Mondo all’85%: la grana si nota appena, un quarto di lavoro in meno per la GPU",
	"gfx.performance": "Prestazioni",
	"gfx.performance_desc": "Mondo al 60% e scenografia spenta: per le macchine che arrancano",
	"gfx.note": "// la scelta è salvata su questo dispositivo. Le scritte dentro l’ufficio si ingrandiscono da sé quando la risoluzione scende: restano leggibili con ogni profilo.",

	# ── Sezioni non ancora migrate / config sola lettura ──────────────
	"section.migrating": "// sezione non ancora disponibile",
	"section.migrating_body": "I contenuti di «%s» verranno portati qui, un pezzo alla volta.",
	"config.incoming": "// config in arrivo dalla VPS…",
	"config.not_exposed": "// sezione non ancora esposta dal team",

	# ── Sezione Agenti (lista + pagina del singolo agente) ────────────
	"agents.back": "◀ AGENTI",
	"agents.not_active": "non attivo ora",
	"agents.consumption": "CONSUMO (ULTIME %s ORE)",
	"agents.registry_actions": "AZIONI NEL REGISTRO",
	"agents.no_transitions": "nessuna transizione recente a suo nome",
	"agents.active_count": "%d agenti ATTIVI sulla VPS in questo momento",
	"agents.status_default": "operativo",
	"agents.restart": "RIAVVIA",
	"agents.stop": "FERMA",

	# ── Sezione Team ──────────────────────────────────────────────────
	"team.desks": "%d/%d postazioni",
	"team.core": "Core: Il Coordinatore · Il Mentor · L'Assistente",
	"team.stop": "FERMA TEAM",
	"team.start": "AVVIA TEAM",
	"team.setup": "SETUP E STATO",

	# ── Setup iniziale aperto ─────────────────────────────────────
	"setup.cta": "SETUP TEAM · %d/4 COMPLETATO  →",
	"setup.ready_to_start": "SETUP COMPLETO · ATTIVA IL TEAM  →",
	"setup.intro": "L’ufficio è già tuo. Per mettere davvero al lavoro gli agenti completa questi quattro passaggi, nell’ordine che preferisci.",
	"setup.office_open": "Puoi chiudere questa finestra e continuare a esplorare in qualsiasi momento: il setup non blocca l’app.",
	"setup.container": "Container",
	"setup.where": "Dove lavora il team",
	"setup.hours": "Orari di lavoro",
	"setup.hours_todo": "Quando il team può lavorare. Senza orari macina a ogni ora e consuma l'abbonamento.",
	"setup.hours_ok": "Finestre di lavoro impostate.",
	"setup.remote_unknown": "Non leggibile sulla macchina connessa. Il valore di questo computer non conta: è di un’altra macchina.",
	"setup.where_todo": "Sul tuo computer, oppure su una VPS che lavora anche a finestra chiusa.",
	"setup.where_local": "Il team lavora su questo computer.",
	"setup.where_vps": "Il team lavora sulla VPS: questa finestra ne è lo specchio.",
	"setup.use_vps": "PORTA IL TEAM SU UNA VPS",
	"setup.provider": "Provider AI",
	"setup.profile": "Profilo e CV",
	"setup.container_ok": "Il container JHT è acceso e raggiungibile.",
	"setup.container_todo": "Accendi l’ambiente isolato in cui lavorano gli agenti.",
	"setup.provider_todo": "Scegli Claude, Codex o Kimi e accedi col tuo abbonamento.",
	"setup.provider_ok": "%s collegato con l’abbonamento.",
	"setup.provider_login": "%s selezionato: manca il login.",
	"setup.provider_recheck": "RICONTROLLA IL LOGIN",
	"setup.provider_rechecking": "CONTROLLO…",
	"setup.plan_todo": "%s collegato: manca l’abbonamento.",
	"setup.plan_question": "Che abbonamento hai su questo account? Decide quanti agenti accendere.",
	"setup.plan_unavailable": "Elenco abbonamenti non disponibile: accendi il container (passo 01).",
	"setup.profile_ok": "L’Assistente ha tutte le informazioni necessarie.",
	"setup.profile_todo": "Consegna il CV e completa il colloquio con l’Assistente.",
	"setup.progress": "SETUP %d/4",
	"setup.configure": "CONFIGURA  →",
	"setup.review": "CONTROLLA  →",
	"setup.start_team": "▶ ATTIVA IL TEAM",
	"setup.team_running": "● TEAM ATTIVO",
	"setup.team_stopped": "non ancora avviato",
	"setup.team_locked": "⚡ TEAM NON ANCORA ATTIVO · SETUP %d/4 — COMPLETA ORA  →",
	"setup.container_lead": "Il container isola il team e conserva i dati in ~/.jht. L’ufficio resta visitabile anche quando è spento.",
	"setup.docker_ready": "runtime disponibile",
	"setup.docker_missing": "runtime spento o non installato",
	"setup.container_start": "▶ ATTIVA CONTAINER",
	"setup.container_recheck": "↻ RICONTROLLA",
	"setup.runtime_current": "aggiornato",
	"setup.runtime_stale": "aggiornamento pronto: riattiva il container",
	"setup.runtime_update": "⇩ AGGIORNA RUNTIME",
	"setup.back_overview": "← PANORAMICA SETUP",
	"setup.docker_install": "INSTALLA DOCKER",
	"setup.provider_lead": "Scegli un solo provider principale. Il login usa il tuo abbonamento: JHT non chiede né salva API key.",
	"setup.provider_note": "Il login si svolge nella console incorporata: link, codice e scelte restano dentro il gioco; il browser si apre solo per autorizzare l’account.",
	"setup.provider_connected": "✓ login rilevato",
	"setup.provider_disconnected": "○ login da completare",
	"setup.provider_choose": "USA QUESTO PROVIDER",
	"setup.provider_subscription_login": "LOGIN CON ABBONAMENTO  →",
	"setup.provider_relogin": "APRI CONSOLE / CAMBIA ACCOUNT",
	"setup.provider_install": "INSTALLA / AGGIORNA CLI",
	"setup.provider_subscribe": "Non hai un abbonamento? Vedi i piani ↗",
	"setup.login_hint_claude": "Nella console interna scegli il login con abbonamento e apri il link mostrato.",
	"setup.login_hint_codex": "Codex usa il device code: apri il link, inserisci il codice mostrato e autorizza ChatGPT.",
	"setup.login_hint_kimi": "Nella console interna digita /login. Il browser completa normalmente il ritorno in automatico.",
	"setup.profile_lead": "Il profilo si costruisce parlando con l’Assistente, non compilando un modulo rigido.",
	"setup.profile_ready_lead": "✓ Il profilo è pronto. Puoi comunque riaprire l’Assistente per aggiornarlo.",
	"setup.profile_body": "Carica il CV e racconta obiettivi, località, esperienza, competenze e lingue. Il badge mostra cosa manca senza costringerti a un percorso prestabilito.",
	"setup.profile_open": "PARLA CON L’ASSISTENTE E CARICA IL CV  →",
	"setup.profile_requires": "Prima accendi il container e completa il login del provider: servono per far rispondere davvero l’Assistente.",
	"setup.tour_progress": "TOUR CONVERSAZIONALE · %d/3 COMPLETATI",
	"setup.tour_assistant": "ASSISTENTE",
	"setup.tour_coordinator": "COORDINATORE",
	"setup.tour_mentor": "MENTOR",
	"setup.runtime_version": "VERSIONE RUNTIME",
	"setup.container_stop": "FERMA CONTAINER",
	"setup.provider_active": "  ·  ATTIVO",
	"setup.provider_logout": "DISCONNETTI ACCOUNT",

	# ── Titoli KPI (dashboard, statistiche, utilizzo) ─────────────────
	"kpi.positions_today": "POSIZIONI OGGI",
	"kpi.avg_score": "SCORE MEDIO",
	"kpi.positions_total": "POSIZIONI TOTALI",
	"kpi.positions_list": "POSIZIONI DI OGGI",
	"kpi.budget_used": "BUDGET USATO",
	"kpi.streak": "STREAK",
	"kpi.streak_value": "%d giorni · %d freeze",
	"kpi.apps_by_stage": "CANDIDATURE PER STADIO",
	"kpi.provider": "PROVIDER",
	"kpi.actions_today": "AZIONI OGGI",
	"kpi.actions_week": "AZIONI SETTIMANA",
	"kpi.tokens_today": "TOKEN OGGI",
	"kpi.quota_week": "QUOTA SETTIMANALE",

	# ── Pagina Utilizzo ───────────────────────────────────────────────
	"usage.open": "▶ UTILIZZO",
	"usage.title": "UTILIZZO",
	"usage.title_window": "UTILIZZO — ULTIME %s ORE",
	"usage.none": "nessun consumo registrato nella finestra",
	"usage.back": "◀ STATISTICHE",

	# ── Mappa ─────────────────────────────────────────────────────────
	"map.no_coords": "SENZA COORDINATE (%d)",
	"map.none_today": "nessuna posizione geolocalizzata oggi",

	# ── Impostazioni → Account cloud ──────────────────────────────────
	"account.intro": "Sincronizza posizioni, profilo e comandi con jobhunterteam.ai. L'account è opzionale: il team può restare completamente locale.",
	"account.cloud": "ACCOUNT CLOUD",
	"account.linked": "collegato",
	"account.local_mode": "modalità locale / ospite",
	"account.device": "DISPOSITIVO",
	"account.device_paired": "associato",
	"account.server": "SERVER",
	"account.login_again": "RIFAI LOGIN GOOGLE",
	"account.login": "ACCEDI CON GOOGLE  →",
	"account.other_account": "USA UN ALTRO ACCOUNT",
	"account.status": "STATO",
	"account.sync_now": "SINCRONIZZA ORA",
	"account.pull_profile": "RECUPERA PROFILO",
	"account.disable_sync": "FERMA SYNC E CONTINUA SOLO IN LOCALE",
	"account.restore": "RIPRISTINA PIPELINE DAL CLOUD",
	"account.manage_devices": "GESTISCI DISPOSITIVI E REVOCA  ↗",
	"account.privacy_note": "Il login Google autentica il tuo account web. La VPS conserva solo un token di dispositivo revocabile; password e cookie Google non vengono salvati nel gioco.",
	"account.disable_title": "Continuare solo in locale?",
	"account.disable_body": "Il team continuerà a funzionare e i dati locali non verranno cancellati. Il token di questo dispositivo verrà revocato e posizioni/profilo non saranno più sincronizzati col cloud.",
	"account.disable_ok": "FERMA SINCRONIZZAZIONE",

	# ── Impostazioni → Email ──────────────────────────────────────────
	"email.intro": "Casella dedicata agli avvisi di lavoro. Il reparto Ricerca la controlla a inizio giornata e porta in ufficio le opportunità ricevute.",
	"email.status": "STATO",
	"email.configured": "configurata · ",
	"email.none": "nessuna casella configurata",
	"email.address": "INDIRIZZO EMAIL",
	"email.app_password": "APP PASSWORD",
	"email.password_ph": "password specifica per l'app, mai la password principale",
	"email.note": "La password rimane in ~/.jht/credentials con permessi 0600 e non viene sincronizzata sul cloud.",
	"email.save": "SALVA E VERIFICA IMAP",
	"email.remove": "RIMUOVI",
	"email.help": "COME CREARE UNA APP PASSWORD  ↗",

	# ── Impostazioni → Telegram ───────────────────────────────────────
	"tg.intro": "Collega i tre bot privati usati dal team. I token restano nel runtime locale o sulla tua VPS e non vengono mai inviati al cloud JHT.",
	"tg.botfather": "APRI BOTFATHER  ↗",
	"tg.guide": "Crea un bot, incolla il token, apri la chat col bot e premi Start; poi usa SALVA E RILEVA CHAT.",
	"tg.role_assistente": "onboarding del profilo e documenti",
	"tg.role_capitano": "direzione del team e posizioni pronte",
	"tg.role_mentor": "coaching e strategia professionale",
	"tg.configured": "● CONFIGURATO",
	"tg.to_link": "○ DA COLLEGARE",
	"tg.token_ph": "token BotFather",
	"tg.chat_id_ph": "chat_id (opzionale: rilevamento automatico)",
	"tg.save": "SALVA E RILEVA CHAT",
	"tg.remove": "RIMUOVI",

	# ── Impostazioni → Avanzate ───────────────────────────────────────
	"advanced.intro": "Diagnostica e manutenzione del runtime. Ogni comando resta visibile dentro il gioco.",
	"advanced.doctor": "ESEGUI DIAGNOSTICA",
	"advanced.review_setup": "RIVEDI SETUP",
	"advanced.reinstall": "REINSTALLA / AGGIORNA RUNTIME",
	"advanced.open_data": "APRI DATI JHT",
	"advanced.open_log": "APRI LOG DEL GIOCO",
	"advanced.version": "Versione gioco %s · dati applicazione %s",

	# ── Sistema VPS (telemetria host e container) ─────────────────────
	"sys.title": "SISTEMA VPS · LIVE",
	"sys.subtitle": "Host e container jht · aggiornamento ogni 8 secondi",
	"sys.disk": "DISCO /",
	"sys.cpu_host_history": "CPU HOST · STORICO",
	"sys.ram_host_history": "RAM HOST · STORICO",
	"sys.container_status": "STATO CONTAINER",
	"sys.container_mem": "MEMORIA JHT",
	"sys.restarts": "RIAVVII",
	"sys.load1": "LOAD 1 MIN",
	"sys.uptime": "UPTIME VPS",
	"sys.rx": "RETE RICEVUTA",
	"sys.tx": "RETE INVIATA",

	# ── Risorse per agente (live) ─────────────────────────────────────
	"metrics.title": "RISORSE PER AGENTE · LIVE",
	"metrics.subtitle": "RAM = processo tmux e discendenti · token = bucket reali del token-meter",
	"metrics.freshness_wait": "TOKEN · freschezza in attesa…",
	"metrics.col_agent": "AGENTE",
	"metrics.col_ram_history": "STORICO RAM",
	"metrics.tokens_window": "TOKEN (%s)",
	"metrics.tokens_bucket": "TOKEN / %s",
	"metrics.no_source": "TOKEN · sorgente non disponibile",
	"metrics.stale": "TOKEN · %s · STALE DA %s",
	"metrics.updated": "TOKEN · aggiornati %s · %s fa",

	# ── Showroom (dati dimostrativi) ──────────────────────────────────
	"demo.map": "◆ SHOWROOM · pin e offerte sono esempi fittizi",
	"demo.positions": "◆ SHOWROOM · 50 POSIZIONI FITTIZIE · nessun dato personale o link attivo",
	# ── Modalità operative del Coordinatore ───────────────────────────
	"burn.section": "MODALITÀ OPERATIVE",
	"burn.section_desc": "deroghe che concedi tu, a termine",
	"burn.title": "Spinta massima",
	"burn.duration": "Durata",
	"burn.desc": "Di norma il team rallenta da solo per far durare il budget: si ferma quando ha speso la quota del giorno, tace fuori dall'orario di lavoro e riduce il ritmo man mano che la finestra si riempie. Questo interruttore sospende quei freni per una finestra sola, quando ti serve che il team spinga adesso.",
	"burn.desc_measured": "Non promette di consumare tutto: la notte in cui è nata questa funzione, con tutte le deroghe attive il consumo si è fermato fra il 6% e il 19% della finestra. Cercare offerte e analizzarle aspetta soprattutto la rete, non il modello, e togliere le pause non lo cambia. Serve perché il team obbedisca quando glielo chiedi.",
	"burn.state_off": "non attiva — il team si autoregola per far durare il budget",
	"burn.state_active": "attiva — scade fra %s",
	"burn.state_soon": "attiva — scade fra %s, poi il ritmo torna da solo",
	"burn.state_unknown": "stato non leggibile — il team non ha risposto",
	"burn.state_unsupported": "non disponibile — il container del team è più vecchio del gioco",
	"burn.left_h": "%s h",
	"burn.left_hm": "%s h %s min",
	"burn.left_m": "%s min",
	"burn.left_soon": "meno di un minuto",
	"burn.sending": "invio al team…",
	"burn.failed": "non riuscito — %s",
	"burn.confirm_title": "Attivare la spinta massima?",
	"burn.confirm_body": "Il team smette di rallentare da solo per far durare il budget: niente stop giornaliero, niente pausa fuori orario, niente ritmo ridotto quando la finestra si riempie.\n\n• Si spegne da sola dopo %s ore — il massimo consentito è %s: non esiste la forma permanente e non resta accesa per dimenticanza.\n\n• Quattro freni non cedono comunque: %s. Non sono economie — oltre il limite settimanale il provider smette di rispondere, e oltre il tetto di memoria la macchina rallenta tutto. Forzarli darebbe meno lavoro, non di più.\n\n• La sorveglianza passa al Coordinatore: senza i freni automatici è lui che deve fermare un agente che consuma senza produrre. Puoi revocare quando vuoi dallo stesso interruttore.",
	"burn.confirm_ok": "Attiva per %s ore",
}
