class_name UIStrings
## Tutte le stringhe UI del gioco, centralizzate. L'italiano (S, sotto)
## resta il catalogo strutturale; le altre 6 lingue del web (en, hu, es,
## de, fr, pt) vivono in scripts/i18n/ui_<lang>.gd con le STESSE chiavi.
## A runtime una traduzione mancante ricade sull'inglese: è la lingua di
## default e nessuna ripresa deve mostrare italiano per un buco nel catalogo.

const LANGS := {
	"it": "Italiano", "en": "English", "hu": "Magyar", "es": "Español",
	"de": "Deutsch", "fr": "Français", "pt": "Português",
}
const LANG_CFG := "user://lang.cfg"
## Lingua mostrata prima che esista una preferenza esplicita dell'utente.
## Non leggiamo il locale del sistema: il video/tutorial e la UI devono partire
## dalla stessa lingua prevedibile su ogni installazione nuova.
const DEFAULT_LANG := "en"

static var lang := DEFAULT_LANG

## Solo l'oracolo di persistenza sostituisce il file utente: le sue due
## esecuzioni sono processi distinti e condividono un ConfigFile vuoto dedicato.
static func language_config_path() -> String:
	if TutorialHarness.enabled():
		return TutorialHarness.LANGUAGE_CFG
	var persistence_test := OS.get_environment("JHT_LANGUAGE_PERSIST_TEST")
	if persistence_test in ["cleanup", "write", "verify"]:
		return "user://language_persistence_selftest.cfg"
	# ConfigFile non crea gerarchie: questo percorso deliberatamente senza padre
	# verifica che un save KO non faccia avanzare la UI come se avesse salvato.
	if persistence_test == "save_failure":
		return "user://language_persistence_missing/lang.cfg"
	return LANG_CFG

static func _static_init() -> void:
	# Il harness registrabile deve partire come prima installazione ma non può
	# leggere né sovrascrivere la scelta lingua della macchina reale. Ignora
	# anche JHT_LANG: il suo scopo è proprio mostrare il picker nativo.
	if TutorialHarness.enabled():
		TutorialHarness.reset_file_if_requested(TutorialHarness.LANGUAGE_CFG)
		var tutorial_saved := saved_language()
		lang = tutorial_saved if tutorial_saved != "" else DEFAULT_LANG
		return
	# Il selftest della title deve simulare una macchina senza file user://,
	# senza leggere o sovrascrivere la preferenza reale dello sviluppatore.
	if OS.get_environment("JHT_LANGUAGE_PICKER_TEST") == "1":
		lang = DEFAULT_LANG
		return
	# TEST-AUTO: JHT_LANG forza la lingua per gli shot
	var forced := OS.get_environment("JHT_LANG")
	if LANGS.has(forced):
		lang = forced
		return
	var saved := saved_language()
	if saved != "":
		lang = saved

## Il primo avvio ha una schermata dedicata; un override valido serve soltanto
## ai test e agli screenshot, che devono poter atterrare direttamente nella
## scena richiesta senza scrivere preferenze dell'utente.
static func language_choice_required(has_saved_preference: bool,
		forced_language := "") -> bool:
	return not has_saved_preference and not LANGS.has(forced_language)

static func needs_initial_language_choice() -> bool:
	if TutorialHarness.enabled():
		return saved_language() == ""
	if OS.get_environment("JHT_LANGUAGE_PICKER_TEST") == "1":
		return true
	return language_choice_required(saved_language() != "", OS.get_environment("JHT_LANG"))

## La lettura è separata dal bootstrap per poter verificare il round-trip
## scrittura → riapertura senza mai toccare le preferenze di chi sviluppa.
static func saved_language(config_path := "") -> String:
	var path := config_path if config_path != "" else language_config_path()
	var cfg := ConfigFile.new()
	if cfg.load(path) != OK:
		return ""
	var saved := str(cfg.get_value("ui", "lang", ""))
	return saved if LANGS.has(saved) else ""

static func _save_language(l: String, config_path := "") -> bool:
	var path := config_path if config_path != "" else language_config_path()
	var cfg := ConfigFile.new()
	cfg.set_value("ui", "lang", l)
	return cfg.save(path) == OK

static func set_lang(l: String, persist := true, config_path := "") -> bool:
	if not LANGS.has(l):
		return false
	if not persist or OS.get_environment("JHT_LANGUAGE_PICKER_TEST") == "1" \
			or OS.get_environment("JHT_LANGUAGE_SETTINGS_TEST") == "1":
		lang = l
		return true
	if not _save_language(l, config_path):
		return false
	lang = l
	return true

static func t(key: String) -> String:
	return _translated(key, lang, _translations() if lang != "it" else {})


## Lookup puro tenuto separato per provare il fallback con cataloghi sintetici:
## le Dictionary ottenute dalle costanti degli script sono read-only in Godot.
static func _translated(key: String, requested_lang: String,
		translations: Dictionary) -> String:
	if requested_lang != "it":
		var d: Dictionary = translations.get(requested_lang, {})
		if d.has(key):
			return d[key]
		var english: Dictionary = translations.get(DEFAULT_LANG, {})
		if english.has(key):
			return english[key]
	return S.get(key, key)

## I dizionari tradotti, caricati pigramente (i preload in const
## creerebbero un ciclo di parse se un file i18n mancasse in dev).
static var _tr_cache := {}

static func _translations() -> Dictionary:
	if _tr_cache.is_empty():
		for l in LANGS:
			if l == "it":
				continue
			var path := "res://scripts/i18n/ui_%s.gd" % l
			if ResourceLoader.exists(path):
				var script: GDScript = load(path)
				_tr_cache[l] = script.get_script_constant_map().get("S", {})
	return _tr_cache

const S := {
	"common.loading": "CARICAMENTO…",
	# ── Title screen ──────────────────────────────────────────────
	"language_picker.eyebrow": "PRIMO AVVIO",
	"language_picker.title": "Scegli la lingua",
	"language_picker.subtitle": "Potrai cambiarla in qualunque momento da Impostazioni.",
	"language_picker.continue": "CONTINUA IN %s",
	"title.wordmark": "JOB HUNTER TEAM",
	"title.name_title": "Presentiamoci",
	"title.name_sub": "Come ti chiami? Il team ti chiamerà per nome.",
	"title.name_first": "Nome",
	"title.name_last": "Cognome (facoltativo)",
	"title.name_enter": "ENTRA IN UFFICIO",
	"title.name_skip": "Preferisco non dirlo, entriamo",
	"title.press_enter": "▶ PREMI INVIO",
	"title.footer": "prototipo — dati mock, nessun backend",
	"title.hint_pause": "ESC menu",

	# ── Menu pausa ────────────────────────────────────────────────
	"pause.title": "PAUSA",
	"pause.resume": "RIPRENDI",
	"pause.window": "FINESTRA / SCHERMO INTERO",
	"pause.quit": "ESCI DAL GIOCO",
	"pause.shutdown": "FERMO IL TEAM E CHIUDO…",
	"pause.detaching": "ESCO · IL TEAM CONTINUA A LAVORARE",
	"shutdown.title": "STAI PER CHIUDERE LA FINESTRA",
	"shutdown.lead": "Gli agenti lavorano nel container, non in questa finestra. Adesso ne stanno lavorando %d: scegli cosa ne faccio.",
	"shutdown.graceful": "FERMA IL TEAM E CHIUDI",
	"shutdown.graceful_hint": "Ogni agente annota dove è arrivato, poi il team si ferma e il container si spegne. Alla riapertura si riprende da lì.",
	"shutdown.forced": "CHIUDI TUTTO SUBITO",
	"shutdown.forced_hint": "Non aspetta nessuno: chi sta lavorando non fa in tempo a salvare il punto in cui è arrivato.",
	"shutdown.forced_now": "NON ASPETTARE · CHIUDI SUBITO",
	"shutdown.cancel": "ANNULLA",
	"shutdown.detach": "ESCI · IL TEAM CONTINUA A LAVORARE",
	"shutdown.detach_hint": "Si chiude solo la finestra: gli agenti restano al lavoro nel container e il budget continua a scorrere.",
	"shutdown.detach_body": "Chiudo solo la finestra: il container resta acceso e gli agenti continuano a cercare, valutare e scrivere anche stanotte. Continuano anche a consumare budget, esattamente come se fossi qui a guardarli.",
	"shutdown.detach_back": "Riapri il gioco quando vuoi e ritrovi l'ufficio al punto in cui è arrivato. Per fermare il team basta rientrare e, chiudendo, scegliere di fermarlo.",
	"shutdown.detach_confirm": "ESCI COSÌ, LI LASCIO LAVORARE",
	"shutdown.ordered": "Ho chiesto al Capitano di chiudere la giornata: ogni agente annota dove era arrivato, poi si ferma.",
	"shutdown.waiting": "Ancora %d agenti al lavoro · %d s. Puoi aspettare o chiudere subito.",
	"shutdown.done": "Team fermo. Chiudo.",
	"headless.back": "○ IL TEAM HA LAVORATO SENZA DI TE PER %s · ORA SONO %d IN UFFICIO",
	"headless.dur_min": "%d min",
	"headless.dur_hour": "%dh %dm",

	# ── HUD ───────────────────────────────────────────────────────
	"hud.team": "TEAM",
	"hud.positions_today": "POSIZIONI OGGI",
	"hud.avg_score": "SCORE MEDIO",
	"hud.budget": "BUDGET",
	"hud.registry_hint": "TAB registro",
	"hud.team_default": "Team JHT",

	# ── Registro candidature ──────────────────────────────────────────
	"registry.title": "REGISTRO CANDIDATURE",
	"registry.empty": "osservare il mercato e' un uso completo di JHT",
	"registry.stage_0": "inviata",
	"registry.stage_1": "screening",
	"registry.stage_2": "colloquio",
	"registry.stage_3": "offerta",
	"registry.close": "[TAB] chiudi",

	# ── Archivio CV (click sullo scaffale output) ─────────────────
	"cv.title": "ARCHIVIO CV SCRITTI",
	"cv.subtitle": "Documenti del reparto Candidature e del Controllo qualità",
	"cv.total": "CV SCRITTI",
	"cv.pass": "PASS",
	"cv.review": "DA RIVEDERE",
	"cv.avg_score": "SCORE MEDIO",
	"cv.list": "ELENCO CV",
	"cv.detail": "PANORAMICA CV",
	"cv.empty": "Nessun CV scritto è ancora presente nello snapshot.",
	"cv.select": "Seleziona un CV dall’elenco per vedere la panoramica.",
	"cv.written_by": "SCRITTO DA",
	"cv.reviewed_by": "REVISIONATO DA",
	"cv.artifacts": "DOCUMENTI PRODOTTI",
	"cv.match": "MATCH POSIZIONE",
	"cv.open_position": "APRI SCHEDA COMPLETA DELLA POSIZIONE",
	"cv.close": "ESC o click fuori per chiudere",
	"cv.preview": "ANTEPRIMA",
	"cv.preview_title": "ANTEPRIMA DOCUMENTO",
	"cv.doc_loading": "Recupero il documento dal container…",
	"cv.doc_error": "Documento non disponibile: ",
	"cv.doc_pdf_only": "Per questo documento esiste solo il PDF: aprilo qui sotto.",
	"cv.open_pdf": "APRI PDF",
	"cv.opening_pdf": "SCARICO…",
	"cv.doc_close": "ESC o click fuori per tornare all'archivio",
	"cv.tab_text": "TESTO",
	"cv.tab_pdf": "ANTEPRIMA PDF",
	"cv.pdf_rendering": "Preparo l'anteprima del PDF…",
	"cv.pdf_no_tool": "Nessun renderizzatore PDF locale: usa APRI PDF per il viewer di sistema.",
	"cv.pdf_first_page_only": "Anteprima limitata alla prima pagina (renderizzatore ridotto).",
	"cv.reveal": "MOSTRA NELLA CARTELLA",
	"cv.reveal_done": "Copia salvata in ",
	"cv.open_failed": "Apertura fallita: ",

	# ── Code delle pile di reparto ───────────────────────────────
	"queue.title": "CODA %s",
	"queue.subtitle": "Posizioni nello stato operativo rappresentato da questa pila",
	"queue.count": "%d POSIZIONI IN CODA",
	"queue.list": "POSIZIONI DA ELABORARE",
	"queue.detail": "PANORAMICA POSIZIONE",
	"queue.empty": "La coda è vuota: nessuna posizione attende in questa fase.",
	"queue.select": "Seleziona una posizione per vedere i dettagli.",
	"queue.open_position": "APRI SCHEDA COMPLETA",
	"queue.close": "ESC o click fuori per chiudere",
	"queue.phase.to_analyze": "DA ANALIZZARE",
	"queue.phase.analyzed": "ANALIZZATE · ATTESA SCORE",
	"queue.phase.with_score": "CON SCORE · ATTESA SCRITTORI",
	"queue.phase.to_write": "CV DA SCRIVERE / REVISIONARE",
	"queue.phase.written": "CV SCRITTI · ATTESA ESITO",
	"hud.dialogue_next": "[INVIO] continua",
	"hud.dialogue_skip": "[ESC] chiudi",

	"tour.title": "TOUR DELL'UFFICIO",
	"tour.step_assistant": "Saluta l'Assistente",
	"tour.step_depts": "Il giro dei reparti",
	"tour.step_doctor": "Una visita al Dottore",
	"tour.step_mentor": "La chiacchierata col Mentor",
	"tour.step_coordinator": "Il Coordinatore e il setup",
	"tour.step_launch": "Prepara il lancio",
	"tour.chk_container": "Container attivo",
	"tour.chk_provider": "Provider collegato",
	"tour.chk_profile": "Profilo completo",
	"tour.hint_talk": "Clicca l'Assistente col diamante per iniziare il giro.",
	"tour.hint_follow": "L'Assistente ti fa strada: seguila, pensa a tutto lei.",
	"tour.hint_free": "Giro libero: clicca chi ha il diamante, in qualsiasi ordine.",
	"tour.hint_launch": "Completa i tre requisiti: il pulsante giallo in alto apre la checklist.",
	"tour.skip": "SALTA IL TOUR",
	"tour.done": "TOUR COMPLETATO ✓",
	"tour.invite": "%s%s! Vieni, ti presento il tuo nuovo team.",
	"tour.guide.scout.greet": "Questo è il reparto Ricerca. Ti presento uno dei nostri Ricercatori.",
	"tour.guide.scout.reply": "Piacere. Ti racconto come cerchiamo le opportunità per te.",
	"tour.guide.analista.greet": "Questo è il reparto Analisi. Una collega ti spiega che cosa succede qui.",
	"tour.guide.analista.reply": "Benvenuto. Qui trasformiamo gli annunci confusi in informazioni chiare.",
	"tour.guide.scorer.greet": "Siamo nel reparto Compatibilità. Ti presento uno dei Consulenti.",
	"tour.guide.scorer.reply": "Piacere. Qui capiamo quali occasioni sono davvero adatte a te.",
	"tour.guide.scrittore.greet": "Questo è il reparto Candidature. Lascio la parola a un Redattore.",
	"tour.guide.scrittore.reply": "Benvenuto. Ti mostro come prepariamo ogni candidatura su misura.",
	"tour.guide.critico.greet": "Qui c'è il Controllo qualità. Un Revisore ti racconta il suo lavoro.",
	"tour.guide.critico.reply": "Piacere. Il nostro compito è non lasciare passare candidature deboli.",
	"tour.guide.dottore.greet": "Prima degli ultimi incontri ti presento il Dottore dell'ufficio.",
	"tour.guide.dottore.reply": "Benvenuto. Io mi assicuro che la squadra continui a lavorare bene.",
	"tour.guide.mentor.greet": "E qui ti lascio in ottime mani. Io sono alla mia scrivania.",
	"tour.guide.mentor.reply": "Accomodati. Ti aspettavo.",
	"tour.guide.coordinatore.greet": "Ultima tappa: la sala operativa.",
	"tour.guide.coordinatore.reply": "Vi stavo aspettando.",

	# ── Pannello reparto ──────────────────────────────────────────
	"dept.desks": "POSTAZIONI",
	"dept.desk_free": "postazione libera",
	"dept.close": "click fuori per chiudere",
	"dept.inbox": "Inbox: %d fogli in attesa",

	# ── Nomi di scena dei ruoli ───────────────────────────────────
	# La targhetta di ogni agente: quello che l'utente legge nella colonna
	# delle chat, sulla targa dei dialoghi e nella scheda. Vivono qui e non
	# più dentro CharacterDefs/TourGuide perché erano l'unica famiglia di
	# etichette scritta a mano in italiano: con l'interfaccia in inglese la
	# colonna delle chat restava italiana in mezzo a tutto il resto tradotto.
	# La chiave si compone a runtime ("role." + slug), quindi il controllo
	# sui sorgenti di i18n_parity_selftest non la vede: la copertura gliela
	# dà _check_role_names, che legge direttamente CharacterDefs.
	"role.coordinatore": "Il Coordinatore",
	"role.scout": "Il Ricercatore",
	"role.analista": "L'Analista",
	"role.scorer": "Il Consulente",
	"role.scrittore": "Il Redattore",
	"role.critico": "Il Revisore",
	"role.mentor": "Il Mentor",
	"role.assistente": "L'Assistente",
	"role.mantenitore": "Il Mantenitore",
	"role.dottore": "Il Dottore",
	"role.sentinella": "Il Tesoriere",
	# Forma breve dei soli ruoli di reparto: si numera ("Ricercatore 02")
	# per i colleghi oltre il lead, quindi niente articolo.
	"role_short.scout": "Ricercatore",
	"role_short.analista": "Analista",
	"role_short.scorer": "Consulente",
	"role_short.scrittore": "Redattore",
	"role_short.critico": "Revisore",

	# ── Scheda agente ─────────────────────────────────────────────
	"agent.activity": "ULTIME ATTIVITÀ",
	"agent.activity_none": "nessuna attività registrata",
	"agent.talk": "▶ PARLA",
	"agent.chat": "▶ CHAT COL TEAM",
	"agent.pile": "Fogli sulla scrivania: %d",
	"agent.thinking": "◉ MOSTRA ATTIVITÀ INTERNA",
	"agent.thinking_tooltip": "Osserva lo stream tmux dell'agente in sola lettura",
	"agent.thinking_unavailable": "Disponibile quando l'agente reale è attivo",
	"agent.thinking_title": "ATTIVITÀ INTERNA — %s",
	"agent.thinking_subtitle": "Stream live della sessione tmux dell'agente",
	"agent.thinking_loading": "● COLLEGAMENTO…",
	"agent.thinking_waiting": "Attendo il primo snapshot del terminale…",
	"agent.thinking_readonly": "SOLA LETTURA · NESSUN TASTO VIENE INVIATO",
	"agent.thinking_bottom": "↓ TORNA IN FONDO",
	"agent.thinking_error": "STREAM NON DISPONIBILE",
	"agent.thinking_live": "STREAM LIVE",
	"agent.thinking_empty": "La sessione è attiva ma non ha ancora prodotto output.",
	"coord.open": "◆ CONSOLE COORDINATORE",
	"coord.open_tip": "Modalità operative, automazioni e ordini permanenti del team",
	"coord.title": "CONSOLE DEL COORDINATORE",
	"coord.subtitle": "Policy applicate a codice, code operative e ordini al Capitano",
	"coord.nav_control": "◆ CONTROLLO E ORDINI",
	"coord.nav_monitor": "▥ MONITORAGGIO",
	"coord.nav_thinking": "◉ ATTIVITÀ INTERNA",
	"coord.nav_chat": "▶ CHAT COL COORDINATORE",
	"coord.view_control": "CONTROLLO OPERATIVO",
	"coord.view_monitor": "MONITORAGGIO COORDINATORE",
	"coord.coordinator": "Coordinatore",
	"coord.monitor_title": "Monitoraggio del Coordinatore",
	"coord.monitor_desc": "Stato live e storico completo delle risorse del Capitano",
	"coord.monitor_live": "Risorse live",
	"coord.monitor_live_desc": "Ultimo campione dal processo tmux e dal token-meter della VPS.",
	"coord.monitor_history": "Storico e consumo",
	"coord.monitor_history_desc": "Token, quote 5h e weekly, throttle, azioni DB, CPU e RAM sullo stesso asse temporale.",
	"coord.m_status": "Stato",
	"coord.m_session": "Sessione",
	"coord.m_ram": "RAM live",
	"coord.m_tokens": "Token finestra",
	"coord.m_ram_live": "RAM processo · ultimi campioni",
	"coord.m_token_buckets": "Token · bucket recenti",
	"coord.monitor_no_detail": "Nessuna attività dettagliata disponibile.",
	"coord.loading": "CARICAMENTO…",
	"coord.refresh": "Aggiorna dati e code",
	"coord.queues": "Panoramica code",
	"coord.queues_desc": "Carico reale del team in questo momento",
	"coord.mode": "Modalità di lavoro",
	"coord.mode_desc": "Un click cambia l’obiettivo di tutto il team. La modalità resta finché non ne scegli un’altra.",
	"coord.mode_search": "Ricerca",
	"coord.mode_search_what": "Il team accumula: trova nuove posizioni, le analizza e le scora.",
	"coord.mode_search_when": "La scelta di partenza, quando vuoi ampliare il portafoglio.",
	"coord.mode_harvest": "Raccolto",
	"coord.mode_harvest_what": "Stop alle nuove ricerche: si scrivono i CV per le migliori posizioni già trovate.",
	"coord.mode_harvest_when": "Quando le posizioni buone senza CV si accumulano.",
	"coord.mode_harvest_data": "%d posizioni con score alto sono ancora senza CV",
	"coord.mode_care": "Cura",
	"coord.mode_care_what": "Niente accumulo: il team verifica e tiene fresche le posizioni già trovate.",
	"coord.mode_care_when": "Quando il portafoglio basta e vuoi mantenerlo affidabile.",
	"coord.mode_calibration": "Calibrazione",
	"coord.mode_calibration_what": "Il team legge le tue esclusioni e i tuoi ticket e riorienta le priorità di ricerca.",
	"coord.mode_calibration_when": "Quando hai dato feedback che il team non ha ancora recepito.",
	"coord.mode_calibration_data": "%d tue segnalazioni non ancora recepite",
	"coord.mode_saving": "Risparmio",
	"coord.mode_saving_what": "Solo il minimo vitale: nessun arricchimento autonomo, nessuna spesa non richiesta.",
	"coord.mode_saving_when": "Quando vuoi conservare budget: le tue richieste esplicite vengono comunque eseguite.",
	"coord.stop_search": "Ferma la ricerca di nuove posizioni",
	"coord.expired": "Scarta le posizioni scadute a rotazione",
	"coord.cv_score": "Score minimo per scrivere un CV",
	"coord.precheck": "Verifica che l'offerta sia viva prima del CV",
	"coord.automation": "Automazioni e budget",
	"coord.automation_desc": "Decidi quali arricchimenti possono consumare budget in autonomia.",
	"coord.economy": "Risparmio token: spegni enrichment autonomo",
	"coord.economy_tip": "Le richieste esplicite dell'utente restano sempre eseguibili",
	"coord.geo": "Geolocalizza automaticamente gli uffici",
	"coord.geo_desc": "Completa la mappa per offerte con sede fisica e score sufficiente.",
	"coord.min_score": "Score minimo geolocalizzazione",
	"coord.zero_all": "0 = nessuna soglia",
	"coord.non_remote": "Solo posizioni non remote",
	"coord.logo": "Scarica automaticamente i loghi aziendali",
	"coord.logo_desc": "Arricchisce le schede delle aziende che superano la soglia.",
	"coord.min_score_logo": "Score minimo logo",
	"coord.recheck": "Ricontrolla periodicamente le posizioni",
	"coord.recheck_desc": "Verifica che le offerte migliori siano ancora aperte dopo N giorni.",
	"coord.score": "Score minimo",
	"coord.days": "Più vecchie di giorni",
	"coord.save": "SALVA POLICY E AVVISA IL COORDINATORE",
	"coord.orders": "Ordini rapidi",
	"coord.orders_desc": "Azioni una tantum: partono subito ma non cambiano la policy permanente.",
	"coord.preset_scout": "SOLO SCOUTING PER IL PROSSIMO CICLO",
	"coord.preset_balance": "RIBILANCIA TUTTA LA PIPELINE",
	"coord.preset_reanalyze": "RIANALIZZA LE POSIZIONI OBSOLETE",
	"coord.preset_maintenance": "ESEGUI UN GIRO DI CURA",
	"coord.preset_scout_desc": "Concentra temporaneamente capacità e budget sulla ricerca di nuove offerte.",
	"coord.preset_balance_desc": "Analizza i colli di bottiglia e sposta gli agenti sulla coda più urgente.",
	"coord.preset_reanalyze_desc": "Usa le soglie configurate sopra per aggiornare le offerte obsolete.",
	"coord.preset_maintenance_desc": "Smaltisce scadute, geocoding, loghi e recheck attualmente abilitati.",
	"coord.execute": "ESEGUI ORA",
	"coord.custom": "Ordine personalizzato",
	"coord.prompt_scout": "Per il prossimo ciclo concentra il budget sugli Scout: cerca nuove posizioni coerenti col profilo, senza avviare lavoro accessorio. Verifica prima il pacing e scala gradualmente.",
	"coord.prompt_balance": "Controlla tutte le code e ribilancia il team sulla fase che sta bloccando la pipeline. Rispetta il budget, non duplicare agenti occupati e spiegami in chat cosa hai deciso.",
	"coord.prompt_reanalyze": "Fai rianalizzare agli Analisti tutte le posizioni vive non controllate da più di %d giorni con score almeno %d. Distribuisci la coda senza duplicati e cadenzala sul budget.",
	"coord.prompt_maintenance": "Esegui ora un giro delle code di cura abilitate: scadute, recheck, geocoding e loghi. Assegna code diverse agli Analisti e, quando sono vuote, applica C-25: se avanza budget non restare fermo.",
	"coord.command_placeholder": "Scrivi un ordine specifico al Coordinatore…",
	"coord.permanent": "Rendi questa istruzione una direttiva permanente",
	"coord.send": "INVIA ORDINE",
	"coord.board": "Bacheca permanente del team",
	"coord.board_tip": "Queste direttive sopravvivono ai riavvii e prevalgono sui comportamenti predefiniti.",
	"coord.close": "ESC o click fuori per chiudere",
	"coord.saving": "SALVATAGGIO…",
	"coord.empty_order": "Scrivi prima un ordine",
	"coord.sending": "INVIO AL COORDINATORE…",
	"coord.ready": "POLICY E CODE AGGIORNATE",
	"coord.q_new": "NUOVE",
	"coord.q_analysis": "ANALISI",
	"coord.q_scored": "SCORATE",
	"coord.q_geo": "GEO",
	"coord.q_logo": "LOGHI",
	"coord.q_recheck": "RECHECK",
	"coord.q_expired": "SCADUTE",
	"coord.board_empty": "Nessuna direttiva permanente attiva.",
	"coord.archive": "ARCHIVIA",
	"coord.saved": "MODIFICA APPLICATA",
	"coord.error": "ERRORE: %s",
	"coord.sent": "ORDINE CONSEGNATO",

	# ── Pannello chat con l'agente ────────────────────────────────
	"chat.title": "CHAT — %s",
	"chat.placeholder": "scrivi un messaggio…",
	"chat.send": "INVIA",
	"chat.you": "TU",
	"chat.empty": "nessun messaggio ancora: scrivi tu per primo",
	"chat.waiting": "in attesa della risposta",
	"chat.besteffort": "◐ questo agente legge i messaggi ma potrebbe non rispondere in chat",
	"chat.menu": "CHAT AGENTI",
	"chat.replies": "risponde in chat",
	"chat.maybe": "legge, risposta non garantita",
	"guided.choose": "SCEGLI UNA RISPOSTA",
	"guided.choice_placeholder": "scegli una delle risposte qui sopra…",
	"guided.free_placeholder": "scrivi liberamente oppure usa una risposta suggerita…",
	"guided.offline_note": "◆ conversazione guidata offline — nessun token e nessun LLM necessario",
	"guided.hybrid_note": "◆ guida attiva — puoi anche scrivere liberamente all’agente collegato",
	"guided.agent_unavailable": "◆ provider collegato — avvia il team per usare la chat reale",
	"guided.ai_suggestions": "RISPOSTE SUGGERITE DALL’AGENTE",
	"chat.close": "chiudi [Esc]",
	"chat.history_start": "inizio della conversazione",
	"chat.jump_latest": "ULTIMO MESSAGGIO",

	# ── Wizard onboarding (foto badge con l'Assistente) ───────────
	"wizard.title": "CONFIGURA IL TUO PROFILO",
	"wizard.subtitle": "Parla con l'Assistente: il badge a sinistra si compila da solo mentre vi confrontate. Carica il CV per fare prima.",
	"wizard.profile": "BADGE PROFILO",
	"wizard.progress": "%d/%d campi",
	"wizard.assistant": "ASSISTENTE",
	"wizard.chat_empty": "l'Assistente sta arrivando: intanto puoi scrivere tu o caricare il CV",
	"wizard.upload": "CARICA CV",
	"wizard.uploading": "carico %s…",
	"wizard.upload_fail": "upload fallito: %s",
	"wizard.attach_msg": "Ti ho caricato un documento: puoi estrarre da qui il mio profilo?",
	"wizard.connecting": "connessione al team…",
	"wizard.booting_assistant": "avvio dell'assistente in corso (può volerci un minuto)…",
	"wizard.sim_badge": "SIMULAZIONE — nessuna VPS collegata",
	"wizard.waiting_profile": "completa il badge con l'Assistente per entrare in ufficio",
	"wizard.ready_note": "badge completo: il team ti aspetta",
	"wizard.enter_office": "ENTRA IN UFFICIO →",
	"wizard.back_office": "← TORNA IN UFFICIO",
	"wizard.profile_done_back": "✓ PROFILO COMPLETO · TORNA IN UFFICIO",
	"wizard.setup_required": "attiva container e provider dall’ufficio per parlare con l’Assistente",
	"wizard.f.name": "Nome",
	"wizard.f.email": "Email",
	"wizard.f.target_role": "Ruolo target",
	"wizard.f.location": "Località",
	"wizard.f.experience_years": "Anni di esperienza",
	"wizard.f.seniority_target": "Seniority",
	"wizard.f.skills": "Competenze (≥2)",
	"wizard.f.languages": "Lingue (≥1)",

	# ── Impostazioni → Collega VPS ────────────────────────────────
	"vps.intro": "Collega la VPS del tuo team: IP e chiave SSH, al resto pensa il gioco.",
	"vps.ip": "IP DELLA VPS",
	"vps.user": "UTENTE SSH",
	"vps.user_note": "Utente con cui il provider apre la VPS: root su Hetzner, ubuntu su OVH e AWS, il nome dell'account su Google Cloud e Azure. Vuoto vale root.",
	"vps.key": "CHIAVE SSH (privata)",
	"vps.key_browse": "SFOGLIA…",
	"vps.connect": "▶ COLLEGA",
	"vps.disconnect": "■ SCOLLEGA",
	"vps.state_disconnected": "non collegato",
	"vps.state_connecting": "collegamento in corso…",
	"vps.state_connected": "COLLEGATO",
	"vps.state_error": "ERRORE",
	"vps.missing_fields": "inserisci IP e chiave SSH",
	"vps.agents_live": "AGENTI ATTIVI SULLA VPS",
	"vps.agents_none": "nessun agente attivo in questo momento",
	"vps.steps": "1  Crea la chiave  →  2  aggiungila alla VPS  →  3  verifica SSH  →  4  prepara e collega",
	"vps.key_section": "1 · CHIAVE SSH DEDICATA",
	"vps.key_generate": "GENERA CHIAVE",
	"vps.key_copy": "COPIA PUBBLICA",
	"vps.key_open": "APRI CARTELLA",
	"vps.key_note": "La chiave privata resta sul computer; al provider va incollata soltanto la riga .pub.",
	"vps.key_fingerprint_none": "Fingerprint: non disponibile per la chiave selezionata — non c'è niente da confrontare con il provider.",
	"vps.destination": "2 · SERVER DI DESTINAZIONE",
	"vps.fingerprint_note": "VERIFICA SSH mostra il fingerprint host: confrontalo con quello indicato dal provider.",
	"vps.connect_existing": "COLLEGA SENZA INSTALLARE",
	"vps.verify_ssh": "VERIFICA SSH",
	"vps.prepare": "PREPARA E COLLEGA AUTOMATICAMENTE",
	"vps.advanced": "CONSOLE AVANZATA",
	"vps.migration_title": "3 · MIGRAZIONE COMPLETA (OPZIONALE)",
	"vps.migration_desc": "Trasferisce database, profilo, documenti, configurazione, login provider e pairing cloud. Chiavi SSH e runtime restano sulla macchina a cui appartengono. Snapshot, checksum e backup vengono verificati prima dello scambio.",
	"vps.source_local": "DA QUESTO COMPUTER",
	"vps.source_saved": "DALLA VPS ATTUALMENTE SALVATA",
	"vps.migrate_to_vps": "MIGRA TUTTO SULLA NUOVA VPS  →",
	"vps.migrate_to_local": "←  MIGRA DALLA VPS A QUESTO COMPUTER",
	"vps.migration_note": "La sorgente viene fermata e disarmata soltanto dopo la verifica della destinazione. Qualunque errore ripristina sorgente e destinazione.",
	"vps.confirm_vps_title": "Migrare tutto sulla nuova VPS?",
	"vps.confirm_source_local": "La sorgente è questo computer.",
	"vps.confirm_source_vps": "La sorgente è la VPS attualmente salvata.",
	"vps.confirm_body": "Il team verrà fermato durante lo snapshot. I dati non saranno cancellati: la destinazione riceverà una copia verificata e conserverà un backup pre-migrazione.",
	"vps.confirm_vps_ok": "FERMA, COPIA E ATTIVA LA NUOVA VPS",
	"vps.confirm_local_title": "Riportare tutto su questo computer?",
	"vps.confirm_local_body": "La VPS verrà fermata, copiata e verificata prima di attivare il team locale. I dati locali attuali avranno un backup e saranno ripristinati automaticamente se qualcosa fallisce.",
	"vps.confirm_local_ok": "FERMA LA VPS, COPIA E ATTIVA IN LOCALE",

	# ── Posizioni (vista web migrata) ─────────────────────────────
	"pos.need_vps": "Collega la VPS per vedere le posizioni reali del team (Impostazioni → Collega VPS).",
	"pos.count": "%d posizioni · %d visibili",
	"pos.clear": "✕ PULISCI FILTRI",
	"pos.filters": "FILTRI (%d)",
	"pos.filters_hide": "NASCONDI FILTRI",
	"pos.all": "TUTTI",
	"pos.selected": "%d SELEZIONATI",
	"pos.rows": "RIGHE",
	"pos.range": "%d–%d di %d",
	"pos.page": "PAGINA %d / %d",
	"pos.previous": "◀ PRECEDENTE",
	"pos.next": "SUCCESSIVA ▶",
	"pos.no_match": "nessuna posizione con questi filtri",
	"pos.f_status": "STATO",
	"pos.f_family": "FAMIGLIA DI RUOLO",
	"pos.f_country": "PAESE",
	"pos.f_mode": "MODALITÀ",
	"pos.uncategorized": "senza categoria",

	# ── Dettaglio posizione ───────────────────────────────────────
	"pos.back": "◀ POSIZIONI",
	"pos.salary": "STIPENDIO",
	"pos.salary_estimated": "stima del team",
	"pos.salary_declared": "dichiarato nell'annuncio",
	"pos.summary": "RIASSUNTO DELL'ANNUNCIO",
	"pos.score_title": "SCORE — %d/100",
	"pos.score_none": "non ancora studiata dal reparto Compatibilità",
	"pos.score_rationale": "RAZIONALE DELLO SCORER",
	"pos.critic_title": "VOTO DEL CRITICO — %.1f/10",
	"pos.critic_none": "nessun controllo qualità ancora completato",
	"pos.highlights": "PUNTI CHIAVE",
	"pos.actions": "AZIONI RICHIESTE AL TEAM",
	"pos.act_write": "Scrittura CV",
	"pos.act_geocode": "Geocodifica ufficio",
	"pos.act_recheck": "Verifica annuncio ancora aperto",
	"pos.act_requested": "richiesta",
	"pos.act_not_requested": "non richiesta",
	"pos.act_note": "// le azioni le esegue il team sulla VPS — per chiedere qualcosa apri un ticket qui sotto",
	"pos.excluded_title": "ESCLUSA DALL'UTENTE",
	"pos.tickets": "TICKET APERTI COL TEAM",
	"pos.ticket_none": "nessun ticket per questa posizione",
	"pos.ticket_placeholder": "scrivi una richiesta al team su questa posizione…",
	"pos.ticket_send": "APRI TICKET",
	"pos.ticket_sending": "invio del ticket alla VPS…",
	"pos.ticket_ok": "✓ ticket aperto — il Coordinatore lo prenderà in carico",
	"pos.ticket_err": "✘ ticket non creato: %s",
	"pos.ticket_need_vps": "// collega la VPS per aprire ticket col team",
	"pos.found": "trovata da %s · %s",
	"pos.open_url": "apri l'annuncio nel browser",
	"pos.open_yes": "annuncio APERTO all'ultima verifica",
	"pos.open_no": "annuncio NON PIÙ APERTO",
	"pos.office_address": "INDIRIZZO",
	"pos.office_verified": "verificato dagli Analisti",
	"pos.office_approx": "non verificato · centro città",

	# ── Candidature e Notifiche (dati reali) ──────────────────────
	"apps.ready": "CV pronto",
	"apps.applied": "inviata",
	"apps.response": "risposta ricevuta",
	"apps.empty_live": "il monitoraggio delle candidature e' opzionale; osservare il mercato e' un uso completo di JHT",
	"notifs.ticket_resolved": "ticket risolto: %s",
	"notifs.ticket_assigned": "ticket in lavorazione: %s",
	"notifs.scored": "studiata dal reparto Compatibilità: %s",
	"notifs.cv_ready": "CV scritto: %s",
	"notifs.applied": "candidatura inviata: %s",
	"notifs.response": "risposta ricevuta: %s",
	"notifs.empty": "nessuna notifica recente dal team",
	"agents.comms": "COMUNICAZIONI NEL TEAM",
	"agents.no_comms": "nessuna comunicazione recente",
	"agents.chat_besteffort": "(risposta non garantita: protocollo chat non nel suo prompt)",

	# ── GlobalSearch (Cmd+K) ──────────────────────────────────────
	"search.placeholder": "cerca posizioni: titolo, azienda, città…  (ESC chiude)",
	"search.no_match": "nessuna posizione trovata",
	"search.need_vps": "collega la VPS per cercare tra le posizioni reali",

	# ── Profilo (editabile: paradigma desktop app) ────────────────
	"prof.name": "Nome",
	"prof.email": "Email",
	"prof.target_role": "Ruolo target",
	"prof.location": "Località",
	"prof.experience": "Anni di esperienza",
	"prof.seniority": "Seniority target",
	"prof.industry": "Settore",
	"prof.nationality": "Nazionalità",
	"prof.languages": "LINGUE (separate da virgola)",
	"prof.skills": "SKILL PRIMARIE (separate da virgola)",
	"prof.salary": "SALARY TARGET (min / max / valuta)",
	"prof.save": "▶ SALVA PROFILO",
	"prof.saving": "salvataggio sulla VPS…",
	"prof.saved": "✓ profilo salvato — il team lo userà dal prossimo giro",
	"prof.save_err": "✘ salvataggio fallito: %s",

	# ── Mappa OSM ─────────────────────────────────────────────────
	"map.hint": "trascina per muoverti · rotella/pinch per lo zoom · click su un pin per le sue posizioni",
	"map.globe_hint": "trascina per ruotare il mondo · click su un pin per atterrarci · avvicinati per la mappa",
	"map.filters": "FILTRI",
	"map.f_score": "SCORE",
	"map.f_city": "CITTÀ",
	"map.score_none": "senza punteggio",
	"map.overview": "PANORAMICA",
	"map.card_hint": "click su una posizione per aprire la scheda",
	"map.card_hint_all": "%d posizioni · scorri l’elenco e clicca per aprire la scheda",
	"map.cluster": "%d posizioni · %d località",
	"map.pin_approx": "pin sul centro città: indirizzo esatto non verificato",

	# ── Orari di lavoro (editabili, con stima dinamica) ───────────
	"hours.intro": "Le finestre in cui il team lavora: modifica e salva, il pacing si adegua.",
	"hours.tz": "Timezone",
	"hours.windows": "FINESTRE (giorni · dalle → alle)",
	"hours.add": "+ AGGIUNGI FINESTRA",
	"hours.presets": "PARTI DA QUI",
	"hours.preset_office": "Orario d'ufficio",
	"hours.preset_evening": "Sera e weekend",
	"hours.preset_always": "Sempre attivo",
	"hours.first_time": "Non hai ancora scelto gli orari: parti da una di queste proposte e correggila come vuoi.",
	"hours.need_team": "Per impostare gli orari serve il team acceso: torna al passo 01 e avvia il container.",
	"hours.estimate": "≈ %.0f ore attive/settimana → stima ~%.1f posizioni nuove/giorno · budget riproporzionato al %d%% dell'attuale",
	"hours.estimate_first": "≈ %.0f ore attive/settimana · stima e budget saranno disponibili dopo la prima settimana",
	"hours.invalid": "✘ finestra non valida: giorni mon…sun e orari HH:MM",
	"hours.save": "▶ SALVA ORARI",
	"hours.saved": "✓ orari salvati — il pacing del team si adegua dal prossimo tick",

	# ── Impostazioni → Lingua ─────────────────────────────────────
	"lang.intro": "Lingua dell'interfaccia — le 7 lingue del sito.",
	"lang.narrative_note": "// nota: il tour narrativo e le sue scelte sono attualmente disponibili in italiano",
	"lang.note": "// si applica subito ai pannelli; riapri quelli già aperti per vederli tradotti",

	# ── Statistiche: grafici cross-filter (come la dashboard web) ─
	"stats.hint": "// click su una barra per filtrare: gli altri grafici si aggiornano",
	"stats.filters": "FILTRI ATTIVI: %d",
	"stats.reset": "✕ AZZERA",
	"stats.types": "TIPI DI RUOLO",
	"stats.countries": "PAESI",
	"stats.cities": "CITTÀ",
	"stats.scores": "SCORE (fasce da 5)",
	"stats.salaries": "STIPENDI (fasce da 20k €)",
	"stats.matches": "POSIZIONI CORRISPONDENTI — %d",
	"stats.no_city": "· senza città: %d",
	"stats.no_country": "(senza paese)",
	"stats.empty": "nessun dato con questi filtri",
	"stats.need_vps": "collega la VPS per i grafici sui dati reali",

	# ── Monitoraggio risorse: usage nel tempo + consumi agenti ────
	"side.usage_history": "Usage",
	"side.usage_agents": "Consumi agenti",
	"usage.no_data": "nessun dato nella finestra",
	"usage.loading": "◌ carico lo storico…",
	"usage.loading_veil": "CARICO LO STORICO",
	"usage.donut_back": "◀ torna al totale",
	"usage.donut_hint": "// hover per i dettagli · click su (altri) per approfondire",
	"usage.role_pooled": "×%d istanze",
	"usage.error": "✘ storico non disponibile: %s",
	"usage.to_now": "ORA",
	"usage.hint": "// finestra %s · legenda cliccabile per nascondere una serie",
	"usage.group_quota": "QUOTE %",
	"usage.group_velocity": "VELOCITÀ",
	"usage.group_tokens": "TOKEN",
	"usage.group_events": "EVENTI",
	"usage.series_usage": "usage 5h %",
	"usage.series_weekly": "weekly %",
	"usage.series_projection": "proiezione %",
	"usage.series_velocity": "velocità %/h",
	"usage.series_velocity_ideal": "velocità ideale %/h",
	"usage.series_weighted": "token pesati · finestra 5h",
	"usage.series_events": "eventi API · finestra 5h",
	"usage.series_throttle": "pause pacing · s per bucket",
	"usage.stacked": "CHI CONSUMA QUANDO — kT per bucket, impilati",
	"usage.ranking": "CLASSIFICA CONSUMI — kT nel periodo",
	"usage.share": "QUOTA SUL TOTALE",
	"usage.heatmap": "MAPPA ORARIA — kT per ora × giorno",
	"usage.heatmap_hint": "// intensità = kT consumati in quell'ora di quel giorno",
	"usage.others": "(altri)",
	"usage.total": "totale %s kT",
	"usage.no_agents": "nessun consumo per-agente nel periodo (i log CLI coprono ~10 giorni)",
	"agent.stats": "▤ SCHEDA E GRAFICI",
	"agent.history_title": "STORICO CONSUMI E AZIONI",
	"agent.history_hint": "// ogni serie ha la sua scala (max in legenda) · click sulla legenda per accendere/spegnere",
	"agent.history_all": "TUTTE",
	"agent.history_none": "NESSUNA",
	"agent.hs_tokens": "token kt",
	"agent.hs_pct5h": "usage finestra 5h %",
	"agent.hs_pctweek": "usage weekly %",
	"agent.hs_day": "consumo di oggi · % weekly cum.",
	"agent.hs_throttle": "throttle s",
	"agent.hs_db": "azioni db",
	"agent.hs_cpu_agent": "cpu agente %",
	"agent.hs_ram_agent": "ram agente MB",
	"agent.hs_cpu": "cpu container %",
	"agent.hs_ram": "ram container %",
	"agent.history_ctx_note": "// cpu/ram agente = sampler agent-vitals (dal prossimo lancio team); container = contesto",

	# ── Dashboard: pipeline del flusso reale ──────────────────────
	"dash.pipeline": "PIPELINE",
	"dash.pl_to_analyze": "Da analizzare",
	"dash.pl_analyzed": "Analizzate",
	"dash.pl_with_score": "Con lo score",
	"dash.pl_to_write": "Da scrivere",
	"dash.pl_written": "Scritte",
	"dash.pl_hint": "// click su un box per aprire le posizioni filtrate",

	# ── Comuni (liste troncate, note sola-lettura, attese dati) ───────
	"common.more": "… e altre %d",
	"common.readonly_desktop": "// sola lettura in questa vista",
	"common.readonly_chat": "// sola lettura — usa la chat nativa dell'agente",
	"common.data_incoming": "// dati in arrivo dalla VPS…",
	"common.updated": "aggiornato: %s",
	# il backend È collegato: è la singola funzione che non implementa
	"common.backend_unsupported": "Il backend collegato non offre questa funzione.",

	# ── Badge simulazione / dati reali ────────────────────────────────
	"sim.live_vps": "● DATI REALI — VPS",
	"sim.live_local": "● DATI REALI — QUESTO COMPUTER",
	# ── Finestra di lavoro esaurita ───────────────────────────────────
	"budget.exhausted": "Il team ha esaurito la finestra di lavoro — riprende %s",
	"budget.near_limit": "Finestra di lavoro al %d%% — il team rallenta, si riapre %s",
	"budget.in_minutes": "fra %d min",
	"budget.in_hours": "fra %dh %02dm",
	"sim.mock": "◐ SIMULAZIONE — dati non reali",

	# ── Ufficio (hint camera) ─────────────────────────────────────────
	"office.camera_hint": "trascina o WASD per la camera · zoom con rotella, pinch o +/- · click su agenti e reparti · TAB registro · ESC menu",

	# ── Sidebar: gruppi e voci (specchio della desktop app) ───────────
	"side.group_team": "Team",
	"side.group_work": "Lavoro",
	"side.group_system": "Sistema",
	# la riga che apre la finestra a schede: dentro, "Statistiche" è una scheda
	"side.monitor": "Monitoraggio",
	# la riga che raccoglie le dodici pagine di configurazione
	"side.settings": "Impostazioni",
	"settings.grp_setup": "Configurazione",
	"settings.grp_channels": "Account e canali",
	"settings.grp_interface": "Interfaccia",
	"side.activation": "Attiva team",
	"side.team": "Team",
	"side.agents": "Agenti",
	"side.chat": "Chat",
	"side.notifs": "Notifiche",
	"side.dashboard": "Dashboard",
	"side.positions": "Posizioni",
	"side.stats": "Statistiche",
	"side.apps": "Candidature",
	"side.map": "Mappa",
	"side.activity": "Attività",
	"side.vps": "Collega VPS",
	"side.profile": "Profilo",
	"side.hours": "Orari",
	"side.provider": "Provider",
	"side.docker": "Docker",
	"side.telegram": "Telegram",
	"side.agent_metrics": "Risorse agenti",
	"side.account": "Account",
	"side.email": "Email",
	"side.appearance": "Aspetto",
	"side.graphics": "Grafica",
	"side.language": "Lingua",
	"side.advanced": "Avanzate",
	"side.feedback": "Segnala un problema",

	# ── Impostazioni → Segnala un problema ───────────────────────
	"feedback.intro": "Raccontaci cosa è andato storto: bastano due frasi. Prima dell'invio rimuoviamo dati personali, contatti e segreti dal racconto e dalla diagnostica; puoi vedere esattamente il report che parte.",
	"feedback.q_doing": "COSA STAVI FACENDO",
	"feedback.ph_doing": "es. stavo attivando il team dopo aver collegato la VPS",
	"feedback.q_happened": "COSA È SUCCESSO",
	"feedback.ph_happened": "es. la schermata è rimasta ferma su «collegamento» per dieci minuti",
	"feedback.q_expected": "COSA TI ASPETTAVI",
	"feedback.ph_expected": "es. che il team partisse e comparissero gli agenti",
	"feedback.q_contact": "EMAIL PER LA RISPOSTA (facoltativa)",
	"feedback.ph_contact": "senza indirizzo non possiamo farti sapere com'è finita",
	"feedback.contact_hint": "// usata solo per rispondere a questa segnalazione",
	"feedback.attach_diag": "Allega la diagnostica del computer",
	"feedback.attach_container": "Allega i log del runtime",
	"feedback.collecting": "Raccolgo la diagnostica…",
	"feedback.redacted_none": "Nessun dato personale o segreto da rimuovere nel report.",
	"feedback.redacted_count": "%d dati personali o segreti rimossi dal report prima dell'invio.",
	"feedback.send": "INVIA SEGNALAZIONE",
	"feedback.preview_btn": "VEDI COSA STAI INVIANDO",
	"feedback.open_folder": "APRI CARTELLA REPORT",
	"feedback.preview_title": "Questo è esattamente il report che parte. Contatti, dati personali e segreti non lasciano il computer.",
	"feedback.back": "◂ TORNA AL MODULO",
	"feedback.sending": "Invio in corso…",
	"feedback.sent": "Segnalazione inviata. Grazie: la leggiamo davvero.",
	"feedback.failed": "Invio non riuscito.",
	"feedback.offline": "Nessuna connessione all'assistenza.",
	"feedback.too_many": "Troppe segnalazioni ravvicinate: riprova tra qualche minuto.",
	"feedback.ticket": "riferimento %s",
	"feedback.saved_copy": "Una copia è salvata in %s: puoi allegarla a una mail.",

	# ── Impostazioni → Aspetto ───────────────────────────────────
	"appearance.intro": "Scegli l’aspetto dell’interfaccia. Il mondo dell’ufficio mantiene la sua illuminazione; menu, finestre, dialoghi e grafici cambiano insieme.",
	"appearance.current": "TEMA ATTIVO: %s",
	"appearance.light": "Chiaro",
	"appearance.dark": "Scuro",
	"appearance.light_desc": "Finestre bianche, testo scuro e accenti ad alto contrasto",
	"appearance.dark_desc": "Interfaccia terminale scura con accenti luminosi",
	"appearance.note": "// la preferenza viene salvata su questo dispositivo",

	# ── Impostazioni → Grafica ───────────────────────────────────
	"gfx.intro": "Il gioco misura da sé quanti fotogrammi riesce a fare e alleggerisce la grafica quando serve. Se preferisci decidere tu, scegli un profilo: da quel momento comanda la tua scelta e la misura automatica non tocca più niente.",
	"gfx.current": "PROFILO ATTIVO: %s",
	"gfx.state": "mondo disegnato al %d%% · scenografia %s",
	"gfx.scenery_on": "accesa",
	"gfx.scenery_off": "spenta",
	"gfx.auto": "Automatico",
	"gfx.auto_desc": "Il gioco misura gli fps e si adatta mentre giochi",
	"gfx.full": "Massima",
	"gfx.full_desc": "Mondo a risoluzione piena, scenografia completa",
	"gfx.balanced": "Equilibrata",
	"gfx.balanced_desc": "Mondo all’85%: la grana si nota appena, un quarto di lavoro in meno per la GPU",
	"gfx.performance": "Prestazioni",
	"gfx.performance_desc": "Mondo al 60% e scenografia spenta: per le macchine che arrancano",
	"gfx.note": "// la scelta è salvata su questo dispositivo. Le scritte dentro l’ufficio si ingrandiscono da sé quando la risoluzione scende: restano leggibili con ogni profilo.",

	# ── Sezioni non ancora migrate / config sola lettura ──────────────
	"section.migrating": "// sezione non ancora disponibile",
	"section.migrating_body": "I contenuti di «%s» verranno portati qui, un pezzo alla volta.",
	"config.incoming": "// config in arrivo dalla VPS…",
	"config.not_exposed": "// sezione non ancora esposta dal team",

	# ── Sezione Agenti (lista + pagina del singolo agente) ────────────
	"agents.back": "◀ AGENTI",
	"agents.not_active": "non attivo ora",
	"agents.consumption": "CONSUMO (ULTIME %s ORE)",
	"agents.registry_actions": "AZIONI NEL REGISTRO",
	"agents.no_transitions": "nessuna transizione recente a suo nome",
	"agents.active_count": "%d agenti ATTIVI sulla VPS in questo momento",
	"agents.status_default": "operativo",
	"agents.restart": "RIAVVIA",
	"agents.stop": "FERMA",

	# ── Sezione Team ──────────────────────────────────────────────────
	"team.desks": "%d/%d postazioni",
	# I tre nomi arrivano da role.* e non sono scritti qui dentro: la riga
	# era identica in tutte e 7 le lingue (italiana anche in inglese) e la
	# parità di chiavi non poteva accorgersene.
	"team.core": "Core: %s · %s · %s",
	"team.stop": "FERMA TEAM",
	"team.start": "AVVIA TEAM",
	"team.setup": "SETUP E STATO",

	# ── Setup iniziale aperto ─────────────────────────────────────
	"setup.cta": "SETUP TEAM · %d/4 COMPLETATO  →",
	"setup.ready_to_start": "SETUP COMPLETO · ATTIVA IL TEAM  →",
	"setup.intro": "L’ufficio è già tuo. Per mettere davvero al lavoro gli agenti completa questi quattro passaggi, nell’ordine che preferisci.",
	"setup.office_open": "Puoi chiudere questa finestra e continuare a esplorare in qualsiasi momento: il setup non blocca l’app.",
	"setup.container": "Container",
	"setup.where": "Dove lavora il team",
	"setup.hours": "Orari di lavoro",
	"setup.hours_todo": "Quando il team può lavorare. Senza orari macina a ogni ora e consuma l'abbonamento.",
	"setup.hours_ok": "Finestre di lavoro impostate.",
	"setup.remote_unknown": "Non leggibile sulla macchina connessa. Il valore di questo computer non conta: è di un’altra macchina.",
	"setup.where_todo": "Sul tuo computer, oppure su una VPS che lavora anche a finestra chiusa.",
	"setup.where_local": "Il team lavora su questo computer.",
	"setup.where_vps": "Il team lavora sulla VPS: questa finestra ne è lo specchio.",
	"setup.use_vps": "PORTA IL TEAM SU UNA VPS",
	"setup.provider": "Provider AI",
	"setup.profile": "Profilo e CV",
	"setup.container_ok": "Il container JHT è acceso e raggiungibile.",
	"setup.container_todo": "Accendi l’ambiente isolato in cui lavorano gli agenti.",
	"setup.provider_todo": "Scegli Claude, Codex o Kimi e accedi col tuo abbonamento.",
	"setup.provider_ok": "%s collegato con l’abbonamento.",
	"setup.provider_login": "%s selezionato: manca il login.",
	"setup.provider_recheck": "RICONTROLLA IL LOGIN",
	"setup.provider_rechecking": "CONTROLLO…",
	"setup.plan_todo": "%s collegato: manca l’abbonamento.",
	"setup.plan_question": "Che abbonamento hai su questo account? Decide quanti agenti accendere.",
	"setup.plan_unavailable": "Elenco abbonamenti non disponibile: accendi il container (passo 01).",
	"setup.profile_ok": "L’Assistente ha tutte le informazioni necessarie.",
	"setup.profile_todo": "Consegna il CV e completa il colloquio con l’Assistente.",
	"setup.progress": "SETUP %d/4",
	"setup.configure": "CONFIGURA  →",
	"setup.review": "CONTROLLA  →",
	"setup.start_team": "▶ ATTIVA IL TEAM",
	"setup.team_running": "● TEAM ATTIVO",
	"setup.team_locked": "TEAM NON ANCORA ATTIVO · SETUP %d/4 — COMPLETA ORA  →",
	"setup.container_lead": "Il container isola il team e conserva i dati in ~/.jht. L’ufficio resta visitabile anche quando è spento.",
	"setup.docker_ready": "runtime disponibile",
	"setup.docker_missing": "runtime spento o non installato",
	"setup.container_start": "▶ ATTIVA CONTAINER",
	"setup.container_recheck": "↻ RICONTROLLA",
	"setup.runtime_current": "aggiornato",
	"setup.runtime_stale": "aggiornamento pronto: riattiva il container",
	"setup.runtime_update": "⇩ AGGIORNA RUNTIME",
	"setup.runtime_update_busy": "◌ AGGIORNAMENTO SICURO IN CORSO…",
	"setup.runtime_check": "↻ VERIFICA AGGIORNAMENTI",
	"setup.runtime_check_busy": "◌ CONTROLLO AGGIORNAMENTI IN CORSO…",
	"setup.runtime_check_running": "Controllo aggiornamenti runtime…",
	"setup.runtime_check_unknown": "aggiornamenti non verificati",
	"setup.runtime_check_current": "Nessun aggiornamento disponibile",
	"setup.runtime_check_available": "Aggiornamento disponibile",
	"setup.runtime_check_error": "Impossibile verificare gli aggiornamenti: il runtime non è stato modificato.",
	"setup.upgrade_running": "Avvio aggiornamento sicuro del runtime…",
	"setup.upgrade_phase": "Fase finale: %s",
	"setup.upgrade_current": "Versione runtime attiva: %s",
	"setup.upgrade_rolled_back": "La versione precedente è stata ripristinata.",
	"setup.upgrade_restart_required": "Il runtime richiede il riavvio di Job Hunter Team per applicare l’aggiornamento.",
	"setup.upgrade_protocol_error": "Risultato dell’aggiornamento non verificabile: il runtime esistente non è stato modificato.",
	"setup.back_overview": "← PANORAMICA SETUP",
	"setup.docker_install": "INSTALLA DOCKER",
	"setup.provider_lead": "Scegli un solo provider principale. Il login usa il tuo abbonamento: JHT non chiede né salva API key.",
	"setup.provider_note": "Il login si svolge nella console incorporata: link, codice e scelte restano dentro il gioco; il browser si apre solo per autorizzare l’account.",
	"setup.provider_connected": "✓ login rilevato",
	"setup.provider_disconnected": "○ login da completare",
	"setup.provider_choose": "USA QUESTO PROVIDER",
	"setup.provider_subscription_login": "LOGIN CON ABBONAMENTO  →",
	"setup.provider_relogin": "APRI CONSOLE / CAMBIA ACCOUNT",
	"setup.provider_install": "INSTALLA / AGGIORNA CLI",
	"setup.provider_subscribe": "Non hai un abbonamento? Vedi i piani ↗",
	"setup.login_hint_claude": "Nella console interna scegli il login con abbonamento e apri il link mostrato.",
	"setup.login_hint_codex": "Codex usa il device code: apri il link, inserisci il codice mostrato e autorizza ChatGPT.",
	"setup.login_hint_kimi": "Nella console interna digita /login. Il browser completa normalmente il ritorno in automatico.",
	"setup.profile_lead": "Il profilo si costruisce parlando con l’Assistente, non compilando un modulo rigido.",
	"setup.profile_ready_lead": "✓ Il profilo è pronto. Puoi comunque riaprire l’Assistente per aggiornarlo.",
	"setup.profile_body": "Carica il CV e racconta obiettivi, località, esperienza, competenze e lingue. Il badge mostra cosa manca senza costringerti a un percorso prestabilito.",
	"setup.profile_open": "PARLA CON L’ASSISTENTE E CARICA IL CV  →",
	"setup.profile_requires": "Prima accendi il container e completa il login del provider: servono per far rispondere davvero l’Assistente.",
	"setup.tour_progress": "TOUR CONVERSAZIONALE · %d/3 COMPLETATI",
	"setup.tour_assistant": "ASSISTENTE",
	"setup.tour_coordinator": "COORDINATORE",
	"setup.tour_mentor": "MENTOR",
	"setup.runtime_version": "VERSIONE RUNTIME",
	"setup.container_stop": "FERMA CONTAINER",
	# Filiera di attivazione del container: le fasi REALI dietro l'unico
	# pulsante, nell'ordine in cui succedono.
	"setup.phase_engine": "MOTORE DOCKER",
	"setup.phase_image": "IMMAGINE DEL TEAM",
	"setup.phase_container": "CONTAINER JHT",
	"setup.phase_team": "TEAM",
	"setup.phase_running": "in corso adesso…",
	# Barra di avanzamento dell'attivazione: percentuale SOLO dove il dato
	# esiste (byte del pull), tempo trascorso sempre, stallo dichiarato.
	"setup.progress_phase": "FASE %d DI %d — %s",
	"setup.progress_elapsed": "trascorsi %s",
	"setup.progress_no_meter": "Questa fase non riporta una percentuale di avanzamento: conta il tempo trascorso.",
	"setup.progress_downloaded": "%s scaricati (dimensione totale non dichiarata)",
	"setup.progress_eta": "~%s rimanenti",
	"setup.progress_stalled": "Nessun aggiornamento da %d s — la rete potrebbe essere lenta.",
	"setup.image_ready": "scaricata e pronta",
	"setup.image_missing": "da scaricare (qualche GB, dipende dalla rete)",
	"setup.container_busy": "◌ ATTIVAZIONE IN CORSO…",
	"setup.team_starting": "◌ AVVIO IN CORSO…",
	"setup.team_stopping": "◌ ARRESTO IN CORSO…",
	"setup.team_on": "al lavoro",
	"setup.provider_needs_container": "Prima accendi il container (passo 01): il login si svolge nella sua console.",
	"setup.needs_container_cmd": "Prima accendi il container (passo 01): questo comando agisce al suo interno.",
	"setup.busy_note": "◌ In corso: %s. I comandi spenti si riattivano da soli appena finisce.",
	"setup.busy_container": "l’attivazione del container",
	"setup.busy_upgrade": "l’aggiornamento del runtime",
	"setup.busy_team": "l’avvio o l’arresto del team",
	"setup.busy_provider": "la configurazione del provider AI",
	"setup.busy_vps": "un’operazione sulla VPS",
	"setup.busy_generic": "un’operazione di setup",
	"setup.team_row_info": "spento — si avvia dalla checklist «Attiva team», non da qui",
	"setup.provider_active": "  ·  ATTIVO",
	"setup.provider_logout": "DISCONNETTI ACCOUNT",

	# ── Titoli KPI (dashboard, statistiche, utilizzo) ─────────────────
	"kpi.positions_today": "POSIZIONI OGGI",
	"kpi.avg_score": "SCORE MEDIO",
	"kpi.positions_total": "POSIZIONI TOTALI",
	"kpi.positions_list": "POSIZIONI DI OGGI",
	"kpi.budget_used": "BUDGET USATO",
	"kpi.apps_by_stage": "CANDIDATURE PER STADIO",
	"kpi.provider": "PROVIDER",
	"kpi.actions_today": "AZIONI OGGI",
	"kpi.actions_week": "AZIONI SETTIMANA",
	"kpi.tokens_today": "TOKEN OGGI",
	"kpi.quota_week": "QUOTA SETTIMANALE",

	# ── Pagina Utilizzo ───────────────────────────────────────────────
	"usage.open": "▶ UTILIZZO",
	"usage.title": "UTILIZZO",
	"usage.title_window": "UTILIZZO — ULTIME %s ORE",
	"usage.none": "nessun consumo registrato nella finestra",
	"usage.back": "◀ STATISTICHE",

	# ── Mappa ─────────────────────────────────────────────────────────
	"map.no_coords": "SENZA COORDINATE (%d)",
	"map.none_today": "nessuna posizione geolocalizzata oggi",

	# ── Impostazioni → Account cloud ──────────────────────────────────
	"account.intro": "Sincronizza posizioni, profilo e comandi con jobhunterteam.ai. L'account è opzionale: il team può restare completamente locale.",
	"account.cloud": "ACCOUNT CLOUD",
	"account.linked": "collegato",
	"account.local_mode": "modalità locale / ospite",
	"account.device": "DISPOSITIVO",
	"account.device_paired": "associato",
	"account.server": "SERVER",
	"account.login_again": "RIFAI LOGIN GOOGLE",
	"account.login": "ACCEDI CON GOOGLE  →",
	"account.other_account": "USA UN ALTRO ACCOUNT",
	"account.status": "STATO",
	"account.sync_now": "SINCRONIZZA ORA",
	"account.pull_profile": "RECUPERA PROFILO",
	"account.disable_sync": "FERMA SYNC E CONTINUA SOLO IN LOCALE",
	"account.restore": "RIPRISTINA PIPELINE DAL CLOUD",
	"account.manage_devices": "GESTISCI DISPOSITIVI E REVOCA  ↗",
	"account.privacy_note": "Il login Google autentica il tuo account web. La VPS conserva solo un token di dispositivo revocabile; password e cookie Google non vengono salvati nel gioco.",
	"account.disable_title": "Continuare solo in locale?",
	"account.disable_body": "Il team continuerà a funzionare e i dati locali non verranno cancellati. Il token di questo dispositivo verrà revocato e posizioni/profilo non saranno più sincronizzati col cloud.",
	"account.disable_ok": "FERMA SINCRONIZZAZIONE",

	# ── Impostazioni → Email ──────────────────────────────────────────
	"email.intro": "Casella dedicata agli avvisi di lavoro. Il reparto Ricerca la controlla a inizio giornata e porta in ufficio le opportunità ricevute.",
	"email.status": "STATO",
	"email.configured": "configurata · ",
	"email.none": "nessuna casella configurata",
	"email.address": "INDIRIZZO EMAIL",
	"email.app_password": "APP PASSWORD",
	"email.password_ph": "password specifica per l'app, mai la password principale",
	"email.note": "La password rimane in ~/.jht/credentials con permessi 0600 e non viene sincronizzata sul cloud.",
	"email.save": "SALVA E VERIFICA IMAP",
	"email.remove": "RIMUOVI",
	"email.help": "COME CREARE UNA APP PASSWORD  ↗",

	# ── Impostazioni → Telegram ───────────────────────────────────────
	"tg.intro": "Collega i tre bot privati usati dal team. I token restano nel runtime locale o sulla tua VPS e non vengono mai inviati al cloud JHT.",
	"tg.botfather": "APRI BOTFATHER  ↗",
	"tg.guide": "Crea un bot, incolla il token, apri la chat col bot e premi Start; poi usa SALVA E RILEVA CHAT.",
	"tg.role_assistente": "onboarding del profilo e documenti",
	"tg.role_capitano": "direzione del team e posizioni pronte",
	"tg.role_mentor": "coaching e strategia professionale",
	"tg.configured": "● CONFIGURATO",
	"tg.to_link": "○ DA COLLEGARE",
	"tg.token_ph": "token BotFather",
	"tg.chat_id_ph": "chat_id (opzionale: rilevamento automatico)",
	"tg.save": "SALVA E RILEVA CHAT",
	"tg.remove": "RIMUOVI",

	# ── Impostazioni → Avanzate ───────────────────────────────────────
	"advanced.intro": "Diagnostica e manutenzione del runtime. Ogni comando resta visibile dentro il gioco.",
	"advanced.doctor": "ESEGUI DIAGNOSTICA",
	"advanced.review_setup": "RIVEDI SETUP",
	"advanced.reinstall": "REINSTALLA / AGGIORNA RUNTIME",
	"advanced.open_data": "APRI DATI JHT",
	"advanced.open_log": "APRI LOG DEL GIOCO",
	"advanced.version": "Versione gioco %s · dati applicazione %s",

	# ── Sistema VPS (telemetria host e container) ─────────────────────
	"sys.title": "SISTEMA VPS · LIVE",
	"sys.subtitle": "Host e container jht · aggiornamento ogni 8 secondi",
	"sys.disk": "DISCO /",
	"sys.cpu_host_history": "CPU HOST · STORICO",
	"sys.ram_host_history": "RAM HOST · STORICO",
	"sys.container_status": "STATO CONTAINER",
	"sys.container_mem": "MEMORIA JHT",
	"sys.restarts": "RIAVVII",
	"sys.load1": "LOAD 1 MIN",
	"sys.uptime": "UPTIME VPS",
	"sys.rx": "RETE RICEVUTA",
	"sys.tx": "RETE INVIATA",

	# ── Risorse per agente (live) ─────────────────────────────────────
	"metrics.title": "RISORSE PER AGENTE · LIVE",
	"metrics.subtitle": "RAM = processo tmux e discendenti · token = bucket reali del token-meter",
	"metrics.freshness_wait": "TOKEN · freschezza in attesa…",
	"metrics.col_agent": "AGENTE",
	"metrics.col_ram_history": "STORICO RAM",
	"metrics.tokens_window": "TOKEN (%s)",
	"metrics.tokens_bucket": "TOKEN / %s",
	"metrics.no_source": "TOKEN · sorgente non disponibile",
	"metrics.stale": "TOKEN · %s · STALE DA %s",
	"metrics.updated": "TOKEN · aggiornati %s · %s fa",

	# ── Showroom (dati dimostrativi) ──────────────────────────────────
	"demo.map": "◆ SHOWROOM · pin e offerte sono esempi fittizi",
	"demo.positions": "◆ SHOWROOM · 50 POSIZIONI FITTIZIE · nessun dato personale o link attivo",
	# ── Modalità operative del Coordinatore ───────────────────────────
	"burn.section": "MODALITÀ OPERATIVE",
	"burn.section_desc": "deroghe che concedi tu, a termine",
	"burn.title": "Spinta massima",
	"burn.duration": "Durata",
	"burn.desc": "Di norma il team rallenta da solo per far durare il budget: si ferma quando ha speso la quota del giorno, tace fuori dall'orario di lavoro e riduce il ritmo man mano che la finestra si riempie. Questo interruttore sospende quei freni per una finestra sola, quando ti serve che il team spinga adesso.",
	"burn.desc_measured": "Non promette di consumare tutto: la notte in cui è nata questa funzione, con tutte le deroghe attive il consumo si è fermato fra il 6% e il 19% della finestra. Cercare offerte e analizzarle aspetta soprattutto la rete, non il modello, e togliere le pause non lo cambia. Serve perché il team obbedisca quando glielo chiedi.",
	"burn.state_off": "non attiva — il team si autoregola per far durare il budget",
	"burn.state_active": "attiva — scade fra %s",
	"burn.state_soon": "attiva — scade fra %s, poi il ritmo torna da solo",
	"burn.state_unknown": "stato non leggibile — il team non ha risposto",
	"burn.state_unsupported": "non disponibile — il container del team è più vecchio del gioco",
	"burn.left_h": "%s h",
	"burn.left_hm": "%s h %s min",
	"burn.left_m": "%s min",
	"burn.left_soon": "meno di un minuto",
	"burn.sending": "invio al team…",
	"burn.failed": "non riuscito — %s",
	"burn.confirm_title": "Attivare la spinta massima?",
	"burn.confirm_body": "Il team smette di rallentare da solo per far durare il budget: niente stop giornaliero, niente pausa fuori orario, niente ritmo ridotto quando la finestra si riempie.\n\n• Si spegne da sola dopo %s ore — il massimo consentito è %s: non esiste la forma permanente e non resta accesa per dimenticanza.\n\n• Quattro freni non cedono comunque: %s. Non sono economie — oltre il limite settimanale il provider smette di rispondere, e oltre il tetto di memoria la macchina rallenta tutto. Forzarli darebbe meno lavoro, non di più.\n\n• La sorveglianza passa al Coordinatore: senza i freni automatici è lui che deve fermare un agente che consuma senza produrre. Puoi revocare quando vuoi dallo stesso interruttore.",
	"burn.confirm_ok": "Attiva per %s ore",

	# ── Aggiornamento dell'applicazione ───────────────────────────
	"update.available": "○ DISPONIBILE LA VERSIONE %s · STAI USANDO LA %s",
	"update.install": "SCARICA E INSTALLA",
	"update.open_page": "APRI LA PAGINA DELLA RELEASE",
	"update.later": "PIÙ TARDI",
	"update.downloading": "SCARICAMENTO IN CORSO · %d%%",
	"update.installing": "VERIFICA DELLA FIRMA APPLE E INSTALLAZIONE…",
	"update.installed": "○ VERSIONE %s INSTALLATA · RIAVVIA PER USARLA",
	"update.restart": "RIAVVIA ADESSO",
	"update.failed": "AGGIORNAMENTO NON RIUSCITO · %s",
	"update.err_download": "il pacchetto non è stato scaricato",
	"update.err_extract": "l'archivio non si è aperto",
	"update.err_signature": "la firma del pacchetto non è valida",
	"update.err_identity": "il pacchetto è firmato da qualcun altro",
	"update.err_start": "la versione nuova non si avvia: è rimasta quella di prima",
	"update.err_swap": "la sostituzione non è riuscita: è rimasta quella di prima",
	"update.err_write": "non ho i permessi per scrivere dov'è installato il gioco",
	"update.section": "AGGIORNAMENTI",
	"update.auto": "Controlla se esiste una versione più recente",
	"update.auto_hint": "Un controllo al giorno, all'avvio: il gioco chiede a GitHub qual è l'ultima release e non manda nessun dato. Con l'interruttore spento non viene contattata nessuna rete.",
	"update.check_now": "CONTROLLA ADESSO",
	"update.checking": "Controllo in corso…",
	"update.current": "Nessun aggiornamento: la %s è l'ultima versione.",
	"update.never": "Mai controllato.",
	"update.last": "Ultimo controllo: %s.",
	"update.signed": "Il pacchetto macOS è firmato e notarizzato da Apple. Il gioco verifica firma, notarizzazione e identità dello sviluppatore — e prova che la versione nuova si avvia — prima di sostituire qualsiasi cosa.",
	"update.manual_only": "Il pacchetto per questo sistema non è firmato: l'aggiornamento apre la pagina della release e l'installazione resta nelle tue mani.",

	# ── Onboarding scriptato e console incorporata ────────────────
	# migrate da _tr(it, en) e dai letterali (GAME-ONBOARDING-NOT-LOCALIZED)
	"onb.skip.runtime": "Lo spazio di lavoro della squadra è già pronto su questo computer: salto il passaggio.",
	"onb.skip.provider": "Vedo che un servizio di intelligenza è già collegato su questo computer: tengo quello e andiamo avanti. Potrai cambiarlo quando vuoi da Provider.",
	"onb.opening.assistente": "Ciao, sono l'Assistente. Vorrei conoscerti un po', così tutto l'ufficio saprà quali lavori cercare per te. Ti farò domande brevi e potrai correggere ogni risposta dalla pagina Profilo.",
	"onb.opening.coordinatore": "Benvenuto in ufficio. Io sono il Coordinatore: preparo la casa della squadra, collego gli strumenti di cui ha bisogno e faccio partire il lavoro. Ti accompagno io, un passo alla volta.",
	"onb.opening.mentor": "Io sono il Mentor. Prima che il team parta voglio capire che tipo di ricerca vuoi: prudente, equilibrata o ambiziosa. Sono preferenze, non vincoli permanenti.",
	"onb.a.intro.start": "Iniziamo dal mio obiettivo",
	"onb.a.intro.profile": "Preferisco compilare il profilo completo",
	"onb.a.intro.later": "Prima voglio esplorare l'ufficio",
	"onb.a.role.software": "Software / engineering",
	"onb.a.role.data": "Data / AI",
	"onb.a.role.product": "Product / project management",
	"onb.a.role.design": "Design / UX / ricerca utente",
	"onb.a.role.business": "Sales / marketing / operations",
	"onb.a.role.security": "Cybersecurity / infrastruttura",
	"onb.a.role.other": "Un altro ambito o più ruoli",
	"onb.a.spec.sw.backend": "Backend / API / sistemi distribuiti",
	"onb.a.spec.sw.frontend": "Frontend / mobile / UI engineering",
	"onb.a.spec.sw.fullstack": "Full-stack",
	"onb.a.spec.sw.platform": "Platform / DevOps / cloud",
	"onb.a.spec.sw.embedded": "Embedded / robotics / hardware",
	"onb.a.spec.sw.open": "Più specializzazioni",
	"onb.a.spec.data.data_science": "Data science / analytics",
	"onb.a.spec.data.ml": "Machine learning / applied AI",
	"onb.a.spec.data.genai": "LLM / generative AI / agenti",
	"onb.a.spec.data.data_engineering": "Data engineering / BI",
	"onb.a.spec.data.research": "Ricerca AI",
	"onb.a.spec.data.open": "Sono aperto/a a più aree",
	"onb.a.spec.pm.product": "Product management",
	"onb.a.spec.pm.project": "Project / program management",
	"onb.a.spec.pm.technical_pm": "Technical product management",
	"onb.a.spec.pm.delivery": "Delivery / agile / operations",
	"onb.a.spec.pm.founder": "Product leadership / founder's office",
	"onb.a.spec.gen.specialist": "Voglio restare specialista",
	"onb.a.spec.gen.generalist": "Preferisco un ruolo generalista",
	"onb.a.spec.gen.leadership": "Cerco responsabilità di leadership",
	"onb.a.spec.gen.individual": "Preferisco contribuire senza gestire persone",
	"onb.a.spec.gen.explore": "Voglio esplorare più direzioni",
	"onb.a.status.employed": "Lavoro già e cerco senza urgenza",
	"onb.a.status.active": "Lavoro già, ma voglio cambiare presto",
	"onb.a.status.available": "Sono disponibile da subito",
	"onb.a.status.graduate": "Studio o mi sono appena laureato/a",
	"onb.a.status.freelance": "Sono freelance o consulente",
	"onb.a.status.returning": "Rientro dopo una pausa",
	"onb.a.exp.entry": "Nessuna esperienza professionale",
	"onb.a.exp.junior": "Meno di 2 anni",
	"onb.a.exp.mid": "Tra 2 e 5 anni",
	"onb.a.exp.senior": "Tra 5 e 10 anni",
	"onb.a.exp.lead": "Più di 10 anni / leadership",
	"onb.a.exp.career": "Sto cambiando carriera",
	"onb.a.conf.exact": "Voglio restare molto vicino alle mie competenze",
	"onb.a.conf.adjacent": "Va bene un ruolo adiacente con qualcosa da imparare",
	"onb.a.conf.stretch": "Accetto ruoli sfidanti anche se non copro tutto",
	"onb.a.conf.retrain": "Sono disposto/a a riqualificarmi seriamente",
	"onb.a.conf.discover": "Non lo so ancora: aiutami a scoprirlo",
	"onb.a.mode.remote": "Solo remoto",
	"onb.a.mode.remote_first": "Preferisco remoto, ma valuto ibrido",
	"onb.a.mode.hybrid": "Preferisco ibrido",
	"onb.a.mode.onsite": "Preferisco in presenza",
	"onb.a.mode.flexible": "Sono flessibile",
	"onb.a.where.local": "Solo vicino a dove vivo",
	"onb.a.where.italy": "Tutta Italia",
	"onb.a.where.eu": "Unione Europea / SEE",
	"onb.a.where.europe": "Europa, anche fuori UE",
	"onb.a.where.worldwide": "Tutto il mondo",
	"onb.a.where.remote_only": "Solo opportunità remote",
	"onb.a.reloc.never": "Non voglio trasferirmi",
	"onb.a.reloc.same_country": "Solo nella mia nazione",
	"onb.a.reloc.eu": "Sì, all'interno dell'Europa",
	"onb.a.reloc.worldwide": "Sì, anche fuori Europa",
	"onb.a.reloc.sponsored": "Solo con visto e relocation pagati",
	"onb.a.reloc.depends": "Dipende dall'opportunità",
	"onb.a.contract.employee": "Solo assunzione da dipendente",
	"onb.a.contract.permanent": "Preferisco indeterminato, valuto altro",
	"onb.a.contract.contractor": "Preferisco contractor / partita IVA",
	"onb.a.contract.freelance": "Cerco progetti freelance",
	"onb.a.contract.internship": "Valuto stage o apprendistato",
	"onb.a.contract.any": "Il tipo di contratto è secondario",
	"onb.a.salary.hard_floor": "Ho una soglia minima non negoziabile",
	"onb.a.salary.improve": "Voglio migliorare la retribuzione attuale",
	"onb.a.salary.market": "Cerco una retribuzione in linea col mercato",
	"onb.a.salary.equity": "Valuto molto equity e bonus",
	"onb.a.salary.secondary": "Per ora stipendio secondario",
	"onb.a.salary.unknown": "Non so ancora quale cifra chiedere",
	"onb.a.company.startup": "Startup piccola e veloce",
	"onb.a.company.scaleup": "Scale-up in crescita",
	"onb.a.company.established": "Azienda strutturata",
	"onb.a.company.enterprise": "Grande impresa / multinazionale",
	"onb.a.company.public": "Pubblico, ricerca o non-profit",
	"onb.a.company.any": "Nessuna preferenza: conta il ruolo",
	"onb.a.finish.complete_profile": "Completo ora i dati personali",
	"onb.a.finish.coordinator": "Passo al Coordinatore",
	"onb.a.finish.mentor": "Prima definisco la strategia col Mentor",
	"onb.a.intro.reply_profile": "Perfetto. Ti apro la scheda personale: puoi compilarla con calma e le informazioni restano nel tuo ufficio.",
	"onb.a.intro.reply_later": "Va benissimo. Torna da me quando vuoi: nessuna scelta viene persa e il setup non blocca l'ufficio.",
	"onb.a.intro.reply_start": "Che famiglia di ruolo descrive meglio ciò che cerchi?",
	"onb.a.role.reply": "Ottimo. Dentro quest'area, quale direzione ti somiglia di più?",
	"onb.a.specialty.reply": "Ora inquadriamo il livello: quanta esperienza professionale porti con te?",
	"onb.a.exp.reply": "E qual è la tua situazione adesso? Cambia molto il ritmo con cui il team deve cercare.",
	"onb.a.status.reply": "Quanto vuoi che esploriamo anche lavori per cui non sembri perfetto sulla carta?",
	"onb.a.conf.reply": "Come preferisci lavorare nella quotidianità?",
	"onb.a.mode.reply": "In quali luoghi vuoi che il reparto Ricerca cerchi per cominciare? Potrai cambiare idea quando vuoi.",
	"onb.a.where.reply": "Per una posizione davvero giusta, quanto sei disponibile a trasferirti?",
	"onb.a.reloc.reply": "Quale rapporto di lavoro vuoi privilegiare?",
	"onb.a.contract.reply": "Che peso deve avere la retribuzione nella selezione? La cifra esatta potrai metterla nel Profilo.",
	"onb.a.salary.reply": "In quale tipo di organizzazione pensi di rendere meglio?",
	"onb.a.finish.reply": "Adesso l'ufficio ti conosce già un po' meglio. Quando avremo collegato la sua intelligenza, qui potrai anche scrivermi liberamente.",
	"onb.a.finish.part_remote": "terrò il perimetro remoto molto rigido",
	"onb.a.finish.part_sponsor": "filtrerò subito visto e relocation",
	"onb.a.finish.part_stretch": "il reparto Compatibilità considererà anche lavori in cui puoi crescere",
	"onb.a.finish.part_exact": "il reparto Compatibilità resterà vicino a ciò che sai già fare bene",
	"onb.a.finish.part_fast": "la ricerca partirà con un ritmo sostenuto",
	"onb.a.finish.part_quality": "privilegeremo qualità e discrezione rispetto al volume",
	"onb.a.finish.part_default": "useremo queste preferenze per scegliere e spiegare ogni opportunità",
	"onb.a.finish.summary": "Ho preparato un profilo su misura: %s. Nella scheda personale puoi aggiungere nome, contatti, lingue, competenze e cifre esatte.",
	"onb.c.intro.local": "Il team lavorerà su questo computer",
	"onb.c.intro.vps": "Il team lavorerà su un computer online sempre acceso",
	"onb.c.intro.explain": "Spiegami la differenza",
	"onb.c.runtime.start": "Prepara o controlla lo spazio di lavoro",
	"onb.c.runtime.repair": "Installa o ripara lo spazio di lavoro",
	"onb.c.runtime.ready": "Lo spazio di lavoro è già pronto",
	"onb.c.provider.codex": "Codex con ChatGPT",
	"onb.c.provider.claude": "Claude Code",
	"onb.c.provider.kimi": "Kimi",
	"onb.c.provider.compare": "Aiutami a scegliere",
	"onb.c.login.login": "Apri il login nell'app",
	"onb.c.login.different": "Scelgo un altro provider",
	"onb.c.login.check": "Ho completato il login: ricontrolla",
	"onb.c.profile.open_profile": "Completa o verifica il profilo",
	"onb.c.profile.already": "Il profilo è già completo",
	"onb.c.autonomy.review_all": "Voglio approvare ogni candidatura",
	"onb.c.autonomy.review_cv": "Prepara tutto, ma fammi approvare i documenti",
	"onb.c.autonomy.high_score": "Procedi da solo soltanto con le occasioni migliori",
	"onb.c.autonomy.autonomous": "Automatizza il più possibile",
	"onb.c.autonomy.observe": "Per ora osserva e non eseguire azioni esterne",
	"onb.c.budget.minimal": "Risparmio massimo: fate soltanto l'essenziale",
	"onb.c.budget.careful": "Risparmioso: qualità dove conta",
	"onb.c.budget.balanced": "Bilanciato",
	"onb.c.budget.quality": "Privilegia la qualità",
	"onb.c.budget.unrestricted": "Nessun limite finché produce valore",
	"onb.c.privacy.strict": "Minimizza sempre i dati condivisi",
	"onb.c.privacy.cv_only": "Usa solo ciò che compare nel CV",
	"onb.c.privacy.contextual": "Usa i miei dati quando sono pertinenti",
	"onb.c.privacy.ask_sensitive": "Chiedimi conferma per dati sensibili",
	"onb.c.privacy.standard": "Impostazioni standard",
	"onb.c.availability.office": "Solo in orario lavorativo",
	"onb.c.availability.evenings": "Soprattutto sera e weekend",
	"onb.c.availability.always": "Può lavorare 24/7",
	"onb.c.availability.manual": "Solo quando lo avvio io",
	"onb.c.availability.custom": "Configuro orari personalizzati",
	"onb.c.channels.telegram": "Ricevi gli aggiornamenti su Telegram",
	"onb.c.channels.email": "Fai controllare una casella per gli avvisi di lavoro",
	"onb.c.channels.cloud": "Collega uno spazio online opzionale",
	"onb.c.channels.skip_channels": "Per ora continuo senza canali opzionali",
	"onb.c.team.start_team": "Attiva il team",
	"onb.c.team.overview": "Mostrami la checklist",
	"onb.c.team.mentor": "Prima parlo con il Mentor",
	"onb.c.team.review": "Rivediamo le mie impostazioni operative",
	"onb.c.intro.reply_explain": "Su questo computer è più semplice e la squadra riposa quando lo spegni. Un computer online resta acceso anche mentre sei lontano. In entrambi i casi le chiavi dell'ufficio restano nelle tue mani.",
	"onb.c.intro.reply_vps": "Ti apro la configurazione del computer online. La procedura ti chiederà dove si trova e come accedervi, spiegandoti ogni passaggio. Poi torniamo qui.",
	"onb.c.intro.reply_local": "Partiamo preparando uno spazio di lavoro riservato alla squadra su questo computer. Posso controllarlo o guidarti nell'installazione.",
	"onb.c.runtime.reply_start": "Controllo avviato. Lo stato in alto si aggiornerà da solo; intanto scegliamo quale intelligenza assisterà la squadra.",
	"onb.c.runtime.reply_repair": "Ho aperto qui dentro l'installazione guidata. Segui i passaggi e poi torna da me.",
	"onb.c.runtime.reply_ready": "Ricevuto. Scegli ora quale servizio assisterà la squadra nel suo lavoro.",
	"onb.c.provider.reply_compare": "Codex è la scelta più collaudata, Claude è apprezzato per la precisione e Kimi tende a essere più economico. Puoi usare il servizio a cui sei già abbonato e cambiare idea in seguito.",
	"onb.c.provider.reply_chosen": "Scelta registrata. Il collegamento avverrà qui dentro; il browser si aprirà soltanto per confermare il tuo abbonamento.",
	"onb.c.login.reply_different": "Va bene, scegliamo di nuovo.",
	"onb.c.login.reply_no_container": "Prima dobbiamo preparare lo spazio di lavoro della squadra. Ti apro la pagina giusta.",
	"onb.c.login.reply_opened": "Segui le istruzioni che compaiono qui dentro. Quando hai terminato, torna da me e chiedimi di controllare.",
	"onb.c.login.reply_check": "Verifica avviata. Ora completiamo il Profilo, così ogni reparto saprà per chi sta lavorando.",
	"onb.c.profile.reply": "Ora decidiamo quanta autonomia dare alla squadra. Le azioni esterne restano sempre tracciabili.",
	"onb.c.autonomy.reply": "Quanto vuoi che l'ufficio risparmi? Più prudenza significa meno lavoro superfluo; più libertà significa più approfondimenti.",
	"onb.c.budget.reply": "Quale regola sulla riservatezza devo far rispettare a tutti i colleghi?",
	"onb.c.privacy.reply": "In quali orari vuoi che l'ufficio lavori e quando preferisci non essere disturbato?",
	"onb.c.channels.reply_skip": "Nessun problema: Telegram, email e cloud restano configurabili in qualsiasi momento.",
	"onb.c.channels.reply_open": "Ho aperto la configurazione. Quando hai finito, torna in questa conversazione: le altre opzioni resteranno qui.",
	"onb.c.team.reply_start": "L'ufficio sta aprendo. Vedrai i colleghi raggiungere le loro scrivanie man mano che prendono servizio.",
	"onb.c.team.reply_missing": "Manca ancora almeno un requisito. Apro la checklist, così vediamo esattamente quale.",
	"onb.c.team.reply_review": "Ripartiamo dal livello di autonomia. Le nuove risposte sostituiranno le preferenze precedenti.",
	"onb.c.policy.manual": "approvazione manuale",
	"onb.c.policy.review_cv": "preparazione automatica con approvazione dei documenti",
	"onb.c.policy.high_score": "iniziativa riservata alle opportunità migliori",
	"onb.c.policy.autonomous": "autonomia estesa e tracciata",
	"onb.c.policy.observe": "sola osservazione, nessuna azione esterna",
	"onb.c.policy.summary": "Regole dell'ufficio registrate: %s; livello di risparmio %s; riservatezza %s. Ora scegliamo se collegare un modo opzionale per ricevere aggiornamenti.",
	"onb.m.intro.stability": "Priorità alla stabilità",
	"onb.m.intro.growth": "Priorità alla crescita",
	"onb.m.intro.salary": "Priorità alla retribuzione",
	"onb.m.intro.balance": "Priorità all'equilibrio",
	"onb.m.intro.meaning": "Priorità all'impatto e al significato",
	"onb.m.intro.learning": "Priorità all'apprendimento",
	"onb.m.intro.reentry": "Priorità a rientrare nel mercato",
	"onb.m.motivation.escape": "Voglio uscire da una situazione che non mi fa stare bene",
	"onb.m.motivation.plateau": "Mi sento fermo/a e voglio crescere",
	"onb.m.motivation.layoff": "Ho perso il lavoro o temo di perderlo",
	"onb.m.motivation.curious": "Sto bene, ma voglio capire cosa offre il mercato",
	"onb.m.motivation.life_change": "È cambiata la mia vita e il lavoro deve adattarsi",
	"onb.m.motivation.first_job": "Cerco il mio primo vero ingresso",
	"onb.m.style.cautious": "Poche opportunità, molto selezionate",
	"onb.m.style.balanced": "Un equilibrio tra qualità e scoperta",
	"onb.m.style.ambitious": "Mostrami anche opportunità sfidanti",
	"onb.m.style.volume": "Voglio esplorare un volume ampio",
	"onb.m.style.experimental": "Proviamo strade diverse e impariamo dai risultati",
	"onb.m.risk.very_low": "Evitiamo rischi: requisiti quasi perfetti",
	"onb.m.risk.low": "Qualche scommessa, ma motivata",
	"onb.m.risk.medium": "Metà match solidi, metà opportunità ambiziose",
	"onb.m.risk.high": "Preferisco puntare in alto",
	"onb.m.risk.adaptive": "Adatta il rischio ai risultati",
	"onb.m.pace.gentle": "Ritmo leggero, senza pressione",
	"onb.m.pace.steady": "Costante ogni settimana",
	"onb.m.pace.intensive": "Ricerca intensa per poche settimane",
	"onb.m.pace.urgent": "Massima urgenza",
	"onb.m.pace.adaptive": "Adatta il ritmo alle opportunità",
	"onb.m.tone.gentle": "Empatico e incoraggiante",
	"onb.m.tone.direct": "Diretto, senza giri di parole",
	"onb.m.tone.analytical": "Analitico, con dati e motivazioni",
	"onb.m.tone.challenging": "Sfidami quando mi sto limitando",
	"onb.m.tone.brief": "Molto sintetico",
	"onb.m.feedback.daily": "Un riepilogo breve ogni giorno",
	"onb.m.feedback.twice_week": "Due aggiornamenti alla settimana",
	"onb.m.feedback.weekly": "Un punto strategico settimanale",
	"onb.m.feedback.milestones": "Scrivimi solo per decisioni importanti",
	"onb.m.feedback.on_demand": "Solo quando lo chiedo io",
	"onb.m.dealbreakers.culture": "Ambiente tossico o valori incompatibili",
	"onb.m.dealbreakers.hours": "Straordinari e reperibilità frequenti",
	"onb.m.dealbreakers.commute": "Pendolarismo o presenza eccessiva",
	"onb.m.dealbreakers.instability": "Contratto o azienda troppo instabili",
	"onb.m.dealbreakers.ethics": "Settori o prodotti che non condivido",
	"onb.m.dealbreakers.none": "Nessun veto generale: valuto caso per caso",
	"onb.m.finish.done": "Confermo queste preferenze",
	"onb.m.finish.hours": "Configura gli orari del team",
	"onb.m.finish.restart": "Voglio ricominciare",
	"onb.m.finish.assistant": "Torno dall'Assistente",
	"onb.m.intro.reply": "Capito. Qual è la ragione più vera per cui stai cercando adesso?",
	"onb.m.motivation.reply": "Quanto vuoi che il team allarghi il campo oltre il match più ovvio?",
	"onb.m.style.reply": "Quanta incertezza sei disposto/a ad accettare per una possibilità migliore?",
	"onb.m.risk.reply": "Che ritmo vuoi sostenere senza bruciarti?",
	"onb.m.pace.reply": "Come vuoi che ti parli quando vedo un problema o un'occasione?",
	"onb.m.tone.reply": "Con quale frequenza vuoi un mio intervento?",
	"onb.m.feedback.reply": "Ultima domanda sostanziale: quale segnale deve farmi scartare subito una posizione?",
	"onb.m.finish.reply_hours": "Gli orari dicono alla squadra quando lavorare e quando lasciarti in pace. Torna qui dopo averli salvati.",
	"onb.m.finish.reply_done": "Ho preso nota. Quando l'ufficio sarà al lavoro, potremo continuare questa conversazione liberamente ogni volta che ne avrai bisogno.",
	"onb.m.finish.summary": "La tua bussola ora è chiara: priorità %s, ricerca %s, rischio %s e ritmo %s. Il veto principale resta %s. Non è una gabbia: se i risultati raccontano altro, te lo dirò.",
	"term.title_login": "LOGIN %s",
	"term.status_starting": "● AVVIO CONSOLE…",
	"term.preparing": "Preparazione del terminale interattivo…",
	"term.truncated": "… output precedente omesso …",
	"term.url_label": "LINK RILEVATO",
	"term.open_browser": "APRI NEL BROWSER",
	"term.copy_link": "COPIA LINK",
	"term.copy_all": "COPIA TESTO",
	"term.copy_all_tip": "Copia tutto l'output della console",
	"term.copied": "COPIATO ✓",
	"term.paste": "INCOLLA",
	"term.input_hint": "Incolla qui il codice di verifica e premi Invio",
	"term.login_cmd_tip": "Manda %s alla console e avvia il login",
	"term.key_enter": "INVIO",
	"term.done_login": "HO COMPLETATO IL LOGIN",
	"term.done_plain": "CHIUDI CONSOLE",
	"term.done_success": "COMPLETATO · CHIUDI",
	"term.close_retry": "CHIUDI E RIPROVA",
	"term.err_start": "Impossibile avviare la console interna",
	"term.status_interactive": "● CONSOLE INTERATTIVA",
	"term.status_error": "● ERRORE",
	"term.status_login_done": "● LOGIN TERMINATO",
	"term.status_cmd_done": "● COMANDO TERMINATO",
	"term.status_cmd_failed": "● COMANDO FALLITO (CODICE %d)",
	"term.status_closed": "● PROCESSO CHIUSO (%d)",
	"term.command_failed": "[JHT] Il comando non è stato completato. Leggi l'errore sopra, chiudi la console e riprova.",
	"term.runtime_install_failed": "[JHT] Il runtime non è stato installato. Leggi l'errore sopra, chiudi questa console e usa INSTALLA / RIPARA RUNTIME per riprovare.",
	"term.verifying": "VERIFICO IL LOGIN…",
	"term.status_not_detected": "● LOGIN NON ANCORA RILEVATO",
	"term.auth_not_found": "[JHT] Non trovo ancora le credenziali del provider. Se il login nel browser è andato a buon fine, lascia questa console aperta ancora qualche secondo: la spunta verde arriva da sola appena il CLI le salva.",
	"term.status_detected": "● LOGIN RILEVATO · CONFIGURAZIONE AGGIORNATA",
	"term.login_complete": "✓ LOGIN COMPLETATO",

	# ── Reparti e dati showroom ───────────────────────────────────
	"dept.scout.name": "Ricerca",
	"dept.scout.tagline": "Cercano sul web opportunità per te",
	"dept.analisti.name": "Analisi",
	"dept.analisti.tagline": "Studiano ogni opportunità nel dettaglio",
	"dept.scorer.name": "Compatibilità",
	"dept.scorer.tagline": "Capiscono quanto ogni lavoro fa per te",
	"dept.scrittori.name": "Candidature",
	"dept.scrittori.tagline": "Preparano CV e lettere su misura",
	"dept.critici.name": "Controllo qualità",
	"dept.critici.tagline": "Rileggono tutto prima della consegna",
	"dept.scout.positions_timeline": "POSIZIONI TROVATE · ULTIMI 7 GIORNI",
	"dept.agent_status.waiting": "IN ATTESA",
	"dept.agent_status.working": "AL LAVORO",
	"dept.agent_status.paused": "IN PAUSA",
	"dept.agent_status.resting": "RIPOSO",

	"dept.chatter.coordinatore.1": "controllo che tutti abbiano un incarico…",
	"dept.chatter.coordinatore.2": "il lavoro di oggi procede bene",
	"dept.chatter.coordinatore.3": "nessun reparto ha bisogno di aiuto",
	"dept.chatter.scout.1": "sto cercando nuove opportunità…",
	"dept.chatter.scout.2": "ho trovato tre aziende interessanti",
	"dept.chatter.scout.3": "questa azienda ha appena pubblicato un'offerta…",
	"dept.chatter.analista.1": "studio meglio questa opportunità…",
	"dept.chatter.analista.2": "qui mancano alcune informazioni",
	"dept.chatter.analista.3": "controllo dove si trova davvero la sede…",
	"dept.chatter.scorer.1": "confronto questa offerta con i suoi desideri…",
	"dept.chatter.scorer.2": "questa opportunità sembra promettente",
	"dept.chatter.scorer.3": "qui competenze e condizioni combaciano bene",
	"dept.chatter.scrittore.1": "questa candidatura merita un inizio migliore…",
	"dept.chatter.scrittore.2": "due righe in meno, il doppio del peso",
	"dept.chatter.scrittore.3": "su misura, mai fotocopie",
	"dept.chatter.critico.1": "questa frase non è abbastanza chiara: riscrivila",
	"dept.chatter.critico.2": "un refuso qui costa un colloquio",
	"dept.chatter.critico.3": "approvato. sorprendentemente.",
	"dept.chatter.mentor.1": "un buon colloquio è una conversazione",
	"dept.chatter.mentor.2": "i numeri raccontano i risultati",
	"dept.chatter.mentor.3": "respira: la ricerca è una maratona",
	"dept.chatter.assistente.1": "la presentazione dell'ufficio è completa",
	"dept.chatter.assistente.2": "se hai dubbi, chiedi pure a me",
	"dept.chatter.assistente.3": "tengo io il registro del team",
	"dept.chatter.mantenitore.1": "gli strumenti dell'ufficio sono in ordine",
	"dept.chatter.mantenitore.2": "preparo gli aggiornamenti…",
	"dept.chatter.mantenitore.3": "backup verificato, tutto al suo posto",
	"dept.chatter.dottore.1": "visita di controllo agli agenti…",
	"dept.chatter.dottore.2": "la squadra è in salute",
	"dept.chatter.dottore.3": "prescrivo una breve pausa e poi si riparte",
	"dept.chatter.sentinella.1": "ronda completata: tutto in ordine",
	"dept.chatter.sentinella.2": "l'ufficio lavora regolarmente",
	"dept.chatter.sentinella.3": "nessun problema durante il turno",

	"dept.mock.position.1.title": "Responsabile Comunicazione",
	"dept.mock.position.1.location": "Milano · ibrido",
	"dept.mock.position.1.note": "esperienze molto vicine al tuo CV",
	"dept.mock.position.2.title": "Specialista Marketing Digitale",
	"dept.mock.position.2.location": "Roma · remoto",
	"dept.mock.position.2.note": "ottimo team, trasferte da chiarire",
	"dept.mock.position.3.title": "Account Manager",
	"dept.mock.position.3.location": "Berlino · in sede",
	"dept.mock.position.3.note": "richiede tedesco B2",
	"dept.mock.status.coordinatore.status": "attivo",
	"dept.mock.status.coordinatore.detail": "pacing regolare, weekly al 64%",
	"dept.mock.status.scout.status": "in scansione",
	"dept.mock.status.scout.detail": "3 board visitate nell'ultima ora",
	"dept.mock.status.analista.status": "al lavoro",
	"dept.mock.status.analista.detail": "2 posizioni in verifica",
	"dept.mock.status.scorer.status": "in valutazione",
	"dept.mock.status.scorer.detail": "coda: 1 posizione",
	"dept.mock.status.mentor.status": "disponibile",
	"dept.mock.status.mentor.detail": "pronto a consigliarti",
	"dept.mock.status.assistente.status": "disponibile",
	"dept.mock.status.assistente.detail": "onboarding completato",
	"dept.mock.reason.1": "l'annuncio ricalca due esperienze già nel tuo CV",
	"dept.mock.reason.2": "la sede è in centro, vicino a una delle tue città prioritarie",
	"dept.mock.reason.3": "stipendio sopra la soglia che hai indicato",
	"dept.mock.reason.4": "-8 punti: chiedono disponibilità anche nel weekend",
	"dept.mock.mentor_tip": "Nei colloqui, racconta i risultati con i numeri: non «ho migliorato le cose», ma «ho ridotto i tempi di attesa del 40%».",
	"dept.mock.notification.1": "Nuova posizione sopra soglia: Frontend Engineer @ Lumon (85)",
	"dept.mock.notification.2": "Quota settimanale al 64%: pacing regolare",
	"dept.mock.notification.3": "CV approvato dal Critico per Data Analyst",
	"dept.mock.notification.4": "Candidatura passata allo stadio colloquio",
	"dept.mock.chat.1": "buongiorno team, weekly al 64%: ritmo buono",
	"dept.mock.chat.2": "2 annunci nuovi da Berlino, li passo agli analisti",
	"dept.mock.chat.3": "range salariale verificato su fonte doppia",
	"dept.mock.chat.4": "score 85 su Lumon: sopra soglia, notifica inviata",
	"dept.mock.chat.5": "CV ok dopo due giri: si spedisce",
	"dept.demo.score_notes": "Valutazione fittizia per mostrare la composizione dello score.",
	"dept.demo.jd_summary": "%s cerca una persona per il ruolo di %s a %s. Questa scheda è un esempio fittizio: mostra responsabilità, requisiti, modalità di lavoro e fascia retributiva senza utilizzare dati reali.",
	"dept.demo.highlight.collaboration": "Collaborazione con un team multidisciplinare",
	"dept.demo.highlight.growth": "Obiettivi chiari e percorso di crescita verificabile",
	"dept.demo.highlight.work_mode": "Modalità %s con orari sostenibili",
}
