// [JHT-WEB-DEMO] Dataset statico per la modalità demo dell'area riservata
// cloud (onboarding utenti nuovi, 22/07). Quattro "personas" — una per
// categoria di lavoro scelta nel wizard /welcome — ognuna con ~26 posizioni
// complete di tutti i campi consumati da dashboard, /positions (lista +
// dettaglio), /map (globo + tree località) e /swipe. Nessuna riga tocca il
// database: i dati vivono qui e le query li servono quando il cookie
// jht_demo_persona è attivo (vedi lib/demo/mode.ts + hook in lib/queries.ts).
// Gli annunci sono volutamente in inglese (come gli annunci reali); l'UI
// intorno resta localizzata.
import type {
  Position,
  PositionHighlight,
  PositionStatus,
  Score,
} from "@/lib/types";

export type DemoPersonaKey = "software" | "marketing" | "finance" | "design";

export const DEMO_PERSONA_KEYS: DemoPersonaKey[] = [
  "software",
  "marketing",
  "finance",
  "design",
];

export function isDemoPersonaKey(v: unknown): v is DemoPersonaKey {
  return (
    typeof v === "string" && DEMO_PERSONA_KEYS.includes(v as DemoPersonaKey)
  );
}

// Riconoscimento id demo nelle API route: le posizioni demo hanno id
// "demo-<persona>-NNN" e legacy_id nel range 9000-9399.
export function isDemoPositionId(id: string): boolean {
  return id.startsWith("demo-");
}
export function isDemoLegacyId(legacyId: number | string): boolean {
  const n = typeof legacyId === "string" ? Number(legacyId) : legacyId;
  return Number.isFinite(n) && n >= 9000 && n < 9400;
}

type City = {
  city: string;
  country: string;
  cc: string;
  lat: number;
  lon: number;
};

const CITIES = {
  milano: {
    city: "Milano",
    country: "Italy",
    cc: "IT",
    lat: 45.4642,
    lon: 9.19,
  },
  roma: {
    city: "Roma",
    country: "Italy",
    cc: "IT",
    lat: 41.9028,
    lon: 12.4964,
  },
  torino: {
    city: "Torino",
    country: "Italy",
    cc: "IT",
    lat: 45.0703,
    lon: 7.6869,
  },
  bologna: {
    city: "Bologna",
    country: "Italy",
    cc: "IT",
    lat: 44.4949,
    lon: 11.3426,
  },
  firenze: {
    city: "Firenze",
    country: "Italy",
    cc: "IT",
    lat: 43.7696,
    lon: 11.2558,
  },
  berlin: {
    city: "Berlin",
    country: "Germany",
    cc: "DE",
    lat: 52.52,
    lon: 13.405,
  },
  munich: {
    city: "Munich",
    country: "Germany",
    cc: "DE",
    lat: 48.1351,
    lon: 11.582,
  },
  hamburg: {
    city: "Hamburg",
    country: "Germany",
    cc: "DE",
    lat: 53.5511,
    lon: 9.9937,
  },
  amsterdam: {
    city: "Amsterdam",
    country: "Netherlands",
    cc: "NL",
    lat: 52.3676,
    lon: 4.9041,
  },
  paris: {
    city: "Paris",
    country: "France",
    cc: "FR",
    lat: 48.8566,
    lon: 2.3522,
  },
  barcelona: {
    city: "Barcelona",
    country: "Spain",
    cc: "ES",
    lat: 41.3874,
    lon: 2.1686,
  },
  madrid: {
    city: "Madrid",
    country: "Spain",
    cc: "ES",
    lat: 40.4168,
    lon: -3.7038,
  },
  london: {
    city: "London",
    country: "United Kingdom",
    cc: "GB",
    lat: 51.5074,
    lon: -0.1278,
  },
  dublin: {
    city: "Dublin",
    country: "Ireland",
    cc: "IE",
    lat: 53.3498,
    lon: -6.2603,
  },
  zurich: {
    city: "Zurich",
    country: "Switzerland",
    cc: "CH",
    lat: 47.3769,
    lon: 8.5417,
  },
  vienna: {
    city: "Vienna",
    country: "Austria",
    cc: "AT",
    lat: 48.2082,
    lon: 16.3738,
  },
  lisbon: {
    city: "Lisbon",
    country: "Portugal",
    cc: "PT",
    lat: 38.7223,
    lon: -9.1393,
  },
  copenhagen: {
    city: "Copenhagen",
    country: "Denmark",
    cc: "DK",
    lat: 55.6761,
    lon: 12.5683,
  },
  stockholm: {
    city: "Stockholm",
    country: "Sweden",
    cc: "SE",
    lat: 59.3293,
    lon: 18.0686,
  },
  prague: {
    city: "Prague",
    country: "Czechia",
    cc: "CZ",
    lat: 50.0755,
    lon: 14.4378,
  },
} satisfies Record<string, City>;

type CityKey = keyof typeof CITIES;

type Seed = {
  title: string;
  company: string;
  // assente = remote puro senza sede; "napoli_x" = città senza coordinate
  // note → entrambe finiscono nel bucket "senza coordinate" della mappa.
  city?: CityKey | "napoli_x";
  remote: NonNullable<Position["remote_type"]>;
  sal?: [number, number, string];
  source: string;
  status: PositionStatus;
  score?: number;
  family: string;
  h: number; // trovata N ore fa
  wr?: boolean; // write_requested (selezionata per il CV)
  critic?: [number, "PASS" | "NEEDS_WORK" | "REJECT"];
  jd?: string;
  req?: string[];
  pros?: string[];
  cons?: string[];
};

// ── Seed per persona ────────────────────────────────────────────────
// Distribuzione status per persona (26 posizioni): 3 new, 3 checked,
// 7 scored, 2 writing, 2 review, 4 ready, 2 applied, 1 response,
// 2 excluded — così ogni box della pipeline e ogni grafico ha dati.

const SOFTWARE: Seed[] = [
  {
    title: "Senior Frontend Engineer",
    company: "Northstar Labs",
    city: "berlin",
    remote: "full_remote",
    sal: [78000, 96000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 91,
    family: "Frontend",
    h: 6,
    critic: [8, "PASS"],
    jd: "Own the design system and the customer-facing React application of a Series-B analytics platform. You will work in a small product squad shipping weekly, with strong ownership of DX and performance budgets.",
    req: [
      "5+ years with React and TypeScript",
      "Experience with design systems at scale",
      "Solid grasp of web performance (CWV, profiling)",
      "English working proficiency",
    ],
    pros: [
      "Stack perfettamente allineato al profilo",
      "Full remote EU con raduni trimestrali",
      "Range salariale sopra la media di mercato",
    ],
    cons: ["On-call leggero una settimana al mese"],
  },
  {
    title: "Full Stack Product Engineer",
    company: "AtlasCare",
    city: "milano",
    remote: "hybrid",
    sal: [58000, 74000, "EUR"],
    source: "Wellfound",
    status: "ready",
    score: 84,
    family: "Full-stack",
    h: 12,
    critic: [7, "PASS"],
    jd: "Healthtech scale-up building patient-facing tools. End-to-end feature work across a Next.js frontend and a Node/Postgres backend, two days a week in the Milan office.",
    req: [
      "3+ years full-stack (Node + React)",
      "Postgres and API design",
      "Italian and English",
    ],
    pros: ["Prodotto con impatto concreto", "Ufficio a 20 minuti dal centro"],
    cons: ["Ibrido vincolante 2 giorni/settimana"],
  },
  {
    title: "Platform Engineer, Kubernetes",
    company: "GreenGrid",
    city: "amsterdam",
    remote: "full_remote",
    sal: [80000, 105000, "EUR"],
    source: "Otta",
    status: "ready",
    score: 88,
    family: "DevOps / Cloud",
    h: 20,
    critic: [8, "PASS"],
    jd: "Energy-tech company running a multi-tenant Kubernetes platform on AWS. You will own cluster lifecycle, observability and developer tooling for 60 engineers.",
    req: [
      "Production Kubernetes experience",
      "IaC (Terraform) and GitOps",
      "Golang or Python for tooling",
    ],
    pros: ["Team platform maturo, on-call pagato", "Budget formazione 3k/anno"],
    cons: ["Timezone spread ampio (UTC-5 → UTC+2)"],
  },
  {
    title: "Machine Learning Engineer",
    company: "SignalForge",
    remote: "full_remote",
    sal: [95000, 130000, "USD"],
    source: "Hacker News",
    status: "ready",
    score: 86,
    family: "AI / ML",
    h: 28,
    critic: [7, "PASS"],
    jd: "Applied ML on time-series anomaly detection for industrial IoT. Python, PyTorch, feature pipelines on Spark, model serving on K8s.",
    req: [
      "Strong Python + PyTorch",
      "Experience shipping models to production",
      "Comfort with data engineering",
    ],
    pros: [
      "Progetti ML end-to-end, non solo notebook",
      "Compenso in USD sopra range",
    ],
    cons: ["Colloqui in 5 step", "Azienda remota senza sede EU"],
  },
  {
    title: "Backend Engineer, Payments",
    company: "FinPilot",
    city: "amsterdam",
    remote: "hybrid",
    sal: [70000, 88000, "EUR"],
    source: "LinkedIn",
    status: "applied",
    score: 82,
    family: "Backend",
    h: 80,
    critic: [8, "PASS"],
    jd: "Payments infrastructure team. High-throughput services in Kotlin, event-driven architecture on Kafka, strict correctness culture.",
  },
  {
    title: "Software Engineer, Data Platform",
    company: "Mosaic Cloud",
    city: "paris",
    remote: "hybrid",
    sal: [68000, 85000, "EUR"],
    source: "Welcome to the Jungle",
    status: "applied",
    score: 79,
    family: "Data",
    h: 110,
    critic: [7, "PASS"],
    jd: "Build the ingestion and transformation layer of a customer data platform (Airflow, dbt, BigQuery).",
  },
  {
    title: "React Native Developer",
    company: "Loopway",
    city: "barcelona",
    remote: "full_remote",
    sal: [52000, 68000, "EUR"],
    source: "Wellfound",
    status: "response",
    score: 77,
    family: "Mobile",
    h: 160,
    critic: [7, "PASS"],
    jd: "Consumer mobility app with 2M MAU. React Native + TypeScript, native modules when needed.",
  },
  {
    title: "TypeScript Engineer, DX Tools",
    company: "Brightline",
    city: "london",
    remote: "full_remote",
    sal: [70000, 90000, "GBP"],
    source: "Otta",
    status: "writing",
    score: 85,
    family: "Frontend",
    h: 30,
    wr: true,
    jd: "Developer-experience team building internal CLIs and CI tooling used by 300 engineers.",
  },
  {
    title: "Site Reliability Engineer",
    company: "Nordwind",
    city: "stockholm",
    remote: "hybrid",
    sal: [62000, 80000, "EUR"],
    source: "LinkedIn",
    status: "writing",
    score: 74,
    family: "DevOps / Cloud",
    h: 44,
    wr: true,
  },
  {
    title: "Data Engineer",
    company: "Pipebase",
    remote: "full_remote",
    sal: [60000, 82000, "EUR"],
    source: "Company site",
    status: "review",
    score: 78,
    family: "Data",
    h: 52,
    jd: "ELT pipelines and data contracts for a B2B SaaS. dbt, Snowflake, Dagster.",
  },
  {
    title: "Fullstack Engineer, Growth",
    company: "NovaPay",
    city: "dublin",
    remote: "hybrid",
    sal: [72000, 92000, "EUR"],
    source: "Wellfound",
    status: "review",
    score: 81,
    family: "Full-stack",
    h: 60,
  },
  {
    title: "Backend Developer, Python",
    company: "Cargolane",
    city: "hamburg",
    remote: "hybrid",
    sal: [58000, 72000, "EUR"],
    source: "StepStone",
    status: "scored",
    score: 69,
    family: "Backend",
    h: 70,
    jd: "Logistics platform, Django + FastAPI services, PostgreSQL, event sourcing on selected domains.",
  },
  {
    title: "Frontend Developer, Vue",
    company: "MarketNest",
    city: "roma",
    remote: "onsite",
    sal: [40000, 52000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 55,
    family: "Frontend",
    h: 84,
  },
  {
    title: "DevOps Engineer, Azure",
    company: "Innsbruck Digital",
    city: "vienna",
    remote: "hybrid",
    sal: [55000, 70000, "EUR"],
    source: "StepStone",
    status: "scored",
    score: 63,
    family: "DevOps / Cloud",
    h: 96,
  },
  {
    title: "Software Engineer, Elixir",
    company: "Fluxwave",
    remote: "full_remote",
    sal: [65000, 85000, "EUR"],
    source: "Hacker News",
    status: "scored",
    score: 72,
    family: "Backend",
    h: 105,
  },
  {
    title: "Data Scientist, NLP",
    company: "Lexio AI",
    city: "munich",
    remote: "hybrid",
    sal: [70000, 90000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 76,
    family: "AI / ML",
    h: 120,
  },
  {
    title: "QA Automation Engineer",
    company: "Testardo",
    city: "torino",
    remote: "hybrid",
    sal: [42000, 55000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 58,
    family: "QA",
    h: 130,
  },
  {
    title: "iOS Engineer",
    company: "Snapdeck",
    city: "copenhagen",
    remote: "hybrid",
    sal: [68000, 84000, "EUR"],
    source: "Otta",
    status: "scored",
    score: 66,
    family: "Mobile",
    h: 140,
  },
  {
    title: "Junior Fullstack Developer",
    company: "Weblab Italia",
    city: "bologna",
    remote: "onsite",
    sal: [28000, 36000, "EUR"],
    source: "Indeed",
    status: "checked",
    family: "Full-stack",
    h: 150,
  },
  {
    title: "Cloud Architect",
    company: "Helvetia Systems",
    city: "zurich",
    remote: "hybrid",
    sal: [110000, 135000, "CHF"],
    source: "LinkedIn",
    status: "checked",
    family: "DevOps / Cloud",
    h: 155,
  },
  {
    title: "Rust Systems Engineer",
    company: "Kernelworks",
    remote: "full_remote",
    sal: [85000, 115000, "USD"],
    source: "Hacker News",
    status: "checked",
    family: "Backend",
    h: 165,
  },
  {
    title: "Frontend Engineer, Svelte",
    company: "Ostrava Tech",
    city: "prague",
    remote: "hybrid",
    sal: [38000, 50000, "EUR"],
    source: "Company site",
    status: "new",
    family: "Frontend",
    h: 175,
  },
  {
    title: "Solutions Engineer",
    company: "Databridge",
    city: "madrid",
    remote: "hybrid",
    sal: [45000, 60000, "EUR"],
    source: "LinkedIn",
    status: "new",
    family: "Data",
    h: 185,
  },
  {
    title: "Software Engineer, Golang",
    company: "Portico",
    city: "lisbon",
    remote: "full_remote",
    sal: [55000, 72000, "EUR"],
    source: "Wellfound",
    status: "new",
    family: "Backend",
    h: 190,
  },
  {
    title: "PHP Developer, Legacy Migration",
    company: "Old Mill Software",
    city: "firenze",
    remote: "onsite",
    sal: [30000, 38000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 31,
    family: "Backend",
    h: 200,
  },
  {
    title: "Wordpress Webmaster",
    company: "AgencyOne",
    city: "roma",
    remote: "onsite",
    sal: [24000, 30000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 22,
    family: "Frontend",
    h: 210,
  },
];

const MARKETING: Seed[] = [
  {
    title: "Growth Marketing Manager",
    company: "Northstar Labs",
    city: "berlin",
    remote: "full_remote",
    sal: [60000, 75000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 90,
    family: "Growth",
    h: 7,
    critic: [8, "PASS"],
    jd: "Own the full acquisition funnel of a B2B SaaS: paid, lifecycle, experiments. You will run a small squad with a designer and an analyst.",
    req: [
      "4+ years in growth/performance roles",
      "Hands-on with GA4, attribution, SQL basics",
      "Track record of experiment programs",
    ],
    pros: [
      "Budget esperimenti dedicato",
      "Full remote EU",
      "Percorso verso Head of Growth",
    ],
    cons: ["Reporting settimanale al board"],
  },
  {
    title: "Content Strategist, B2B",
    company: "AtlasCare",
    city: "milano",
    remote: "hybrid",
    sal: [42000, 54000, "EUR"],
    source: "Wellfound",
    status: "ready",
    score: 83,
    family: "Content",
    h: 14,
    critic: [7, "PASS"],
    jd: "Healthtech scale-up: editorial strategy, SEO content and thought leadership for clinical audiences.",
    req: [
      "Portfolio of long-form B2B content",
      "SEO fundamentals",
      "Italian mother tongue, English C1",
    ],
    pros: ["Team editoriale interno", "Tema ad alto impatto"],
    cons: ["Due giorni in ufficio a Milano"],
  },
  {
    title: "Performance Marketing Lead",
    company: "Loopway",
    city: "barcelona",
    remote: "full_remote",
    sal: [55000, 70000, "EUR"],
    source: "Otta",
    status: "ready",
    score: 86,
    family: "Performance Ads",
    h: 22,
    critic: [8, "PASS"],
    jd: "Consumer app with 2M MAU: own Meta/Google/TikTok budgets (~€400k/mo), creative testing pipeline and incrementality measurement.",
    req: [
      "Managed 6-figure monthly budgets",
      "Creative testing frameworks",
      "Incrementality / MMM exposure",
    ],
    pros: ["Budget importante e libertà creativa", "Bonus legato a CAC target"],
    cons: ["Pressione forte sui numeri trimestrali"],
  },
  {
    title: "CRM & Lifecycle Manager",
    company: "FinPilot",
    city: "amsterdam",
    remote: "hybrid",
    sal: [50000, 64000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 81,
    family: "CRM & Email",
    h: 30,
    critic: [7, "PASS"],
    jd: "Own Braze journeys, segmentation and retention KPIs for a fintech with 800k users.",
    req: [
      "Braze or Iterable hands-on",
      "Segmentation and A/B discipline",
      "SQL for audience building",
    ],
    pros: ["Stack CRM moderno", "Team data di supporto"],
    cons: ["Dominio regolamentato, approvazioni lente"],
  },
  {
    title: "Brand Marketing Manager",
    company: "Studio Relay",
    city: "firenze",
    remote: "hybrid",
    sal: [45000, 58000, "EUR"],
    source: "LinkedIn",
    status: "applied",
    score: 80,
    family: "Brand",
    h: 85,
    critic: [7, "PASS"],
    jd: "Design-led company: brand campaigns, partnerships and events across EU markets.",
  },
  {
    title: "Demand Generation Specialist",
    company: "Mosaic Cloud",
    city: "paris",
    remote: "hybrid",
    sal: [48000, 60000, "EUR"],
    source: "Welcome to the Jungle",
    status: "applied",
    score: 78,
    family: "Growth",
    h: 115,
    critic: [7, "PASS"],
  },
  {
    title: "Social Media Manager",
    company: "Snapdeck",
    city: "copenhagen",
    remote: "full_remote",
    sal: [40000, 52000, "EUR"],
    source: "Otta",
    status: "response",
    score: 75,
    family: "Content",
    h: 170,
    critic: [6, "PASS"],
  },
  {
    title: "SEO Manager",
    company: "Pipebase",
    remote: "full_remote",
    sal: [50000, 65000, "EUR"],
    source: "Company site",
    status: "writing",
    score: 84,
    family: "Content",
    h: 32,
    wr: true,
    jd: "B2B SaaS with strong inbound motion: technical SEO, programmatic pages, content ops.",
  },
  {
    title: "Marketing Automation Specialist",
    company: "NovaPay",
    city: "dublin",
    remote: "hybrid",
    sal: [45000, 58000, "EUR"],
    source: "Wellfound",
    status: "writing",
    score: 73,
    family: "CRM & Email",
    h: 46,
    wr: true,
  },
  {
    title: "Product Marketing Manager",
    company: "Brightline",
    city: "london",
    remote: "full_remote",
    sal: [55000, 72000, "GBP"],
    source: "Otta",
    status: "review",
    score: 82,
    family: "Product Marketing",
    h: 55,
    jd: "Positioning, launches and sales enablement for a dev-tools company.",
  },
  {
    title: "Event Marketing Manager",
    company: "Helvetia Systems",
    city: "zurich",
    remote: "hybrid",
    sal: [80000, 95000, "CHF"],
    source: "LinkedIn",
    status: "review",
    score: 77,
    family: "Brand",
    h: 62,
  },
  {
    title: "Paid Social Specialist",
    company: "MarketNest",
    city: "roma",
    remote: "hybrid",
    sal: [32000, 42000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 62,
    family: "Performance Ads",
    h: 72,
  },
  {
    title: "Copywriter, Tech",
    company: "Weblab Italia",
    city: "bologna",
    remote: "hybrid",
    sal: [28000, 36000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 57,
    family: "Content",
    h: 86,
  },
  {
    title: "Growth Analyst",
    company: "Cargolane",
    city: "hamburg",
    remote: "hybrid",
    sal: [45000, 56000, "EUR"],
    source: "StepStone",
    status: "scored",
    score: 68,
    family: "Growth",
    h: 98,
  },
  {
    title: "Email Marketing Specialist",
    company: "Fluxwave",
    remote: "full_remote",
    sal: [38000, 48000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 64,
    family: "CRM & Email",
    h: 106,
  },
  {
    title: "Influencer Marketing Manager",
    company: "Lexio AI",
    city: "munich",
    remote: "hybrid",
    sal: [48000, 60000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 66,
    family: "Brand",
    h: 122,
  },
  {
    title: "Community Manager",
    company: "Kernelworks",
    remote: "full_remote",
    sal: [40000, 55000, "USD"],
    source: "Hacker News",
    status: "scored",
    score: 59,
    family: "Content",
    h: 132,
  },
  {
    title: "Field Marketing Manager, Italy",
    company: "Databridge",
    city: "milano",
    remote: "hybrid",
    sal: [46000, 58000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 71,
    family: "Brand",
    h: 142,
  },
  {
    title: "Junior Marketing Specialist",
    company: "AgencyOne",
    city: "roma",
    remote: "onsite",
    sal: [24000, 30000, "EUR"],
    source: "Indeed",
    status: "checked",
    family: "Growth",
    h: 152,
  },
  {
    title: "Head of Marketing",
    company: "Portico",
    city: "lisbon",
    remote: "full_remote",
    sal: [70000, 90000, "EUR"],
    source: "Wellfound",
    status: "checked",
    family: "Growth",
    h: 158,
  },
  {
    title: "PR & Communications Manager",
    company: "Nordwind",
    city: "stockholm",
    remote: "hybrid",
    sal: [50000, 62000, "EUR"],
    source: "LinkedIn",
    status: "checked",
    family: "Brand",
    h: 166,
  },
  {
    title: "Marketing Operations Manager",
    company: "Ostrava Tech",
    city: "prague",
    remote: "hybrid",
    sal: [40000, 52000, "EUR"],
    source: "Company site",
    status: "new",
    family: "CRM & Email",
    h: 176,
  },
  {
    title: "Ecommerce Marketing Manager",
    company: "Old Mill Software",
    city: "madrid",
    remote: "hybrid",
    sal: [38000, 48000, "EUR"],
    source: "InfoJobs",
    status: "new",
    family: "Growth",
    h: 186,
  },
  {
    title: "Video Content Creator",
    company: "Testardo",
    city: "torino",
    remote: "hybrid",
    sal: [30000, 40000, "EUR"],
    source: "Indeed",
    status: "new",
    family: "Content",
    h: 192,
  },
  {
    title: "Door-to-door Sales Promoter",
    company: "PromoPlus",
    city: "napoli_x",
    remote: "onsite",
    sal: [18000, 24000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 18,
    family: "Sales",
    h: 202,
  },
  {
    title: "Telemarketing Operator",
    company: "CallItalia",
    city: "roma",
    remote: "onsite",
    sal: [20000, 25000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 24,
    family: "Sales",
    h: 212,
  },
];

const FINANCE: Seed[] = [
  {
    title: "Senior FP&A Analyst",
    company: "FinPilot",
    city: "amsterdam",
    remote: "hybrid",
    sal: [65000, 80000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 89,
    family: "FP&A",
    h: 8,
    critic: [8, "PASS"],
    jd: "Fintech scale-up: own the operating model, monthly forecast cycle and board reporting pack. Partner with product leads on unit economics.",
    req: [
      "4+ years FP&A in tech or consulting",
      "Advanced modelling (driver-based)",
      "SQL / BI tooling a plus",
    ],
    pros: [
      "Esposizione diretta al CFO",
      "Modello operativo moderno (no Excel-only)",
    ],
    cons: ["Ciclo di chiusura mensile intenso"],
  },
  {
    title: "Financial Controller",
    company: "AtlasCare",
    city: "milano",
    remote: "hybrid",
    sal: [55000, 68000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 84,
    family: "Accounting",
    h: 15,
    critic: [7, "PASS"],
    jd: "Healthtech scale-up: closing, IFRS reporting, audit coordination and ERP improvement (NetSuite).",
    req: [
      "IFRS closing experience",
      "NetSuite or similar ERP",
      "Italian + English",
    ],
    pros: ["Percorso verso Finance Manager", "Team giovane"],
    cons: ["Ibrido 2 giorni a Milano"],
  },
  {
    title: "Risk Analyst, Credit",
    company: "NovaPay",
    city: "dublin",
    remote: "hybrid",
    sal: [58000, 72000, "EUR"],
    source: "Wellfound",
    status: "ready",
    score: 86,
    family: "Risk & Audit",
    h: 24,
    critic: [8, "PASS"],
    jd: "Consumer lending risk team: scorecards, portfolio monitoring, provisioning models under IFRS 9.",
    req: ["Credit risk modelling", "Python or R", "IFRS 9 exposure"],
    pros: ["Team quantitativo forte", "Dataset ricco"],
    cons: ["Contesto regolamentato, ritmi audit"],
  },
  {
    title: "Business Analyst, Strategy",
    company: "Mosaic Cloud",
    city: "paris",
    remote: "hybrid",
    sal: [55000, 70000, "EUR"],
    source: "Welcome to the Jungle",
    status: "ready",
    score: 82,
    family: "Business Analysis",
    h: 32,
    critic: [7, "PASS"],
    jd: "Support the COO on pricing, market sizing and expansion cases across EU markets.",
    req: [
      "2-4 years consulting or BizOps",
      "Strong modelling and storytelling",
      "French is a plus",
    ],
    pros: ["Progetti trasversali C-level", "Crescita rapida"],
    cons: ["Trasferte mensili"],
  },
  {
    title: "Treasury Analyst",
    company: "Helvetia Systems",
    city: "zurich",
    remote: "hybrid",
    sal: [95000, 115000, "CHF"],
    source: "LinkedIn",
    status: "applied",
    score: 81,
    family: "Treasury",
    h: 88,
    critic: [7, "PASS"],
    jd: "Cash management, FX hedging and liquidity planning for a Swiss industrial group.",
  },
  {
    title: "Internal Auditor",
    company: "Cargolane",
    city: "hamburg",
    remote: "hybrid",
    sal: [55000, 68000, "EUR"],
    source: "StepStone",
    status: "applied",
    score: 77,
    family: "Risk & Audit",
    h: 118,
    critic: [7, "PASS"],
  },
  {
    title: "Finance Business Partner",
    company: "Brightline",
    city: "london",
    remote: "hybrid",
    sal: [60000, 75000, "GBP"],
    source: "Otta",
    status: "response",
    score: 79,
    family: "FP&A",
    h: 172,
    critic: [7, "PASS"],
  },
  {
    title: "M&A Analyst",
    company: "Portico Advisors",
    city: "lisbon",
    remote: "hybrid",
    sal: [45000, 60000, "EUR"],
    source: "eFinancialCareers",
    status: "writing",
    score: 85,
    family: "M&A / Deals",
    h: 34,
    wr: true,
    jd: "Boutique advisory: valuation, due diligence support and deal execution for mid-market transactions.",
  },
  {
    title: "Revenue Operations Analyst",
    company: "Pipebase",
    remote: "full_remote",
    sal: [50000, 64000, "EUR"],
    source: "Company site",
    status: "writing",
    score: 74,
    family: "Business Analysis",
    h: 48,
    wr: true,
  },
  {
    title: "Group Reporting Specialist",
    company: "Nordwind",
    city: "stockholm",
    remote: "hybrid",
    sal: [52000, 64000, "EUR"],
    source: "LinkedIn",
    status: "review",
    score: 78,
    family: "Accounting",
    h: 56,
  },
  {
    title: "Pricing Analyst",
    company: "Loopway",
    city: "barcelona",
    remote: "full_remote",
    sal: [45000, 58000, "EUR"],
    source: "Wellfound",
    status: "review",
    score: 80,
    family: "Business Analysis",
    h: 64,
  },
  {
    title: "Junior Accountant",
    company: "Weblab Italia",
    city: "bologna",
    remote: "onsite",
    sal: [26000, 32000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 54,
    family: "Accounting",
    h: 74,
  },
  {
    title: "Credit Controller",
    company: "MarketNest",
    city: "roma",
    remote: "hybrid",
    sal: [30000, 38000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 58,
    family: "Accounting",
    h: 88,
  },
  {
    title: "FP&A Analyst",
    company: "Lexio AI",
    city: "munich",
    remote: "hybrid",
    sal: [55000, 68000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 72,
    family: "FP&A",
    h: 100,
  },
  {
    title: "Data Analyst, Finance",
    company: "Fluxwave",
    remote: "full_remote",
    sal: [48000, 62000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 70,
    family: "Business Analysis",
    h: 108,
  },
  {
    title: "Compliance Analyst, AML",
    company: "SignalForge",
    remote: "full_remote",
    sal: [55000, 72000, "USD"],
    source: "LinkedIn",
    status: "scored",
    score: 63,
    family: "Risk & Audit",
    h: 124,
  },
  {
    title: "Payroll Specialist",
    company: "Testardo",
    city: "torino",
    remote: "hybrid",
    sal: [28000, 35000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 56,
    family: "Accounting",
    h: 134,
  },
  {
    title: "Investor Relations Associate",
    company: "GreenGrid",
    city: "amsterdam",
    remote: "hybrid",
    sal: [55000, 70000, "EUR"],
    source: "Otta",
    status: "scored",
    score: 68,
    family: "M&A / Deals",
    h: 144,
  },
  {
    title: "Junior Business Controller",
    company: "Ostrava Tech",
    city: "prague",
    remote: "hybrid",
    sal: [30000, 40000, "EUR"],
    source: "Company site",
    status: "checked",
    family: "FP&A",
    h: 154,
  },
  {
    title: "Head of Finance",
    company: "Snapdeck",
    city: "copenhagen",
    remote: "hybrid",
    sal: [85000, 105000, "EUR"],
    source: "Otta",
    status: "checked",
    family: "FP&A",
    h: 160,
  },
  {
    title: "Fund Accountant",
    company: "Dublin Fund Services",
    city: "dublin",
    remote: "hybrid",
    sal: [45000, 55000, "EUR"],
    source: "eFinancialCareers",
    status: "checked",
    family: "Accounting",
    h: 168,
  },
  {
    title: "ESG Reporting Analyst",
    company: "Databridge",
    city: "madrid",
    remote: "hybrid",
    sal: [38000, 48000, "EUR"],
    source: "LinkedIn",
    status: "new",
    family: "Risk & Audit",
    h: 178,
  },
  {
    title: "Cost Accountant, Manufacturing",
    company: "Old Mill Industries",
    city: "firenze",
    remote: "onsite",
    sal: [32000, 40000, "EUR"],
    source: "Indeed",
    status: "new",
    family: "Accounting",
    h: 188,
  },
  {
    title: "Strategy Associate",
    company: "Kernelworks",
    remote: "full_remote",
    sal: [65000, 85000, "USD"],
    source: "Hacker News",
    status: "new",
    family: "Business Analysis",
    h: 194,
  },
  {
    title: "Door-to-door Insurance Agent",
    company: "AssicuraPlus",
    city: "roma",
    remote: "onsite",
    sal: [18000, 26000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 20,
    family: "Sales",
    h: 204,
  },
  {
    title: "Data Entry Clerk, Invoices",
    company: "CallItalia",
    city: "napoli_x",
    remote: "onsite",
    sal: [19000, 23000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 26,
    family: "Accounting",
    h: 214,
  },
];

const DESIGN: Seed[] = [
  {
    title: "Senior Product Designer",
    company: "Northstar Labs",
    city: "berlin",
    remote: "full_remote",
    sal: [70000, 88000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 92,
    family: "Product Design",
    h: 5,
    critic: [8, "PASS"],
    jd: "Own end-to-end product design for the analytics suite: discovery, flows, high-fidelity UI and a shared Figma design system.",
    req: [
      "5+ years product design, B2B SaaS",
      "Systems thinking, tokens, variables",
      "Comfort with research and data",
    ],
    pros: [
      "Design maturo con ricerca dedicata",
      "Full remote EU",
      "Range sopra mercato",
    ],
    cons: ["Ritmo release settimanale"],
  },
  {
    title: "UX Researcher",
    company: "AtlasCare",
    city: "milano",
    remote: "hybrid",
    sal: [48000, 60000, "EUR"],
    source: "Wellfound",
    status: "ready",
    score: 85,
    family: "UX Research",
    h: 13,
    critic: [7, "PASS"],
    jd: "Healthtech: qualitative and quantitative research with patients and clinicians, research ops from scratch.",
    req: [
      "Mixed-methods research",
      "Healthcare or regulated domain a plus",
      "Italian + English",
    ],
    pros: ["Ricerca con impatto reale", "Team design in crescita"],
    cons: ["Due giorni in sede"],
  },
  {
    title: "Design Systems Designer",
    company: "Brightline",
    city: "london",
    remote: "full_remote",
    sal: [60000, 78000, "GBP"],
    source: "Otta",
    status: "ready",
    score: 87,
    family: "Design Systems",
    h: 21,
    critic: [8, "PASS"],
    jd: "Own the multi-brand design system of a dev-tools company: tokens, components, docs and adoption.",
    req: [
      "Design systems at scale",
      "Deep Figma expertise (variables, plugins)",
      "Close collaboration with engineers",
    ],
    pros: [
      "Ruolo dedicato al design system",
      "Cultura design-engineering forte",
    ],
    cons: ["Stakeholder su 3 timezone"],
  },
  {
    title: "Brand Designer",
    company: "Studio Relay",
    city: "firenze",
    remote: "hybrid",
    sal: [40000, 52000, "EUR"],
    source: "LinkedIn",
    status: "ready",
    score: 83,
    family: "Brand & Graphic",
    h: 29,
    critic: [7, "PASS"],
    jd: "Design-led studio: identity systems, campaign art direction and motion collaborations for EU clients.",
    req: [
      "Strong identity portfolio",
      "Art direction experience",
      "Motion sensibility a plus",
    ],
    pros: ["Portfolio clienti di livello", "Studio riconosciuto"],
    cons: ["Ritmi da studio con deadline client"],
  },
  {
    title: "Product Designer, Mobile",
    company: "Loopway",
    city: "barcelona",
    remote: "full_remote",
    sal: [52000, 66000, "EUR"],
    source: "Wellfound",
    status: "applied",
    score: 81,
    family: "Product Design",
    h: 90,
    critic: [7, "PASS"],
    jd: "Consumer mobility app: native patterns, design sprints, growth experiments with the marketing squad.",
  },
  {
    title: "UI Designer, Fintech",
    company: "FinPilot",
    city: "amsterdam",
    remote: "hybrid",
    sal: [50000, 64000, "EUR"],
    source: "LinkedIn",
    status: "applied",
    score: 78,
    family: "Product Design",
    h: 120,
    critic: [7, "PASS"],
  },
  {
    title: "Motion Designer",
    company: "Snapdeck",
    city: "copenhagen",
    remote: "full_remote",
    sal: [45000, 58000, "EUR"],
    source: "Otta",
    status: "response",
    score: 76,
    family: "Motion & Video",
    h: 174,
    critic: [6, "PASS"],
  },
  {
    title: "Product Designer, Platform",
    company: "Pipebase",
    remote: "full_remote",
    sal: [55000, 70000, "EUR"],
    source: "Company site",
    status: "writing",
    score: 84,
    family: "Product Design",
    h: 33,
    wr: true,
    jd: "B2B data platform: complex tables, dashboards and workflows. Strong information design focus.",
  },
  {
    title: "Visual Designer, Marketing",
    company: "NovaPay",
    city: "dublin",
    remote: "hybrid",
    sal: [42000, 54000, "EUR"],
    source: "Wellfound",
    status: "writing",
    score: 72,
    family: "Brand & Graphic",
    h: 47,
    wr: true,
  },
  {
    title: "Service Designer",
    company: "Mosaic Cloud",
    city: "paris",
    remote: "hybrid",
    sal: [50000, 64000, "EUR"],
    source: "Welcome to the Jungle",
    status: "review",
    score: 79,
    family: "UX Research",
    h: 57,
  },
  {
    title: "UX Writer",
    company: "GreenGrid",
    city: "amsterdam",
    remote: "full_remote",
    sal: [45000, 58000, "EUR"],
    source: "Otta",
    status: "review",
    score: 77,
    family: "Content Design",
    h: 65,
  },
  {
    title: "Graphic Designer",
    company: "MarketNest",
    city: "roma",
    remote: "hybrid",
    sal: [28000, 36000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 58,
    family: "Brand & Graphic",
    h: 75,
  },
  {
    title: "Junior UI Designer",
    company: "Weblab Italia",
    city: "bologna",
    remote: "onsite",
    sal: [24000, 30000, "EUR"],
    source: "Indeed",
    status: "scored",
    score: 52,
    family: "Product Design",
    h: 89,
  },
  {
    title: "Design Lead",
    company: "Helvetia Systems",
    city: "zurich",
    remote: "hybrid",
    sal: [110000, 130000, "CHF"],
    source: "LinkedIn",
    status: "scored",
    score: 74,
    family: "Product Design",
    h: 101,
  },
  {
    title: "Illustrator, Editorial",
    company: "Fluxwave",
    remote: "full_remote",
    sal: [38000, 50000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 63,
    family: "Brand & Graphic",
    h: 109,
  },
  {
    title: "3D Artist, Product Viz",
    company: "Kernelworks",
    remote: "full_remote",
    sal: [50000, 68000, "USD"],
    source: "Hacker News",
    status: "scored",
    score: 66,
    family: "Motion & Video",
    h: 125,
  },
  {
    title: "UX Designer, E-commerce",
    company: "Databridge",
    city: "madrid",
    remote: "hybrid",
    sal: [38000, 48000, "EUR"],
    source: "InfoJobs",
    status: "scored",
    score: 68,
    family: "Product Design",
    h: 135,
  },
  {
    title: "Interaction Designer",
    company: "Lexio AI",
    city: "munich",
    remote: "hybrid",
    sal: [55000, 70000, "EUR"],
    source: "LinkedIn",
    status: "scored",
    score: 71,
    family: "Product Design",
    h: 145,
  },
  {
    title: "Design Ops Manager",
    company: "Nordwind",
    city: "stockholm",
    remote: "hybrid",
    sal: [55000, 68000, "EUR"],
    source: "LinkedIn",
    status: "checked",
    family: "Design Systems",
    h: 155,
  },
  {
    title: "Creative Director",
    company: "Portico Studio",
    city: "lisbon",
    remote: "hybrid",
    sal: [70000, 90000, "EUR"],
    source: "Wellfound",
    status: "checked",
    family: "Brand & Graphic",
    h: 161,
  },
  {
    title: "Packaging Designer",
    company: "Old Mill Industries",
    city: "torino",
    remote: "onsite",
    sal: [32000, 40000, "EUR"],
    source: "Indeed",
    status: "checked",
    family: "Brand & Graphic",
    h: 169,
  },
  {
    title: "Product Designer, Design Tools",
    company: "Ostrava Tech",
    city: "prague",
    remote: "hybrid",
    sal: [40000, 52000, "EUR"],
    source: "Company site",
    status: "new",
    family: "Product Design",
    h: 179,
  },
  {
    title: "Accessibility Specialist",
    company: "Cargolane",
    city: "hamburg",
    remote: "hybrid",
    sal: [48000, 60000, "EUR"],
    source: "StepStone",
    status: "new",
    family: "UX Research",
    h: 189,
  },
  {
    title: "UX Researcher, Games",
    company: "Testardo Play",
    city: "torino",
    remote: "hybrid",
    sal: [35000, 45000, "EUR"],
    source: "Indeed",
    status: "new",
    family: "UX Research",
    h: 195,
  },
  {
    title: "Flyer Designer, Print Shop",
    company: "AgencyOne",
    city: "roma",
    remote: "onsite",
    sal: [20000, 26000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 25,
    family: "Brand & Graphic",
    h: 205,
  },
  {
    title: "Sign Painter Apprentice",
    company: "Old Mill Industries",
    city: "napoli_x",
    remote: "onsite",
    sal: [17000, 22000, "EUR"],
    source: "Indeed",
    status: "excluded",
    score: 19,
    family: "Brand & Graphic",
    h: 215,
  },
];

// "napoli_x" = città volutamente NON presente in CITIES: quelle posizioni
// finiscono nel bucket "senza coordinate" della mappa (widget "+N"), così
// anche quella parte della UI è dimostrabile.
const SEEDS: Record<DemoPersonaKey, Seed[]> = {
  software: SOFTWARE,
  marketing: MARKETING,
  finance: FINANCE,
  design: DESIGN,
};

const LEGACY_BASE: Record<DemoPersonaKey, number> = {
  software: 9000,
  marketing: 9100,
  finance: 9200,
  design: 9300,
};

// ── Espansione seed → entità complete ──────────────────────────────

export type DemoPosition = Position & {
  score: number | null;
  critic_score: number | null;
  critic_verdict: string | null;
  salary_min: number | null;
  salary_max: number | null;
  salary_currency: string;
  lat: number | null;
  lon: number | null;
  last_action_at: string;
  last_action_by: string;
  last_action_actor: string;
  demo_score_row: Score | null;
  demo_highlights: PositionHighlight[];
};

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}

// Deriva un sub-score plausibile dal totale, deterministico per posizione.
function sub(total: number, salt: number, n: number): number {
  const jitter = ((salt * 7 + n * 13) % 11) - 5;
  return Math.max(10, Math.min(100, total + jitter));
}

const STATUS_RANK: Record<string, number> = {
  new: 0,
  checked: 1,
  scored: 2,
  writing: 3,
  review: 4,
  ready: 5,
  applied: 6,
  response: 7,
  excluded: 2,
};

function expand(key: DemoPersonaKey, seeds: Seed[]): DemoPosition[] {
  const base = LEGACY_BASE[key];
  return seeds.map((s, i) => {
    const n = i + 1;
    const legacy = base + n;
    const id = `demo-${key}-${String(n).padStart(3, "0")}`;
    const city: City | null =
      s.city && s.city in CITIES ? CITIES[s.city as CityKey] : null;
    const cityName = city?.city ?? (s.city ? "Napoli" : null);
    const country = city?.country ?? (s.city ? "Italy" : null);
    const cc = city?.cc ?? (s.city ? "IT" : null);
    const rank = STATUS_RANK[s.status] ?? 0;
    const found = hoursAgo(s.h);
    // Ultima azione: più lo status è avanti nella pipeline, più recente
    // dell'arrivo. Attore coerente con lo stadio.
    const lastAt = hoursAgo(Math.max(1, s.h - rank * Math.min(8, s.h / 8)));
    const actorByRank = [
      "scout",
      "analista",
      "scorer",
      "scrittore",
      "critico",
      "critico",
      "user",
      "user",
    ];
    const by = actorByRank[Math.min(rank, actorByRank.length - 1)];
    const scoredAt = s.score != null ? hoursAgo(Math.max(1, s.h - 6)) : null;
    const scoreRow: Score | null =
      s.score != null
        ? {
            id: `demo-score-${key}-${n}`,
            position_id: id,
            total_score: s.score,
            stack_match: sub(s.score, legacy, 1),
            remote_fit: sub(s.score, legacy, 2),
            salary_fit: sub(s.score, legacy, 3),
            experience_fit: sub(s.score, legacy, 4),
            strategic_fit: sub(s.score, legacy, 5),
            breakdown: null,
            notes: null,
            scored_by: `scorer-${(legacy % 2) + 1}`,
            scored_at: scoredAt ?? found,
          }
        : null;
    const highlights: PositionHighlight[] = [
      ...(s.pros ?? []).map((text, j) => ({
        id: `demo-hl-${key}-${n}-p${j}`,
        position_id: id,
        type: "pro" as const,
        text,
      })),
      ...(s.cons ?? []).map((text, j) => ({
        id: `demo-hl-${key}-${n}-c${j}`,
        position_id: id,
        type: "con" as const,
        text,
      })),
    ];
    return {
      id,
      legacy_id: legacy,
      title: s.title,
      company: s.company,
      company_id: null,
      location: cityName
        ? `${cityName}, ${cc}`
        : s.remote === "full_remote"
          ? "Remote"
          : null,
      remote_type: s.remote,
      salary_declared_min: s.sal?.[0] ?? null,
      salary_declared_max: s.sal?.[1] ?? null,
      salary_declared_currency: s.sal?.[2] ?? null,
      salary_estimated_min: null,
      salary_estimated_max: null,
      salary_estimated_currency: null,
      salary_estimated_source: null,
      url: `https://example.com/demo-jobs/${legacy}`,
      source: s.source,
      jd_text: null,
      jd_summary: s.jd ?? null,
      requirements: s.req ? s.req.map((r) => `- ${r}`).join("\n") : null,
      found_by: `scout-${(legacy % 3) + 1}`,
      found_at: found,
      deadline: null,
      status: s.status,
      notes: null,
      last_checked: rank >= 1 ? hoursAgo(Math.max(1, s.h - 3)) : null,
      is_open: true,
      role_family: s.family,
      loc_country: country,
      loc_city: cityName,
      loc_country_code: cc,
      write_requested: !!s.wr || rank >= 3,
      office_lat: city?.lat ?? null,
      office_lon: city?.lon ?? null,
      office_address: null,
      score: s.score ?? null,
      critic_score: s.critic?.[0] ?? null,
      critic_verdict: s.critic?.[1] ?? null,
      salary_min: s.sal?.[0] ?? null,
      salary_max: s.sal?.[1] ?? null,
      salary_currency: s.sal?.[2] ?? "EUR",
      lat: city?.lat ?? null,
      lon: city?.lon ?? null,
      last_action_at: lastAt,
      last_action_by: by,
      last_action_actor: by === "scout" ? `scout-${(legacy % 3) + 1}` : by,
      demo_score_row: scoreRow,
      demo_highlights: highlights,
    };
  });
}

const cache = new Map<DemoPersonaKey, DemoPosition[]>();

export function getDemoPositionsData(key: DemoPersonaKey): DemoPosition[] {
  let v = cache.get(key);
  if (!v) {
    v = expand(key, SEEDS[key]);
    cache.set(key, v);
  }
  return v;
}

export function findDemoPositionById(id: string): DemoPosition | null {
  for (const key of DEMO_PERSONA_KEYS) {
    const hit = getDemoPositionsData(key).find((p) => p.id === id);
    if (hit) return hit;
  }
  return null;
}

export function findDemoPositionByLegacyId(
  legacyId: number,
): DemoPosition | null {
  for (const key of DEMO_PERSONA_KEYS) {
    const hit = getDemoPositionsData(key).find((p) => p.legacy_id === legacyId);
    if (hit) return hit;
  }
  return null;
}
