import type { MetadataRoute } from 'next'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://jobhunterteam.ai'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/auth',
          '/setup',
          // Dashboard / app pages
          '/dashboard',
          '/profile',
          '/team',
          '/applications',
          '/positions',
          '/ready',
          '/risposte',
          '/crescita',
          '/assistente',
          '/capitano',
          '/scout',
          '/analista',
          '/scorer',
          '/scrittore',
          '/critico',
          '/sentinella',
          '/agents',
          '/tasks',
          '/sessions',
          '/queue',
          '/events',
          '/logs',
          '/analytics',
          '/budget',
          '/sentinel',
          '/forum',
          '/audit',
          '/reports',
          '/integrations',
          '/settings',
          '/credentials',
          '/providers',
          '/channels',
          '/deploy',
          '/gateway',
          '/health',
          '/validators',
          '/skills',
          '/notifications',
          // Dashboard pages added
          '/achievements',
          '/activity',
          '/ai-assistant',
          '/alerts',
          '/archive',
          '/assistant',
          '/automations',
          '/backup',
          '/bookmarks',
          '/calendar',
          '/companies',
          '/compare',
          '/config',
          '/contacts',
          '/context',
          '/cover-letters',
          '/cron',
          '/daemon',
          '/database',
          '/env',
          '/errors',
          '/export',
          '/feedback',
          '/git',
          '/goals',
          '/history',
          '/hooks',
          '/import',
          '/insights',
          '/interviews',
          '/jobs',
          '/map',
          '/memory',
          '/messages',
          '/migrations',
          '/monitoring',
          '/networking',
          '/onboarding',
          '/overview',
          '/performance',
          '/pipelines',
          '/plugins',
          '/profiles',
          '/rate-limiter',
          '/recommendations',
          '/reminders',
          '/resume-builder',
          '/retry',
          '/saved-searches',
          '/scheduler',
          '/search',
          '/secrets',
          '/status',
          '/templates',
          '/timeline',
          '/tools',
          '/webhooks',
          '/workers',
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  }
}
