export type DocSection = { id: string; label: string }
export type Module     = { id: string; description: string; group: string }
export type CliCmd     = { cmd: string; description: string; example?: string }
export type ApiRoute   = { method: 'GET' | 'POST' | 'PATCH' | 'DELETE'; path: string; description: string }

export const SECTIONS: DocSection[] = [
  { id: 'overview',  label: 'Architettura' },
  { id: 'modules',   label: 'Moduli shared/' },
  { id: 'cli',       label: 'Comandi CLI' },
  { id: 'api',       label: 'API Routes' },
]

export const MODULES: Module[] = [
  // Core
  { id: 'agents',        group: 'Core',       description: 'Definizioni agenti, configurazione ruoli e capacità' },
  { id: 'tasks',         group: 'Core',       description: 'Gestione task asincroni con stati queued/running/terminal' },
  { id: 'sessions',      group: 'Core',       description: 'Sessioni conversazione multi-canale (web, CLI, Telegram)' },
  { id: 'events',        group: 'Core',       description: 'EventBus pub/sub + SSE per notifiche real-time' },
  { id: 'history',       group: 'Core',       description: 'Cronologia conversazioni con transcript JSONL' },
  // AI
  { id: 'context-engine',group: 'AI',         description: 'Assembla contesto AI rispettando budget token' },
  { id: 'llm',           group: 'AI',         description: 'Client unificato per provider AI (Anthropic, OpenAI, Minimax)' },
  { id: 'memory',        group: 'AI',         description: 'Memoria persistente agenti: soul, identity, episodic' },
  { id: 'providers',     group: 'AI',         description: 'Configurazione e auth provider AI' },
  { id: 'analytics',     group: 'AI',         description: 'Metriche uso API, costi token, latenza' },
  // Data
  { id: 'backup',        group: 'Dati',       description: 'Backup atomico con manifest + ripristino selettivo' },
  { id: 'migrations',    group: 'Dati',       description: 'Migrazioni schema versionate con rollback' },
  { id: 'i18n',          group: 'Dati',       description: 'Internazionalizzazione, chiavi traduzione IT/EN' },
  { id: 'data',          group: 'Dati',       description: 'Layer accesso dati, lettura/scrittura JSON atomica' },
  { id: 'credentials',   group: 'Dati',       description: 'Gestione credenziali cifrate per servizi esterni' },
  { id: 'secrets',       group: 'Dati',       description: 'Secrets cifrati AES-256 (API key, token, password)' },
  // Sistema
  { id: 'daemon',        group: 'Sistema',    description: 'Processo daemon: plist (macOS), systemd (Linux)' },
  { id: 'scheduler',     group: 'Sistema',    description: 'Job scheduler con cron expression e retry' },
  { id: 'cron',          group: 'Sistema',    description: 'Definizioni job cron e gestione lifecycle' },
  { id: 'monitoring',    group: 'Sistema',    description: 'CPU, memoria, heartbeat, alerter soglie' },
  { id: 'logger',        group: 'Sistema',    description: 'Logger strutturato livelli DEBUG/INFO/WARN/ERROR' },
  { id: 'rate-limiter',  group: 'Sistema',    description: 'Rate limiter token bucket per API esterne' },
  { id: 'retry',         group: 'Sistema',    description: 'Circuit breaker + retry esponenziale' },
  { id: 'queue',         group: 'Sistema',    description: 'Coda task prioritaria con concorrenza configurabile' },
  // Integrazione
  { id: 'telegram',      group: 'Integrazione', description: 'Bot Telegram: handler messaggi, webhook, polling' },
  { id: 'channels',      group: 'Integrazione', description: 'Canali comunicazione astratti (web/CLI/Telegram)' },
  { id: 'gateway',       group: 'Integrazione', description: 'Gateway API esterno con routing e auth middleware' },
  { id: 'hooks',         group: 'Integrazione', description: 'Hook eventi su azioni sistema (task completato, ecc.)' },
  { id: 'plugins',       group: 'Integrazione', description: 'Sistema plugin: discovery, caricamento, lifecycle' },
  { id: 'skills',        group: 'Integrazione', description: 'Skill agenti: definizione, registrazione, esecuzione' },
  { id: 'tools',         group: 'Integrazione', description: 'Tool AI registrati e disponibili agli agenti' },
  { id: 'templates',     group: 'Integrazione', description: 'Template messaggi con variabili e categorie' },
  { id: 'notifications', group: 'Integrazione', description: 'Centro notifiche: read/unread, filtri, desktop' },
  { id: 'docs',          group: 'Integrazione', description: 'Helper generazione documentazione da sorgenti' },
  { id: 'validators',    group: 'Integrazione', description: 'Validatori schema JSON con report errori' },
  { id: 'deploy',        group: 'Integrazione', description: 'Deploy pipeline: build, push, rollback' },
  { id: 'assistant',     group: 'Integrazione', description: 'Assistente AI con context e upload allegati' },
]

export const CLI_COMMANDS: CliCmd[] = [
  { cmd: 'jht setup',         description: 'Wizard configurazione iniziale workspace' },
  { cmd: 'jht status',        description: 'Stato sistema: agenti attivi, sessioni, task' },
  { cmd: 'jht health',        description: 'Health check 7 moduli con semafori' },
  { cmd: 'jht doctor',        description: 'Diagnostica config, provider, dipendenze, permessi' },
  { cmd: 'jht upgrade',       description: 'Verifica versione remote e aggiorna (--apply)' },
  { cmd: 'jht dashboard',     description: 'Avvia Next.js dev server e apre browser', example: 'jht dashboard --port 3001' },
  { cmd: 'jht team start',    description: 'Avvia agenti in sessioni tmux JHT-*', example: 'jht team start ALFA' },
  { cmd: 'jht team stop',     description: 'Ferma sessioni tmux agenti' },
  { cmd: 'jht team list',     description: 'Elenca sessioni tmux attive JHT-*' },
  { cmd: 'jht agents',        description: '8 agenti con stato tmux e conteggio task' },
  { cmd: 'jht sessions',      description: 'Tabella sessioni con filtri stato/tail/verbose' },
  { cmd: 'jht stats',         description: 'Statistiche aggregate task/API/sessioni con periodo' },
  { cmd: 'jht backup',        description: 'Crea/lista/ripristina backup con manifest' },
  { cmd: 'jht migrate',       description: 'Migrazioni v1→v4 con dry-run' },
  { cmd: 'jht cache',         description: 'Stats e pulizia cache/tmp/logs' },
  { cmd: 'jht export',        description: 'Esporta dati JSON/CSV con filtro date' },
  { cmd: 'jht import',        description: 'Importa dati con validazione e dry-run' },
  { cmd: 'jht logs',          description: 'Log con filtri livello/modulo, output colorato' },
  { cmd: 'jht config',        description: 'Legge e imposta valori configurazione' },
  { cmd: 'jht plugins',       description: 'Lista/abilita/disabilita plugin da manifest' },
  { cmd: 'jht providers',     description: 'Stato autenticazione Anthropic/OpenAI/Minimax' },
  { cmd: 'jht context',       description: 'Stato/sources/clear context-engine' },
  { cmd: 'jht secrets',       description: 'Gestione secrets AES-256: list/set/get/delete' },
  { cmd: 'jht hooks',         description: 'Lista/abilita/disabilita/show hook per evento' },
  { cmd: 'jht notifications', description: 'Lista/read/clear notifiche (alias: notif)' },
  { cmd: 'jht templates',     description: 'Lista template per categoria, preview variabili' },
  { cmd: 'jht cron',          description: 'Job cron: list/enable/disable/run' },
]

export const API_ROUTES: ApiRoute[] = [
  { method: 'GET',    path: '/api/agents',        description: 'Lista agenti con stato sessione tmux' },
  { method: 'GET',    path: '/api/tasks',          description: 'Task con filtro stato (queued/running/terminal)' },
  { method: 'POST',   path: '/api/tasks',          description: 'Crea nuovo task con agentId opzionale' },
  { method: 'PATCH',  path: '/api/tasks',          description: 'Cancella task attivo' },
  { method: 'GET',    path: '/api/sessions',       description: 'Lista sessioni con filtro stato' },
  { method: 'POST',   path: '/api/sessions',       description: 'Crea sessione su canale' },
  { method: 'PATCH',  path: '/api/sessions',       description: 'Cambia stato sessione (active/paused/ended)' },
  { method: 'GET',    path: '/api/events',         description: 'SSE stream eventi real-time' },
  { method: 'GET',    path: '/api/history',        description: 'Conversazioni con filtro agentId' },
  { method: 'POST',   path: '/api/history',        description: 'Crea conversazione o aggiunge messaggio' },
  { method: 'DELETE', path: '/api/history',        description: 'Elimina conversazione per ID' },
  { method: 'GET',    path: '/api/activity',       description: 'Feed attività team paginato con filtro tipo' },
  { method: 'GET',    path: '/api/search',         description: 'Ricerca globale ?q= su pagine/agenti/sessioni/task' },
  { method: 'GET',    path: '/api/secrets',        description: 'Lista secrets con valori mascherati' },
  { method: 'POST',   path: '/api/secrets',        description: 'Aggiunge nuovo secret cifrato' },
  { method: 'DELETE', path: '/api/secrets',        description: 'Elimina secret per ID' },
  { method: 'GET',    path: '/api/context',        description: 'Stato context engine: budget, sezioni, config' },
  { method: 'GET',    path: '/api/preferences',    description: 'Preferenze utente' },
  { method: 'PATCH',  path: '/api/preferences',    description: 'Aggiorna preferenze (tema, lingua, notifiche)' },
  { method: 'GET',    path: '/api/onboarding',     description: 'Stato tour onboarding' },
  { method: 'POST',   path: '/api/onboarding',     description: 'Aggiorna step/skip/reset onboarding' },
  { method: 'GET',    path: '/api/hooks',          description: 'Scopre hook dalla workspace' },
  { method: 'GET',    path: '/api/settings',       description: 'Configurazione corrente' },
  { method: 'PATCH',  path: '/api/settings',       description: 'Aggiorna settings' },
  { method: 'POST',   path: '/api/settings/_action', description: 'Azioni: export-data, clear-cache, reset-settings' },
]
