[package]
name = "jht-desktop"
version = "0.1.0"
description = "Job Hunter Team desktop shell"
authors = ["Leone Emanuel Puglisi"]
edition = "2021"

[lib]
name = "jht_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
