-- jobs.db schema, as shared/skills/_db.py ensure_schema() creates it.
-- GENERATED by scripts/dump-jobs-schema.py: do not edit, regenerate.
-- source: origin/master 4717266e8
-- _db.py sha256: 0a77baf0575806e6120b57c594a4472ecc872cf0705969e9340a1b5d5a0393a4

CREATE TABLE role_family_registry (
            user_id       TEXT NOT NULL,
            name          TEXT NOT NULL,
            status        TEXT NOT NULL DEFAULT 'active',
            support_count INTEGER NOT NULL DEFAULT 0,
            merged_into   TEXT,
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            promoted_at   TIMESTAMP,
            PRIMARY KEY (user_id, name)
        );

CREATE INDEX idx_rfr_active ON role_family_registry(user_id, status);

CREATE TABLE position_feedback (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            position_id INTEGER NOT NULL,
            action TEXT NOT NULL CHECK (action IN (
                'like','dislike','hide','star','clear'
            )),
            reason TEXT,
            comment TEXT,
            score INTEGER CHECK (score IS NULL OR (score BETWEEN 1 AND 5)),
            direction TEXT CHECK (direction IS NULL OR direction IN (
                'more_like_this','less_like_this'
            )),
            cloud_id INTEGER,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (position_id) REFERENCES positions(id)
        );

CREATE INDEX idx_position_feedback_position
            ON position_feedback(position_id, id DESC);

CREATE TABLE position_user_notes (
            position_id INTEGER NOT NULL,
            origin TEXT NOT NULL DEFAULT 'box' CHECK (origin IN ('box','web')),
            body TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (position_id, origin),
            FOREIGN KEY (position_id) REFERENCES positions(id)
        );

CREATE TABLE email_application_attempts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            position_id INTEGER NOT NULL,
            idempotency_key TEXT NOT NULL,
            state TEXT NOT NULL CHECK (state IN (
                'draft_ready', 'send_started', 'sent',
                'send_outcome_unknown', 'receipt_incomplete', 'error'
            )),
            message_id TEXT NOT NULL,
            recipients_json TEXT NOT NULL,
            body_sha256 TEXT NOT NULL,
            attachments_json TEXT NOT NULL,
            receipt_json TEXT,
            error_class TEXT,
            send_started_at TEXT,
            accepted_at TEXT,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            UNIQUE (position_id, idempotency_key)
        );

CREATE INDEX idx_email_attempts_position ON email_application_attempts(position_id, state);

CREATE TABLE application_answers (
            key TEXT PRIMARY KEY CHECK (key <> ''),
            label TEXT NOT NULL,
            answer_json TEXT NOT NULL,
            field_type TEXT NOT NULL,
            options_json TEXT NOT NULL DEFAULT '[]',
            channel TEXT NOT NULL,
            source_message_id INTEGER,
            answered_at TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        , basis TEXT NOT NULL DEFAULT '');

CREATE TABLE closer_wakes (
            wake_key TEXT PRIMARY KEY,
            position_id INTEGER,
            delivered INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        );

CREATE TABLE apply_cap_reservations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            position_id INTEGER NOT NULL,
            channel TEXT NOT NULL CHECK (channel IN ('email', 'browser')),
            token TEXT NOT NULL UNIQUE,
            state TEXT NOT NULL DEFAULT 'reserved' CHECK (state IN ('reserved', 'released')),
            reserved_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            released_at TEXT
        );

CREATE INDEX idx_apply_cap_reservations_day ON apply_cap_reservations(state, reserved_at);

CREATE TABLE companies (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE,
        website TEXT,
        hq_country TEXT,
        sector TEXT,
        size TEXT,
        glassdoor_rating REAL,
        red_flags TEXT,
        culture_notes TEXT,
        analyzed_by TEXT,
        analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        verdict TEXT,
        logo TEXT,
        logo_source TEXT,
        logo_fetched INTEGER DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE positions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT NOT NULL,
        company TEXT NOT NULL,
        company_id INTEGER,
        location TEXT,
        remote_type TEXT,
        salary_declared_min INTEGER,
        salary_declared_max INTEGER,
        salary_declared_currency TEXT DEFAULT 'EUR',
        salary_estimated_min INTEGER,
        salary_estimated_max INTEGER,
        salary_estimated_currency TEXT DEFAULT 'EUR',
        salary_estimated_source TEXT,
        url TEXT,
        source TEXT,
        jd_text TEXT,
        requirements TEXT,
        jd_summary TEXT,
        found_by TEXT,
        found_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deadline TEXT,
        status TEXT DEFAULT 'new' CHECK (status IN (
            'new','checked','scored','writing','review','ready','applied','response','excluded'
        )),
        notes TEXT,
        last_checked TIMESTAMP,
        last_actor TEXT,
        role_family TEXT,
        role_family_proposed TEXT,
        loc_city TEXT,
        loc_region TEXT,
        loc_country TEXT,
        loc_country_code TEXT,
        loc_continent TEXT,
        work_mode TEXT,
        work_country TEXT,
        work_country_code TEXT,
        is_multi_location INTEGER DEFAULT 0,
        location_notes TEXT,
        office_lat REAL,
        office_lon REAL,
        office_address TEXT,
        office_geocoded INTEGER DEFAULT 0,
        office_verified INTEGER DEFAULT 0,
        expires_at DATE,
        is_open INTEGER DEFAULT 1,
        last_open_check TIMESTAMP,
        write_requested INTEGER DEFAULT 0,
        write_requested_at TIMESTAMP,
        write_request_kind TEXT,
        geocode_requested INTEGER DEFAULT 0,
        geocode_requested_at TIMESTAMP,
        salary_precise_requested INTEGER DEFAULT 0,
        salary_precise_requested_at TIMESTAMP,
        salary_precise TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, user_excluded_reason TEXT, user_excluded_note TEXT, user_excluded_at TIMESTAMP, user_excluded_prev_status TEXT, recheck_requested INTEGER DEFAULT 0, recheck_requested_at TIMESTAMP, apply_requested INTEGER DEFAULT 0, apply_requested_at TIMESTAMP, apply_requested_by TEXT,
        -- Length guardrails: mirror dei CHECK constraint Postgres (mig 015).
        -- Origin: incident RobertHalf 2026-05-19 (location 4394 char di HTML
        -- bloccava sync cloud, vedi docs/internal/architecture/cloud-sync-architecture.md).
        -- SQLite locale deve fallire SUBITO al INSERT, non in differita al push.
        CHECK (LENGTH(title) <= 500),
        CHECK (LENGTH(company) <= 300),
        CHECK (location IS NULL OR LENGTH(location) <= 200),
        FOREIGN KEY (company_id) REFERENCES companies(id)
    );

CREATE TABLE position_highlights (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        position_id INTEGER NOT NULL,
        type TEXT NOT NULL,
        text TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (position_id) REFERENCES positions(id)
    );

CREATE TABLE scores (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        position_id INTEGER NOT NULL UNIQUE,
        total_score INTEGER NOT NULL,
        stack_match INTEGER,
        remote_fit INTEGER,
        salary_fit INTEGER,
        experience_fit INTEGER,
        strategic_fit INTEGER,
        breakdown TEXT,
        notes TEXT,
        scored_by TEXT,
        scored_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (position_id) REFERENCES positions(id)
    );

CREATE TABLE applications (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        position_id INTEGER NOT NULL UNIQUE,
        cv_path TEXT,
        cl_path TEXT,
        cv_pdf_path TEXT,
        cl_pdf_path TEXT,
        critic_verdict TEXT,
        critic_score REAL,
        critic_notes TEXT,
        critic_round INTEGER,
        status TEXT DEFAULT 'draft',
        written_at TIMESTAMP,
        applied_at TIMESTAMP,
        applied_via TEXT,
        response TEXT,
        response_at TIMESTAMP,
        rejection_reason TEXT,
        rejection_note TEXT,
        written_by TEXT,
        reviewed_by TEXT,
        critic_reviewed_at TIMESTAMP,
        applied BOOLEAN DEFAULT 0,
        interview_round INTEGER DEFAULT NULL,
        cv_drive_id TEXT,
        cl_drive_id TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (position_id) REFERENCES positions(id)
    );

CREATE TABLE pending_user_messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        agent TEXT NOT NULL,
        body TEXT NOT NULL,
        kind TEXT NOT NULL DEFAULT 'notification' CHECK (kind IN (
            'notification','question','digest','alert'
        )),
        author TEXT NOT NULL DEFAULT 'agent' CHECK (author IN ('agent','user')),
        chat_ts REAL,
        source_id TEXT,
        source_action TEXT,
        source_payload TEXT,
        source_directive_id INTEGER,
        related_position_id INTEGER,
        delivered_via TEXT CHECK (delivered_via IN ('telegram','web') OR delivered_via IS NULL),
        delivered_at TIMESTAMP,
        acknowledged_at TIMESTAMP,
        user_reply TEXT,
        user_reply_at TIMESTAMP,
        agent_seen_reply_at TIMESTAMP,
        cloud_synced_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, cloud_legacy_id INTEGER,
        FOREIGN KEY (related_position_id) REFERENCES positions(id)
    );

CREATE TABLE pending_user_message_delivery_claims (
        message_id INTEGER PRIMARY KEY,
        claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (message_id) REFERENCES pending_user_messages(id)
            ON DELETE CASCADE
    );

CREATE TABLE pending_user_message_delivery_retries (
        message_id INTEGER PRIMARY KEY,
        attempts INTEGER NOT NULL DEFAULT 0,
        next_attempt_at_ms INTEGER NOT NULL,
        last_code INTEGER,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (message_id) REFERENCES pending_user_messages(id)
            ON DELETE CASCADE
    );

CREATE TABLE position_tickets (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        position_id INTEGER NOT NULL,
        request_text TEXT NOT NULL,
        kind TEXT NOT NULL DEFAULT 'custom',
        status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','assigned','resolved')),
        assigned_agent TEXT,
        response_text TEXT,
        -- id del ticket gemello su Supabase (mig 043): correlazione per il
        -- round-trip cloud↔VPS. NULL = ticket creato in locale, non ancora
        -- pushato sul cloud (il daemon lo INSERT e scrive qui l'id). Vedi
        -- `jht cloud sync-tickets`.
        cloud_id INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        assigned_at TIMESTAMP,
        resolved_at TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (position_id) REFERENCES positions(id)
    );

CREATE TABLE team_directives (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        body TEXT NOT NULL,
        kind TEXT NOT NULL DEFAULT 'order' CHECK (kind IN (
            'order','strategy','formation','note'
        )),
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_by TEXT NOT NULL DEFAULT 'user',   -- user | capitano | assistente
        cloud_id INTEGER,                          -- gemello Supabase (round-trip dashboard); NULL = solo locale
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        archived_at TIMESTAMP
    );

CREATE TABLE team_directive_request_ledger (
        request_id TEXT PRIMARY KEY,
        action TEXT NOT NULL,
        target_id INTEGER NOT NULL,
        payload TEXT,
        result TEXT
    );

CREATE TABLE scout_coordination (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        scout TEXT NOT NULL,
        cerchi TEXT,
        fonti TEXT,
        note TEXT,
        started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        superseded_at TIMESTAMP
    );

CREATE TABLE scout_claims (
        job_id TEXT PRIMARY KEY,
        scout TEXT NOT NULL,
        claimed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX idx_positions_status ON positions(status);

CREATE INDEX idx_positions_company ON positions(company);

CREATE INDEX idx_positions_company_id ON positions(company_id);

CREATE INDEX idx_positions_url ON positions(url);

CREATE INDEX idx_positions_write_requested ON positions(write_requested) WHERE write_requested = 1;

CREATE INDEX idx_positions_geocode_requested ON positions(geocode_requested) WHERE geocode_requested = 1;

CREATE INDEX idx_positions_salary_precise_requested ON positions(salary_precise_requested) WHERE salary_precise_requested = 1;

CREATE INDEX idx_scores_total ON scores(total_score);

CREATE INDEX idx_applications_status ON applications(status);

CREATE INDEX idx_pending_user_messages_agent ON pending_user_messages(agent);

CREATE INDEX idx_pending_user_messages_delivery ON pending_user_messages(delivered_via, acknowledged_at);

CREATE INDEX idx_pending_user_messages_unseen_reply ON pending_user_messages(user_reply_at, agent_seen_reply_at);

CREATE UNIQUE INDEX idx_pending_messages_source_id
      ON pending_user_messages(source_id) WHERE source_id IS NOT NULL;

CREATE INDEX idx_position_tickets_status ON position_tickets(status);

CREATE INDEX idx_position_tickets_position ON position_tickets(position_id);

CREATE INDEX idx_position_tickets_cloud_id ON position_tickets(cloud_id) WHERE cloud_id IS NOT NULL;

CREATE INDEX idx_team_directives_status ON team_directives(status);

CREATE INDEX idx_team_directives_cloud_id ON team_directives(cloud_id) WHERE cloud_id IS NOT NULL;

CREATE INDEX idx_scout_coordination_active ON scout_coordination(scout) WHERE superseded_at IS NULL;

CREATE TABLE position_state_transitions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        position_id INTEGER NOT NULL,
        from_state TEXT,
        to_state TEXT NOT NULL,
        ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        by_agent TEXT NOT NULL,
        notes TEXT,
        FOREIGN KEY (position_id) REFERENCES positions(id)
    );

CREATE INDEX idx_pst_position_ts ON position_state_transitions(position_id, ts);

CREATE INDEX idx_pst_ts ON position_state_transitions(ts);

CREATE INDEX idx_pst_to_state ON position_state_transitions(to_state, ts);

CREATE TABLE maintenance_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        by_agent TEXT NOT NULL,
        target_type TEXT NOT NULL,       -- position | company
        target_id INTEGER NOT NULL,
        action TEXT NOT NULL,            -- vocabolario chiuso, vedi maintenance_log.ACTIONS
        outcome TEXT NOT NULL,           -- vocabolario chiuso, vedi maintenance_log.OUTCOMES
        field TEXT,                      -- campo toccato (NULL = esito senza scrittura)
        before TEXT,                     -- valore prima, come stringa
        after TEXT,                      -- valore dopo, come stringa
        evidence_kind TEXT,              -- http | api | manual | none
        evidence_url TEXT,
        evidence_code INTEGER,           -- status HTTP
        evidence_hash TEXT,              -- sha256 del contenuto normalizzato
        duration_ms INTEGER
    );

CREATE INDEX idx_me_target ON maintenance_events(target_type, target_id, ts);

CREATE INDEX idx_me_ts ON maintenance_events(ts);

CREATE INDEX idx_me_outcome ON maintenance_events(action, outcome, ts);

CREATE INDEX idx_me_agent ON maintenance_events(by_agent, ts);

CREATE TRIGGER applications_reject_str_now_insert
    BEFORE INSERT ON applications
    WHEN NEW.written_at = 'now' OR NEW.applied_at = 'now' OR NEW.response_at = 'now'
    BEGIN
      SELECT RAISE(ABORT,
        'INVALID TIMESTAMP: you passed the literal string "now" as written_at/applied_at/response_at. USE: python3 /app/shared/skills/db_update.py application <POSITION_ID> ... (the UPSERT skill converts it automatically). Do NOT run an inline INSERT via python3 -c "import sqlite3 ... VALUES (..., now, ...)". See RULE-11b in your prompt.'
      );
    END;

CREATE TRIGGER applications_reject_str_now_update
    BEFORE UPDATE ON applications
    WHEN NEW.written_at = 'now' OR NEW.applied_at = 'now' OR NEW.response_at = 'now'
    BEGIN
      SELECT RAISE(ABORT,
        'INVALID TIMESTAMP: you passed the literal string "now" in an UPDATE. USE: python3 /app/shared/skills/db_update.py application <POSITION_ID> --written-at now (the skill converts it), or datetime("now","localtime") in inline SQL.'
      );
    END;

CREATE TRIGGER positions_reject_str_now_insert
    BEFORE INSERT ON positions
    WHEN NEW.found_at = 'now' OR NEW.last_checked = 'now'
    BEGIN
      SELECT RAISE(ABORT,
        'INVALID TIMESTAMP: you passed the literal string "now" as positions.found_at/last_checked. USE: db_update.py position <ID> --last-checked now (it converts the value), or datetime("now","localtime") in inline SQL. Do NOT pass the literal string "now".'
      );
    END;

CREATE TRIGGER positions_reject_str_now_update
    BEFORE UPDATE ON positions
    WHEN NEW.found_at = 'now' OR NEW.last_checked = 'now'
    BEGIN
      SELECT RAISE(ABORT,
        'INVALID TIMESTAMP: you passed the literal string "now" in an UPDATE on positions. USE: db_update.py position <ID> --last-checked now, or datetime("now","localtime") in inline SQL.'
      );
    END;

CREATE TRIGGER companies_reject_str_now_insert
    BEFORE INSERT ON companies
    WHEN NEW.analyzed_at = 'now'
    BEGIN
      SELECT RAISE(ABORT,
        'INVALID TIMESTAMP: you passed the literal string "now" as companies.analyzed_at. USE: db_update.py company "<name>" ... (the skill sets CURRENT_TIMESTAMP), or datetime("now","localtime") in inline SQL.'
      );
    END;

CREATE TRIGGER companies_reject_str_now_update
    BEFORE UPDATE ON companies
    WHEN NEW.analyzed_at = 'now'
    BEGIN
      SELECT RAISE(ABORT,
        'INVALID TIMESTAMP: you passed the literal string "now" in an UPDATE on companies. USE: db_update.py company, or datetime("now","localtime") in inline SQL.'
      );
    END;

CREATE TRIGGER companies_touch_updated_at
    AFTER UPDATE ON companies FOR EACH ROW
    WHEN NEW.updated_at IS OLD.updated_at
    BEGIN
      UPDATE companies SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;

CREATE TRIGGER companies_default_created_at
    AFTER INSERT ON companies FOR EACH ROW
    WHEN NEW.created_at IS NULL OR NEW.updated_at IS NULL
    BEGIN
      UPDATE companies
      SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
          updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
      WHERE id = NEW.id;
    END;

CREATE TRIGGER positions_touch_updated_at
    AFTER UPDATE ON positions FOR EACH ROW
    WHEN NEW.updated_at IS OLD.updated_at
    BEGIN
      UPDATE positions SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;

CREATE TRIGGER positions_default_created_at
    AFTER INSERT ON positions FOR EACH ROW
    WHEN NEW.created_at IS NULL OR NEW.updated_at IS NULL
    BEGIN
      UPDATE positions
      SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
          updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
      WHERE id = NEW.id;
    END;

CREATE TRIGGER position_highlights_touch_updated_at
    AFTER UPDATE ON position_highlights FOR EACH ROW
    WHEN NEW.updated_at IS OLD.updated_at
    BEGIN
      UPDATE position_highlights SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;

CREATE TRIGGER position_highlights_default_created_at
    AFTER INSERT ON position_highlights FOR EACH ROW
    WHEN NEW.created_at IS NULL OR NEW.updated_at IS NULL
    BEGIN
      UPDATE position_highlights
      SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
          updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
      WHERE id = NEW.id;
    END;

CREATE TRIGGER scores_touch_updated_at
    AFTER UPDATE ON scores FOR EACH ROW
    WHEN NEW.updated_at IS OLD.updated_at
    BEGIN
      UPDATE scores SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;

CREATE TRIGGER scores_default_created_at
    AFTER INSERT ON scores FOR EACH ROW
    WHEN NEW.created_at IS NULL OR NEW.updated_at IS NULL
    BEGIN
      UPDATE scores
      SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
          updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
      WHERE id = NEW.id;
    END;

CREATE TRIGGER applications_touch_updated_at
    AFTER UPDATE ON applications FOR EACH ROW
    WHEN NEW.updated_at IS OLD.updated_at
    BEGIN
      UPDATE applications SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;

CREATE TRIGGER applications_invalidate_critic_after_rewrite
    AFTER UPDATE OF written_at ON applications FOR EACH ROW
    WHEN NEW.written_at IS NOT OLD.written_at AND (
      NEW.critic_verdict IS NOT NULL OR NEW.critic_score IS NOT NULL OR
      NEW.critic_notes IS NOT NULL OR NEW.critic_round IS NOT NULL OR
      NEW.reviewed_by IS NOT NULL OR NEW.critic_reviewed_at IS NOT NULL
    )
    BEGIN
      UPDATE applications
      SET status = CASE
            WHEN status IN ('ready', 'approved') THEN 'review'
            ELSE status
          END,
          critic_verdict = NULL,
          critic_score = NULL,
          critic_notes = NULL,
          critic_round = NULL,
          reviewed_by = NULL,
          critic_reviewed_at = NULL
      WHERE id = NEW.id;
    END;

CREATE TRIGGER applications_default_created_at
    AFTER INSERT ON applications FOR EACH ROW
    WHEN NEW.created_at IS NULL OR NEW.updated_at IS NULL
    BEGIN
      UPDATE applications
      SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
          updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
      WHERE id = NEW.id;
    END;

CREATE TRIGGER pending_user_messages_touch_updated_at
    AFTER UPDATE ON pending_user_messages FOR EACH ROW
    WHEN NEW.updated_at IS OLD.updated_at
    BEGIN
      UPDATE pending_user_messages SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;

CREATE TRIGGER pending_user_messages_default_created_at
    AFTER INSERT ON pending_user_messages FOR EACH ROW
    WHEN NEW.created_at IS NULL OR NEW.updated_at IS NULL
    BEGIN
      UPDATE pending_user_messages
      SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
          updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
      WHERE id = NEW.id;
    END;

CREATE TABLE _tombstones (
        table_name TEXT NOT NULL CHECK (table_name IN ('positions', 'scores', 'applications')),
        legacy_id INTEGER NOT NULL,
        deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (table_name, legacy_id)
    );

CREATE INDEX idx_tombstones_deleted_at ON _tombstones(deleted_at);

CREATE TRIGGER positions_tombstone
    BEFORE DELETE ON positions FOR EACH ROW
    BEGIN
      INSERT OR REPLACE INTO _tombstones (table_name, legacy_id, deleted_at)
      VALUES ('positions', OLD.id, CURRENT_TIMESTAMP);
    END;

CREATE TRIGGER scores_tombstone
    BEFORE DELETE ON scores FOR EACH ROW
    BEGIN
      INSERT OR REPLACE INTO _tombstones (table_name, legacy_id, deleted_at)
      VALUES ('scores', OLD.position_id, CURRENT_TIMESTAMP);
    END;

CREATE TRIGGER applications_tombstone
    BEFORE DELETE ON applications FOR EACH ROW
    BEGIN
      INSERT OR REPLACE INTO _tombstones (table_name, legacy_id, deleted_at)
      VALUES ('applications', OLD.position_id, CURRENT_TIMESTAMP);
    END;

CREATE INDEX idx_positions_loc_country_code ON positions(loc_country_code) WHERE loc_country_code IS NOT NULL;

CREATE INDEX idx_positions_work_mode ON positions(work_mode) WHERE work_mode IS NOT NULL;

CREATE INDEX idx_positions_loc_continent ON positions(loc_continent) WHERE loc_continent IS NOT NULL;

CREATE INDEX idx_positions_office_geocoded ON positions(office_geocoded) WHERE office_geocoded = 1;

CREATE TRIGGER cover_letter_request_effect
        AFTER UPDATE OF cl_path, cl_pdf_path ON applications
        WHEN EXISTS (
            SELECT 1 FROM positions p
             WHERE p.id = NEW.position_id
               AND p.write_requested = 1
               AND p.write_request_kind = 'cover_letter'
        ) AND (
            NEW.cl_path IS NOT OLD.cl_path OR
            NEW.cl_pdf_path IS NOT OLD.cl_pdf_path
        )
        BEGIN
            UPDATE positions
               SET write_requested = 0,
                   write_requested_at = CASE
                     WHEN strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime') >
                          COALESCE(write_requested_at, '')
                     THEN strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime')
                     ELSE strftime('%Y-%m-%d %H:%M:%f', write_requested_at,
                                   '+0.001 seconds')
                   END,
                   write_request_kind = NULL,
                   updated_at = CURRENT_TIMESTAMP
             WHERE id = NEW.position_id
               AND write_requested = 1
               AND write_request_kind = 'cover_letter';
        END;

CREATE INDEX idx_positions_open_expiry ON positions(expires_at) WHERE is_open = 1;

CREATE INDEX idx_positions_user_excluded ON positions(user_excluded_at) WHERE user_excluded_at IS NOT NULL;

CREATE INDEX idx_positions_recheck_requested ON positions(recheck_requested) WHERE recheck_requested = 1;

CREATE INDEX idx_positions_apply_requested ON positions(apply_requested) WHERE apply_requested = 1;

CREATE UNIQUE INDEX idx_position_tickets_active_rescore
            ON position_tickets(position_id, kind)
            WHERE kind = 'rescore' AND status IN ('open', 'assigned')
    ;

CREATE INDEX idx_pending_messages_unmirrored ON pending_user_messages(agent, id) WHERE chat_ts IS NULL;

CREATE INDEX idx_pending_messages_mirrored ON pending_user_messages(agent, chat_ts) WHERE chat_ts IS NOT NULL;

CREATE UNIQUE INDEX idx_positions_url_unique ON positions(url) WHERE url IS NOT NULL AND url <> '';

CREATE UNIQUE INDEX idx_scout_coordination_scout_started_unique ON scout_coordination(scout, started_at);

PRAGMA user_version = 7;
