"use client";

import Link from "next/link";
import {
  LandingI18nProvider,
  useLandingI18n,
} from "../components/landing/LandingI18n";
import LandingNav from "../components/landing/LandingNav";
import { LandingFooter } from "../components/landing/LandingCTA";
import ScrollToTop from "../components/landing/ScrollToTop";

const T = {
  it: {
    title: "Termini di Servizio",
    updated: "Ultimo aggiornamento: Aprile 2026",
    intro:
      "Utilizzando Job Hunter Team (JHT) accetti i seguenti termini e condizioni.",
    s1_title: "Licenza",
    s1_body:
      'JHT e distribuito sotto licenza MIT. Puoi usarlo, modificarlo e redistribuirlo liberamente, purche la licenza originale sia inclusa. Il software e fornito "cosi com\'e", senza garanzie di alcun tipo.',
    s2_title: "Uso consentito",
    s2_body:
      "JHT e progettato per assistere nella ricerca di lavoro attraverso agenti AI. L'uso del software per attivita illegali, spam, frode o per violare i termini di servizio di piattaforme terze (LinkedIn, Indeed, ecc.) e espressamente vietato.",
    s3_title: "Provider AI di terze parti",
    s3_body:
      "JHT orchestra una delle tre CLI supportate (Claude Code, Codex, Kimi) che richiedono un tuo abbonamento attivo col rispettivo provider (Anthropic, OpenAI, Moonshot). L'uso di quei servizi e soggetto ai loro termini e ai costi dell'abbonamento. Sei responsabile dell'account, del pagamento e dell'uso delle credenziali. JHT non intermedia ne fattura nulla.",
    s4_title: "Responsabilita",
    s4_body:
      "JHT genera contenuti (CV, cover letter, risposte) tramite intelligenza artificiale. Il contenuto generato potrebbe contenere errori o imprecisioni. Sei l'unico responsabile della revisione e dell'invio di qualsiasi materiale generato dal sistema.",
    s5_title: "Dati personali",
    s5_body:
      "Tutti i dati restano in locale sul tuo computer. Non raccogliamo ne trasmettiamo dati personali. Per maggiori dettagli, consulta la nostra Privacy Policy.",
    s6_title: "Modifiche ai termini",
    s6_body:
      "Ci riserviamo il diritto di aggiornare questi termini in qualsiasi momento. Le modifiche saranno pubblicate su questa pagina con la data di aggiornamento.",
    s7_title: "Contatti",
    s7_body: "Per domande sui termini di servizio, scrivi a support@jobhunterteam.ai.",
    nav_home: "Home",
    nav_terms: "Termini",
    nav_privacyPolicy: "Privacy Policy",
  },
  en: {
    title: "Terms of Service",
    updated: "Last updated: April 2026",
    intro:
      "By using Job Hunter Team (JHT) you agree to the following terms and conditions.",
    s1_title: "License",
    s1_body:
      'JHT is distributed under the MIT License. You can use, modify, and redistribute it freely, provided the original license is included. The software is provided "as is", without warranties of any kind.',
    s2_title: "Permitted use",
    s2_body:
      "JHT is designed to assist in job searching through AI agents. Using the software for illegal activities, spam, fraud, or to violate the terms of service of third-party platforms (LinkedIn, Indeed, etc.) is expressly prohibited.",
    s3_title: "Third-party AI providers",
    s3_body:
      "JHT orchestrates one of three supported CLIs (Claude Code, Codex, Kimi), each requiring your own active subscription with the respective provider (Anthropic, OpenAI, Moonshot). Use of those services is subject to their terms and subscription costs. You are responsible for the account, payment, and credential use. JHT does not intermediate or bill anything.",
    s4_title: "Liability",
    s4_body:
      "JHT generates content (CVs, cover letters, responses) through artificial intelligence. Generated content may contain errors or inaccuracies. You are solely responsible for reviewing and submitting any material generated by the system.",
    s5_title: "Personal data",
    s5_body:
      "All data stays locally on your computer. We do not collect or transmit personal data. For more details, see our Privacy Policy.",
    s6_title: "Changes to terms",
    s6_body:
      "We reserve the right to update these terms at any time. Changes will be posted on this page with the update date.",
    s7_title: "Contact",
    s7_body:
      "For questions about the terms of service, write to support@jobhunterteam.ai.",
    nav_home: "Home",
    nav_terms: "Terms",
    nav_privacyPolicy: "Privacy Policy",
  },
  hu: {
    title: "Szolgáltatási feltételek",
    updated: "Utolsó frissítés: 2026 április",
    intro:
      "A Job Hunter Team (JHT) használatával elfogadod az alábbi feltételeket.",
    s1_title: "Licenc",
    s1_body:
      'A JHT MIT licenc alatt kerül terjesztésre. Szabadon használhatod, módosíthatod és újraterjesztheted, feltéve, hogy az eredeti licenc benne van. A szoftver „ahogy van" alapon készült, mindennemű garancia nélkül.',
    s2_title: "Engedélyezett használat",
    s2_body:
      "A JHT az AI ügynökökön keresztül történő álláskeresés támogatására készült. A szoftver használata illegális tevékenységre, spamre, csalásra vagy harmadik féltől származó platformok (LinkedIn, Indeed, stb.) szolgáltatási feltételeinek megsértésére kifejezetten tilos.",
    s3_title: "Harmadik féltől származó AI szolgáltatók",
    s3_body:
      "A JHT három támogatott CLI valamelyikét vezérli (Claude Code, Codex, Kimi), és mindegyikhez saját aktív előfizetés kell az adott szolgáltatónál (Anthropic, OpenAI, Moonshot). E szolgáltatások használata az ő feltételeiknek és az előfizetési költségeiknek van alávetve. A fiók, fizetés és a hitelesítő adatok használatáért Te vagy felelős. A JHT nem közvetít és nem számláz semmit.",
    s4_title: "Felelősség",
    s4_body:
      "A JHT mesterséges intelligenciával generálja a tartalmat (önéletrajzok, motivációs levelek, válaszok). A generált tartalom hibákat vagy pontatlanságokat tartalmazhat. Egyedül Te vagy felelős a rendszer által generált anyagok átnézéséért és benyújtásáért.",
    s5_title: "Személyes adatok",
    s5_body:
      "Minden adat helyben marad a számítógépeden. Nem gyűjtünk és nem továbbítunk személyes adatokat. További részletekért olvasd el az Adatvédelmi irányelveket.",
    s6_title: "Feltételek változása",
    s6_body:
      "Fenntartjuk a jogot, hogy bármikor frissítsük ezeket a feltételeket. A változások ezen az oldalon lesznek közzétéve a frissítés dátumával.",
    s7_title: "Kapcsolat",
    s7_body:
      "A szolgáltatási feltételekkel kapcsolatos kérdések esetén írj az support@jobhunterteam.ai címre.",
    nav_home: "Főoldal",
    nav_terms: "Feltételek",
    nav_privacyPolicy: "Adatvédelmi szabályzat",
  },
  es: {
    title: "Términos del Servicio",
    updated: "Última actualización: Abril de 2026",
    intro:
      "Al utilizar Job Hunter Team (JHT) aceptas los siguientes términos y condiciones.",
    s1_title: "Licencia",
    s1_body:
      'JHT se distribuye bajo la Licencia MIT. Puedes usarlo, modificarlo y redistribuirlo libremente, siempre que se incluya la licencia original. El software se proporciona "tal cual", sin garantías de ningún tipo.',
    s2_title: "Uso permitido",
    s2_body:
      "JHT está diseñado para ayudar en la búsqueda de empleo mediante agentes de IA. El uso del software para actividades ilegales, spam, fraude o para violar los términos de servicio de plataformas de terceros (LinkedIn, Indeed, etc.) está expresamente prohibido.",
    s3_title: "Proveedores de IA de terceros",
    s3_body:
      "JHT orquesta una de las tres CLI compatibles (Claude Code, Codex, Kimi), cada una de las cuales requiere tu propia suscripción activa con el proveedor correspondiente (Anthropic, OpenAI, Moonshot). El uso de esos servicios está sujeto a sus términos y a los costes de la suscripción. Eres responsable de la cuenta, del pago y del uso de las credenciales. JHT no intermedia ni factura nada.",
    s4_title: "Responsabilidad",
    s4_body:
      "JHT genera contenido (CV, cartas de presentación, respuestas) mediante inteligencia artificial. El contenido generado puede contener errores o imprecisiones. Eres el único responsable de revisar y enviar cualquier material generado por el sistema.",
    s5_title: "Datos personales",
    s5_body:
      "Todos los datos permanecen localmente en tu ordenador. No recopilamos ni transmitimos datos personales. Para más detalles, consulta nuestra Política de Privacidad.",
    s6_title: "Cambios en los términos",
    s6_body:
      "Nos reservamos el derecho de actualizar estos términos en cualquier momento. Los cambios se publicarán en esta página con la fecha de actualización.",
    s7_title: "Contacto",
    s7_body:
      "Para preguntas sobre los términos del servicio, escribe a support@jobhunterteam.ai.",
    nav_home: "Inicio",
    nav_terms: "Términos",
    nav_privacyPolicy: "Política de privacidad",
  },
  de: {
    title: "Nutzungsbedingungen",
    updated: "Letzte Aktualisierung: April 2026",
    intro:
      "Durch die Nutzung von Job Hunter Team (JHT) akzeptierst du die folgenden Geschäftsbedingungen.",
    s1_title: "Lizenz",
    s1_body:
      'JHT wird unter der MIT-Lizenz vertrieben. Du kannst es frei verwenden, ändern und weiterverbreiten, sofern die ursprüngliche Lizenz beigefügt ist. Die Software wird „wie besehen" bereitgestellt, ohne jegliche Gewährleistung.',
    s2_title: "Zulässige Nutzung",
    s2_body:
      "JHT wurde entwickelt, um bei der Jobsuche durch KI-Agenten zu unterstützen. Die Nutzung der Software für illegale Aktivitäten, Spam, Betrug oder zur Verletzung der Nutzungsbedingungen von Drittanbieter-Plattformen (LinkedIn, Indeed usw.) ist ausdrücklich untersagt.",
    s3_title: "KI-Anbieter von Drittanbietern",
    s3_body:
      "JHT orchestriert eine der drei unterstützten CLIs (Claude Code, Codex, Kimi), die jeweils dein eigenes aktives Abonnement beim entsprechenden Anbieter (Anthropic, OpenAI, Moonshot) voraussetzen. Die Nutzung dieser Dienste unterliegt deren Bedingungen und Abonnementkosten. Du bist für das Konto, die Zahlung und die Verwendung der Anmeldedaten verantwortlich. JHT vermittelt nichts und stellt nichts in Rechnung.",
    s4_title: "Haftung",
    s4_body:
      "JHT erstellt Inhalte (Lebensläufe, Anschreiben, Antworten) mittels künstlicher Intelligenz. Generierte Inhalte können Fehler oder Ungenauigkeiten enthalten. Du allein bist für die Überprüfung und das Einreichen jeglichen vom System generierten Materials verantwortlich.",
    s5_title: "Personenbezogene Daten",
    s5_body:
      "Alle Daten verbleiben lokal auf deinem Computer. Wir erheben oder übertragen keine personenbezogenen Daten. Weitere Einzelheiten findest du in unserer Datenschutzerklärung.",
    s6_title: "Änderungen der Bedingungen",
    s6_body:
      "Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu aktualisieren. Änderungen werden auf dieser Seite mit dem Aktualisierungsdatum veröffentlicht.",
    s7_title: "Kontakt",
    s7_body:
      "Bei Fragen zu den Nutzungsbedingungen schreibe an support@jobhunterteam.ai.",
    nav_home: "Startseite",
    nav_terms: "Bedingungen",
    nav_privacyPolicy: "Datenschutzrichtlinie",
  },
  fr: {
    title: "Conditions d'Utilisation",
    updated: "Dernière mise à jour : avril 2026",
    intro:
      "En utilisant Job Hunter Team (JHT), vous acceptez les conditions générales suivantes.",
    s1_title: "Licence",
    s1_body:
      "JHT est distribué sous licence MIT. Vous pouvez l'utiliser, le modifier et le redistribuer librement, à condition d'inclure la licence originale. Le logiciel est fourni « tel quel », sans garantie d'aucune sorte.",
    s2_title: "Utilisation autorisée",
    s2_body:
      "JHT est conçu pour aider à la recherche d'emploi grâce à des agents IA. L'utilisation du logiciel pour des activités illégales, du spam, de la fraude ou pour violer les conditions d'utilisation de plateformes tierces (LinkedIn, Indeed, etc.) est expressément interdite.",
    s3_title: "Fournisseurs d'IA tiers",
    s3_body:
      "JHT orchestre l'une des trois CLI prises en charge (Claude Code, Codex, Kimi), chacune nécessitant votre propre abonnement actif auprès du fournisseur concerné (Anthropic, OpenAI, Moonshot). L'utilisation de ces services est soumise à leurs conditions et aux coûts de l'abonnement. Vous êtes responsable du compte, du paiement et de l'utilisation des identifiants. JHT n'intermédie rien et ne facture rien.",
    s4_title: "Responsabilité",
    s4_body:
      "JHT génère du contenu (CV, lettres de motivation, réponses) au moyen de l'intelligence artificielle. Le contenu généré peut contenir des erreurs ou des inexactitudes. Vous êtes seul responsable de la relecture et de l'envoi de tout matériel généré par le système.",
    s5_title: "Données personnelles",
    s5_body:
      "Toutes les données restent en local sur votre ordinateur. Nous ne collectons ni ne transmettons de données personnelles. Pour plus de détails, consultez notre Politique de Confidentialité.",
    s6_title: "Modifications des conditions",
    s6_body:
      "Nous nous réservons le droit de mettre à jour ces conditions à tout moment. Les modifications seront publiées sur cette page avec la date de mise à jour.",
    s7_title: "Contact",
    s7_body:
      "Pour toute question concernant les conditions d'utilisation, écrivez à support@jobhunterteam.ai.",
    nav_home: "Accueil",
    nav_terms: "Conditions",
    nav_privacyPolicy: "Politique de confidentialité",
  },
  pt: {
    title: "Termos de Serviço",
    updated: "Última atualização: abril de 2026",
    intro:
      "Ao utilizar o Job Hunter Team (JHT), aceita os seguintes termos e condições.",
    s1_title: "Licença",
    s1_body:
      'O JHT é distribuído sob a Licença MIT. Pode usá-lo, modificá-lo e redistribuí-lo livremente, desde que a licença original seja incluída. O software é fornecido "tal como está", sem garantias de qualquer tipo.',
    s2_title: "Utilização permitida",
    s2_body:
      "O JHT foi concebido para ajudar na procura de emprego através de agentes de IA. A utilização do software para atividades ilegais, spam, fraude ou para violar os termos de serviço de plataformas de terceiros (LinkedIn, Indeed, etc.) é expressamente proibida.",
    s3_title: "Fornecedores de IA de terceiros",
    s3_body:
      "O JHT orquestra uma das três CLI suportadas (Claude Code, Codex, Kimi), cada uma exigindo a sua própria subscrição ativa junto do respetivo fornecedor (Anthropic, OpenAI, Moonshot). A utilização desses serviços está sujeita aos seus termos e aos custos da subscrição. É responsável pela conta, pelo pagamento e pela utilização das credenciais. O JHT não intermedeia nem fatura nada.",
    s4_title: "Responsabilidade",
    s4_body:
      "O JHT gera conteúdo (CV, cartas de apresentação, respostas) através de inteligência artificial. O conteúdo gerado pode conter erros ou imprecisões. É o único responsável pela revisão e pelo envio de qualquer material gerado pelo sistema.",
    s5_title: "Dados pessoais",
    s5_body:
      "Todos os dados permanecem localmente no seu computador. Não recolhemos nem transmitimos dados pessoais. Para mais detalhes, consulte a nossa Política de Privacidade.",
    s6_title: "Alterações aos termos",
    s6_body:
      "Reservamo-nos o direito de atualizar estes termos a qualquer momento. As alterações serão publicadas nesta página com a data de atualização.",
    s7_title: "Contacto",
    s7_body:
      "Para questões sobre os termos de serviço, escreva para support@jobhunterteam.ai.",
    nav_home: "Início",
    nav_terms: "Termos",
    nav_privacyPolicy: "Política de privacidade",
  },
};

type TKey = keyof typeof T.it;

function Section({ title, body }: { title: string; body: string }) {
  return (
    <div className="mb-6">
      <h2 className="text-[14px] font-bold text-[var(--color-white)] mb-2">
        {title}
      </h2>
      <p className="text-[12px] text-[var(--color-muted)] leading-relaxed">
        {body}
      </p>
    </div>
  );
}

function TermsContent() {
  const { lang } = useLandingI18n();
  const tx = T[lang as keyof typeof T] ?? T.en;
  const t = (k: TKey) => tx[k] ?? k;

  const sections: [TKey, TKey][] = [
    ["s1_title", "s1_body"],
    ["s2_title", "s2_body"],
    ["s3_title", "s3_body"],
    ["s4_title", "s4_body"],
    ["s5_title", "s5_body"],
    ["s6_title", "s6_body"],
    ["s7_title", "s7_body"],
  ];

  return (
    <main style={{ position: "relative", zIndex: 1 }}>
      <LandingNav />
      <div className="max-w-3xl mx-auto px-5 pt-32 pb-20">
        <div className="mb-8 pb-6 border-b border-[var(--color-border)]">
          <div className="flex items-center gap-2 mb-3">
            <Link
              href="/"
              className="text-[10px] text-[var(--color-dim)] hover:text-[var(--color-muted)] no-underline transition-colors"
            >
              {t("nav_home")}
            </Link>
            <span className="text-[var(--color-border)]">/</span>
            <span className="text-[10px] text-[var(--color-muted)]">
              {t("nav_terms")}
            </span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-[var(--color-white)]">
            {t("title")}
          </h1>
          <p className="text-[var(--color-dim)] text-[10px] mt-2">
            {t("updated")}
          </p>
          <p className="text-[var(--color-muted)] text-[12px] mt-3 leading-relaxed">
            {t("intro")}
          </p>
        </div>

        {sections.map(([titleKey, bodyKey]) => (
          <Section key={titleKey} title={t(titleKey)} body={t(bodyKey)} />
        ))}

        <div className="mt-12 pt-6 border-t border-[var(--color-border)] flex items-center justify-between">
          <Link
            href="/privacy"
            className="text-[11px] text-[var(--color-dim)] hover:text-[var(--color-green)] transition-colors no-underline"
          >
            &larr; {t("nav_privacyPolicy")}
          </Link>
          <Link
            href="/"
            className="text-[11px] text-[var(--color-dim)] hover:text-[var(--color-green)] transition-colors no-underline"
          >
            {t("nav_home")} &rarr;
          </Link>
        </div>
      </div>
      <LandingFooter />
      <ScrollToTop />
    </main>
  );
}

export default function TermsPage() {
  return (
    <LandingI18nProvider>
      <TermsContent />
    </LandingI18nProvider>
  );
}
