-- 043_position_tickets.sql
-- Ticket utente→team su una posizione (2026-06-18). Dalla pagina dettaglio
-- l'utente scrive una richiesta testuale libera → ticket 'open'; il Capitano lo
-- assegna a un agente ('assigned'); l'agente risolve con response_text
-- ('resolved'). L'utente vede richiesta+risposta in una sezione dedicata.
-- Mirror SQLite: shared/skills/_db.py (CREATE TABLE position_tickets) +
-- write-ops shared/skills/ticket.py.
-- NB il sync bidirezionale cloud↔VPS dei ticket è un FOLLOW-UP: per ora la
-- feature gira sul path locale (dashboard nel container). Questa tabella + RLS
-- preparano il cloud. RLS per-utente come team_commands (mig 012).

CREATE TABLE IF NOT EXISTS position_tickets (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    position_legacy_id INTEGER NOT NULL,
    request_text       TEXT NOT NULL,
    kind               TEXT NOT NULL DEFAULT 'custom',
    status             TEXT NOT NULL DEFAULT 'open'
                         CHECK (status IN ('open','assigned','resolved')),
    assigned_agent     TEXT,
    response_text      TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    assigned_at        TIMESTAMPTZ,
    resolved_at        TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_position_tickets_user_pos
    ON position_tickets(user_id, position_legacy_id);
CREATE INDEX IF NOT EXISTS idx_position_tickets_user_status
    ON position_tickets(user_id, status);

ALTER TABLE position_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users select own position tickets"
    ON position_tickets FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "users insert own position tickets"
    ON position_tickets FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users update own position tickets"
    ON position_tickets FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
