-- 054_team_directives.sql
-- Bacheca del team: ordini/direttive PERMANENTI dell'utente (strategia/formazione,
-- policy operative — es. "modalità mantenimento: stop scouting, CV solo 90+").
-- Restano attive finché l'utente non le cambia; il Capitano le rilegge a ogni
-- riavvio (C-21). Mirror SQLite: shared/skills/_db.py (team_directives) +
-- write-ops shared/skills/team_directives.py. Editabile dalla dashboard web, con
-- round-trip cloud↔VPS via la colonna LOCALE `cloud_id` (come position_tickets,
-- mig 043). RLS per-utente come position_tickets.

CREATE TABLE IF NOT EXISTS team_directives (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    body        TEXT NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'order'
                  CHECK (kind IN ('order','strategy','formation','note')),
    status      TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','archived')),
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_by  TEXT NOT NULL DEFAULT 'user',   -- user | capitano | assistente
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_team_directives_user_status
    ON team_directives(user_id, status);

ALTER TABLE team_directives ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users select own team directives"
    ON team_directives FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "users insert own team directives"
    ON team_directives FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users update own team directives"
    ON team_directives FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
