-- H-08 migration-history anchor: intentionally no executable SQL.
-- Remote identity: 20260810213953 / landing_hits
-- Canonical effect: supabase/migrations/068_landing_hits.sql
-- Remote statements MD5: dcd2b0519ef96a545eeb8d5bf433df62
--
-- The linked database already records this timestamped migration. Keeping
-- the exact identity locally reconciles history without replaying old DDL;
-- the canonical migration (or forward-only 081) owns the final schema.
