-- H-08 migration-history anchor: intentionally no executable SQL.
-- Remote identity: 20260531114803 / positions_write_requested
-- Canonical effect: supabase/migrations/027_positions_write_requested.sql
-- Remote statements MD5: 7714f32389e26a33a0322b803f357b91
--
-- The linked database already records this timestamped migration. Keeping
-- the exact identity locally reconciles history without replaying old DDL;
-- the canonical migration (or forward-only 081) owns the final schema.
