-- H-08 migration-history anchor: intentionally no executable SQL.
-- Remote identity: 20260618160133 / 041_positions_user_excluded
-- Canonical effect: supabase/migrations/041_positions_user_excluded.sql
-- Remote statements MD5: e1b514ec1ca352505c6ddfe2b8dc1af3
--
-- The linked database already records this timestamped migration. Keeping
-- the exact identity locally reconciles history without replaying old DDL;
-- the canonical migration (or forward-only 081) owns the final schema.
