-- H-08 migration-history anchor: intentionally no executable SQL.
-- Remote identity: 20260605230132 / 035_profile_blocks
-- Canonical effect: supabase/migrations/035_profile_blocks.sql
-- Remote statements MD5: 6ccceeb7ac7596e7538593ef086fe728
--
-- The linked database already records this timestamped migration. Keeping
-- the exact identity locally reconciles history without replaying old DDL;
-- the canonical migration (or forward-only 081) owns the final schema.
