-- H-08 migration-history anchor: intentionally no executable SQL.
-- Remote identity: 20260628141024 / 048_position_tickets_realtime
-- Canonical effect: supabase/migrations/048_position_tickets_realtime.sql
-- Remote statements MD5: 3cd90b7a2dea084cfd235259cc1923b3
--
-- The linked database already records this timestamped migration. Keeping
-- the exact identity locally reconciles history without replaying old DDL;
-- the canonical migration (or forward-only 081) owns the final schema.
