// Capitoli e fasi della guida di setup.
//
// ⚠️ CONTENUTO PROVVISORIO. La struttura delle fasi e il copy inglese
// definitivi arrivano da HQ-DOCS; questo file è l'impalcatura su cui
// innestarli: gli `id` sono stabili, le fasi già dichiarano il loro OS, la
// loro schermata (per id, dal registro) e i loro link operativi. Sostituire
// un testo qui non tocca il layout, e aggiungere una fase è una voce in più
// in un array.
//
// I contenuti attuali sono tratti dai percorsi già verificati in
// `app/tutorials/tutorial-content.ts` e dalle prove end-to-end su Linux,
// Windows e macOS: sono veri, non riempitivi, ma vanno riletti da DOCS.

import {
  CLI_INSTALL_CMD,
  DOCKER_URL,
  DOCS_DASHBOARD,
  DOCS_PRIVACY,
  DOCS_PROVIDER,
  DOWNLOAD_PAGE,
} from "./guide-config";
import type { GuideChapter } from "./guide-types";

export const GUIDE_CHAPTERS: GuideChapter[] = [
  {
    id: "before-you-start",
    title: {
      en: "Before you start",
      it: "Prima di iniziare",
      es: "Antes de empezar",
      fr: "Avant de commencer",
      de: "Bevor du anfängst",
      pt: "Antes de começar",
      hu: "Mielőtt elkezded",
    },
    summary: {
      en: "What the machine needs, and the one dependency that matters.",
      it: "Cosa serve alla macchina, e l'unica dipendenza che conta.",
      es: "Qué necesita el ordenador, y la única dependencia que importa.",
      fr: "Ce dont la machine a besoin, et la seule dépendance qui compte.",
      de: "Was der Rechner braucht — und die eine Abhängigkeit, die zählt.",
      pt: "O que a máquina precisa, e a única dependência que importa.",
      hu: "Mire van szüksége a gépnek, és az egyetlen függőség, ami számít.",
    },
    phases: [
      {
        id: "requirements",
        os: "all",
        title: {
          en: "Check the machine",
          it: "Controlla la macchina",
          es: "Comprueba el ordenador",
          fr: "Vérifiez la machine",
          de: "Prüfe den Rechner",
          pt: "Verifica a máquina",
          hu: "Ellenőrizd a gépet",
        },
        body: {
          en: "4 GB of RAM, 2 CPU cores and about 35 GB of free disk are the minimum; 8 GB and 4 cores make it comfortable. The team runs on your own machine, so it uses your own resources.",
          it: "4 GB di RAM, 2 core e circa 35 GB di disco liberi sono il minimo; con 8 GB e 4 core si sta comodi. Il team gira sulla tua macchina, quindi usa le tue risorse.",
          es: "4 GB de RAM, 2 núcleos y unos 35 GB de disco libre son el mínimo; con 8 GB y 4 núcleos se trabaja cómodo. El equipo funciona en tu ordenador, así que usa tus recursos.",
          fr: "4 Go de RAM, 2 cœurs et environ 35 Go d'espace disque libre sont le minimum ; 8 Go et 4 cœurs sont confortables. L'équipe tourne sur votre machine et utilise donc vos ressources.",
          de: "4 GB RAM, 2 CPU-Kerne und rund 35 GB freier Speicher sind das Minimum; mit 8 GB und 4 Kernen läuft es bequem. Das Team läuft auf deinem Rechner und nutzt daher deine Ressourcen.",
          pt: "4 GB de RAM, 2 núcleos e cerca de 35 GB de disco livre são o mínimo; com 8 GB e 4 núcleos fica confortável. A equipa corre na tua máquina, por isso usa os teus recursos.",
          hu: "4 GB RAM, 2 processzormag és nagyjából 35 GB szabad lemezterület a minimum; 8 GB és 4 mag mellett kényelmes. A csapat a saját gépeden fut, tehát a te erőforrásaidat használja.",
        },
      },
      {
        id: "docker",
        os: "all",
        title: {
          en: "Install Docker",
          it: "Installa Docker",
          es: "Instala Docker",
          fr: "Installez Docker",
          de: "Installiere Docker",
          pt: "Instala o Docker",
          hu: "Telepítsd a Dockert",
        },
        body: {
          en: "Docker is the only real dependency: the team lives inside a container on your machine. If you do not have it yet, install it now — doing it later stops the setup halfway.",
          it: "Docker è l'unica vera dipendenza: il team vive dentro un container sulla tua macchina. Se non ce l'hai, installalo adesso — farlo dopo blocca il setup a metà.",
          es: "Docker es la única dependencia real: el equipo vive dentro de un contenedor en tu ordenador. Si aún no lo tienes, instálalo ahora — hacerlo después detiene la configuración a medias.",
          fr: "Docker est la seule vraie dépendance : l'équipe vit dans un conteneur sur votre machine. Si vous ne l'avez pas encore, installez-le maintenant — le faire plus tard bloque la configuration à mi-chemin.",
          de: "Docker ist die einzige echte Abhängigkeit: Das Team lebt in einem Container auf deinem Rechner. Wenn du es noch nicht hast, installiere es jetzt — später bleibt die Einrichtung auf halbem Weg stehen.",
          pt: "O Docker é a única dependência real: a equipa vive dentro de um contentor na tua máquina. Se ainda não o tens, instala-o agora — deixá-lo para depois trava a configuração a meio.",
          hu: "A Docker az egyetlen valódi függőség: a csapat egy konténerben él a gépeden. Ha még nincs meg, telepítsd most — később a beállítás félúton megáll.",
        },
        screen: { screenId: "docker-check" },
        links: [
          {
            kind: "external",
            href: DOCKER_URL,
            label: {
              en: "Don't have Docker? Get it here",
              it: "Non hai Docker? Scaricalo da qui",
              es: "¿No tienes Docker? Descárgalo aquí",
              fr: "Vous n'avez pas Docker ? Téléchargez-le ici",
              de: "Kein Docker? Hier herunterladen",
              pt: "Não tens Docker? Descarrega-o aqui",
              hu: "Nincs Dockered? Töltsd le itt",
            },
          },
        ],
      },
    ],
  },
  {
    id: "download",
    title: {
      en: "Download",
      it: "Scarica",
      es: "Descarga",
      fr: "Téléchargement",
      de: "Herunterladen",
      pt: "Descarregar",
      hu: "Letöltés",
    },
    summary: {
      en: "Get the app for your system and open it the first time.",
      it: "Prendi l'app per il tuo sistema e aprila la prima volta.",
      es: "Consigue la aplicación para tu sistema y ábrela por primera vez.",
      fr: "Récupérez l'application pour votre système et ouvrez-la une première fois.",
      de: "Hol dir die App für dein System und öffne sie zum ersten Mal.",
      pt: "Obtém a aplicação para o teu sistema e abre-a pela primeira vez.",
      hu: "Szerezd be a rendszeredhez való alkalmazást, és nyisd meg először.",
    },
    phases: [
      {
        id: "download-app",
        os: "all",
        title: {
          en: "Download the app",
          it: "Scarica l'app",
          es: "Descarga la aplicación",
          fr: "Téléchargez l'application",
          de: "Lade die App herunter",
          pt: "Descarrega a aplicação",
          hu: "Töltsd le az alkalmazást",
        },
        body: {
          en: "One click on your system starts the download of the latest release. If you would rather stay in a terminal, the one-line install does the same job.",
          it: "Un clic sul tuo sistema avvia il download dell'ultima versione. Se preferisci restare a terminale, l'installazione in una riga fa lo stesso lavoro.",
          es: "Un clic en tu sistema inicia la descarga de la última versión. Si prefieres el terminal, la instalación en una línea hace lo mismo.",
          fr: "Un clic sur votre système lance le téléchargement de la dernière version. Si vous préférez le terminal, l'installation en une ligne fait la même chose.",
          de: "Ein Klick auf dein System startet den Download der neuesten Version. Wer lieber im Terminal bleibt, nimmt die Ein-Zeilen-Installation.",
          pt: "Um clique no teu sistema inicia a transferência da última versão. Se preferes o terminal, a instalação numa linha faz o mesmo.",
          hu: "Egy kattintás a rendszeredre elindítja a legfrissebb kiadás letöltését. Ha inkább a terminálnál maradnál, az egysoros telepítés ugyanezt teszi.",
        },
        screen: { screenId: "download-page" },
        links: [
          {
            kind: "download",
            label: {
              en: "Download for this system",
              it: "Scarica per questo sistema",
              es: "Descargar para este sistema",
              fr: "Télécharger pour ce système",
              de: "Für dieses System herunterladen",
              pt: "Descarregar para este sistema",
              hu: "Letöltés ehhez a rendszerhez",
            },
          },
          {
            kind: "internal",
            href: DOWNLOAD_PAGE,
            label: {
              en: "Open the Download page",
              it: "Apri la pagina Download",
              es: "Abrir la página de Descarga",
              fr: "Ouvrir la page de téléchargement",
              de: "Download-Seite öffnen",
              pt: "Abrir a página de Download",
              hu: "A Letöltés oldal megnyitása",
            },
          },
          {
            kind: "command",
            command: CLI_INSTALL_CMD,
            label: {
              en: "Or install from the terminal",
              it: "Oppure installa da terminale",
              es: "O instala desde el terminal",
              fr: "Ou installez depuis le terminal",
              de: "Oder im Terminal installieren",
              pt: "Ou instala a partir do terminal",
              hu: "Vagy telepítsd terminálból",
            },
          },
        ],
      },
      {
        id: "open-macos",
        os: ["macos"],
        title: {
          en: "Unzip and open",
          it: "Scompatta e apri",
          es: "Descomprime y abre",
          fr: "Décompressez et ouvrez",
          de: "Entpacken und öffnen",
          pt: "Descompacta e abre",
          hu: "Csomagold ki és nyisd meg",
        },
        body: {
          en: "Unzip the downloaded archive and open the app with a double click. The macOS build is signed and notarized, so no security warning should stop you.",
          it: "Scompatta l'archivio scaricato e apri l'app con un doppio clic. La build macOS è firmata e notarizzata, quindi non dovrebbe fermarti nessun avviso di sicurezza.",
          es: "Descomprime el archivo descargado y abre la aplicación con doble clic. La versión de macOS está firmada y notarizada, así que ningún aviso de seguridad debería detenerte.",
          fr: "Décompressez l'archive téléchargée et ouvrez l'application d'un double clic. La version macOS est signée et notariée : aucun avertissement de sécurité ne devrait vous arrêter.",
          de: "Entpacke das heruntergeladene Archiv und öffne die App mit einem Doppelklick. Der macOS-Build ist signiert und notarisiert, es sollte dich also keine Sicherheitswarnung aufhalten.",
          pt: "Descompacta o ficheiro transferido e abre a aplicação com duplo clique. A versão macOS está assinada e notarizada, por isso nenhum aviso de segurança te deve travar.",
          hu: "Csomagold ki a letöltött archívumot, és nyisd meg az alkalmazást dupla kattintással. A macOS-változat aláírt és hitelesített, így semmilyen biztonsági figyelmeztetés nem állíthat meg.",
        },
      },
      {
        id: "open-windows",
        os: ["windows"],
        title: {
          en: "Run the installer",
          it: "Esegui l'installer",
          es: "Ejecuta el instalador",
          fr: "Lancez l'installeur",
          de: "Starte den Installer",
          pt: "Executa o instalador",
          hu: "Futtasd a telepítőt",
        },
        body: {
          en: "Run the downloaded .exe. Windows shows a SmartScreen warning because the build is not signed yet: continue only if the file came from the official site.",
          it: "Esegui il file .exe scaricato. Windows mostra un avviso SmartScreen perché la build non è ancora firmata: prosegui solo se il file arriva dal sito ufficiale.",
          es: "Ejecuta el .exe descargado. Windows muestra un aviso de SmartScreen porque la versión aún no está firmada: continúa solo si el archivo viene del sitio oficial.",
          fr: "Lancez le fichier .exe téléchargé. Windows affiche un avertissement SmartScreen car la version n'est pas encore signée : continuez seulement si le fichier vient du site officiel.",
          de: "Starte die heruntergeladene .exe. Windows zeigt eine SmartScreen-Warnung, weil der Build noch nicht signiert ist: Fahre nur fort, wenn die Datei von der offiziellen Website stammt.",
          pt: "Executa o .exe transferido. O Windows mostra um aviso do SmartScreen porque a versão ainda não está assinada: continua só se o ficheiro veio do site oficial.",
          hu: "Futtasd a letöltött .exe fájlt. A Windows SmartScreen-figyelmeztetést mutat, mert a build még nincs aláírva: csak akkor folytasd, ha a fájl a hivatalos oldalról származik.",
        },
        warning: {
          en: "The warning is expected. Check the source of the file, not the warning.",
          it: "L'avviso è previsto. Controlla da dove viene il file, non l'avviso.",
          es: "El aviso es esperado. Comprueba de dónde viene el archivo, no el aviso.",
          fr: "L'avertissement est attendu. Vérifiez l'origine du fichier, pas l'avertissement.",
          de: "Die Warnung ist zu erwarten. Prüfe die Herkunft der Datei, nicht die Warnung.",
          pt: "O aviso é esperado. Verifica a origem do ficheiro, não o aviso.",
          hu: "A figyelmeztetés várható. A fájl forrását ellenőrizd, ne a figyelmeztetést.",
        },
      },
      {
        id: "open-linux",
        os: ["linux"],
        title: {
          en: "Extract and allow it to run",
          it: "Estrai e consenti l'esecuzione",
          es: "Extrae y permite la ejecución",
          fr: "Extrayez et autorisez l'exécution",
          de: "Entpacken und Ausführung erlauben",
          pt: "Extrai e permite a execução",
          hu: "Csomagold ki és engedélyezd a futtatást",
        },
        body: {
          en: "Extract the .tar.gz archive, then make the binary executable before running it. Your desktop may ask for confirmation the first time.",
          it: "Estrai l'archivio .tar.gz, poi rendi eseguibile il binario prima di lanciarlo. Il desktop può chiederti una conferma la prima volta.",
          es: "Extrae el archivo .tar.gz y luego haz ejecutable el binario antes de lanzarlo. Tu escritorio puede pedirte confirmación la primera vez.",
          fr: "Extrayez l'archive .tar.gz, puis rendez le binaire exécutable avant de le lancer. Votre bureau peut demander une confirmation la première fois.",
          de: "Entpacke das .tar.gz-Archiv und mach die Binärdatei ausführbar, bevor du sie startest. Dein Desktop fragt beim ersten Mal eventuell nach.",
          pt: "Extrai o ficheiro .tar.gz e depois torna o binário executável antes de o lançar. O teu ambiente de trabalho pode pedir confirmação da primeira vez.",
          hu: "Csomagold ki a .tar.gz archívumot, majd tedd futtathatóvá a binárist, mielőtt elindítod. Az asztali környezet első alkalommal megerősítést kérhet.",
        },
        links: [
          {
            kind: "command",
            command:
              "chmod +x job-hunter-team.x86_64 && ./job-hunter-team.x86_64",
            label: {
              en: "Make it executable and run it",
              it: "Rendilo eseguibile e avvialo",
              es: "Hazlo ejecutable y ejecútalo",
              fr: "Rendez-le exécutable et lancez-le",
              de: "Ausführbar machen und starten",
              pt: "Torna-o executável e executa-o",
              hu: "Tedd futtathatóvá és indítsd el",
            },
          },
        ],
      },
    ],
  },
  {
    id: "first-launch",
    title: {
      en: "First launch",
      it: "Primo avvio",
      es: "Primer inicio",
      fr: "Premier lancement",
      de: "Erster Start",
      pt: "Primeiro arranque",
      hu: "Első indítás",
    },
    summary: {
      en: "Choose the language, then look around before anything starts.",
      it: "Scegli la lingua, poi guardati intorno prima che parta qualcosa.",
      es: "Elige el idioma y luego mira alrededor antes de que arranque nada.",
      fr: "Choisissez la langue, puis regardez autour de vous avant que quoi que ce soit démarre.",
      de: "Wähle die Sprache und sieh dich um, bevor irgendetwas startet.",
      pt: "Escolhe o idioma e depois olha à volta antes de arrancar seja o que for.",
      hu: "Válaszd ki a nyelvet, majd nézz körül, mielőtt bármi elindulna.",
    },
    phases: [
      {
        id: "choose-language",
        os: "all",
        title: {
          en: "Choose the language",
          it: "Scegli la lingua",
          es: "Elige el idioma",
          fr: "Choisissez la langue",
          de: "Sprache wählen",
          pt: "Escolhe o idioma",
          hu: "Válassz nyelvet",
        },
        body: {
          en: "The language screen comes before everything else: English is preselected, and confirming is required. The choice is saved for the next launches.",
          it: "La schermata della lingua viene prima di tutto: l'inglese è preselezionato e la conferma è obbligatoria. La scelta resta salvata per gli avvii successivi.",
          es: "La pantalla de idioma va antes que todo: el inglés está preseleccionado y hay que confirmar. La elección se guarda para los siguientes inicios.",
          fr: "L'écran de la langue vient avant tout : l'anglais est présélectionné et la confirmation est obligatoire. Le choix est conservé pour les lancements suivants.",
          de: "Der Sprachbildschirm kommt vor allem anderen: Englisch ist vorausgewählt, bestätigen ist Pflicht. Die Wahl bleibt für die nächsten Starts gespeichert.",
          pt: "O ecrã do idioma vem antes de tudo: o inglês está pré-selecionado e confirmar é obrigatório. A escolha fica guardada para os arranques seguintes.",
          hu: "A nyelvi képernyő minden mást megelőz: az angol előre ki van jelölve, és a megerősítés kötelező. A választás a következő indításokra is megmarad.",
        },
        screen: { screenId: "language-choice" },
      },
      {
        id: "look-around",
        os: "all",
        title: {
          en: "Look around the office",
          it: "Gira per l'ufficio",
          es: "Recorre la oficina",
          fr: "Faites le tour du bureau",
          de: "Sieh dich im Büro um",
          pt: "Percorre o escritório",
          hu: "Járd körbe az irodát",
        },
        body: {
          en: "You are in before any setup. Walking around, reading the sample conversations and the example positions does not start a live team and does not use your provider.",
          it: "Sei dentro prima di qualsiasi setup. Girare, leggere le conversazioni di esempio e le posizioni di prova non avvia nessun team vero e non consuma il tuo provider.",
          es: "Ya estás dentro antes de configurar nada. Moverte, leer las conversaciones de ejemplo y las posiciones de muestra no arranca ningún equipo real ni gasta tu proveedor.",
          fr: "Vous êtes à l'intérieur avant toute configuration. Circuler, lire les conversations d'exemple et les offres de démonstration ne lance aucune équipe réelle et ne consomme pas votre fournisseur.",
          de: "Du bist schon drin, bevor irgendetwas eingerichtet ist. Herumlaufen, Beispielgespräche und Beispielstellen lesen startet kein echtes Team und verbraucht deinen Anbieter nicht.",
          pt: "Já estás dentro antes de configurares o que quer que seja. Andar, ler as conversas de exemplo e as posições de amostra não arranca nenhuma equipa real nem gasta o teu provedor.",
          hu: "Már bent vagy, mielőtt bármit beállítanál. A körbejárás, a mintabeszélgetések és a példapozíciók olvasása nem indít valódi csapatot, és nem fogyasztja a szolgáltatód.",
        },
        screen: { screenId: "office-overview" },
      },
      {
        id: "departments",
        os: "all",
        title: {
          en: "See who does what",
          it: "Guarda chi fa cosa",
          es: "Mira quién hace qué",
          fr: "Voyez qui fait quoi",
          de: "Sieh, wer was macht",
          pt: "Vê quem faz o quê",
          hu: "Nézd meg, ki mit csinál",
        },
        body: {
          en: "Each desk is a role: someone searches, someone scores against your CV, someone writes, someone reviews. Knowing the layout makes the rest of the setup easier to read.",
          it: "Ogni scrivania è un ruolo: c'è chi cerca, chi dà i punteggi rispetto al tuo CV, chi scrive, chi rivede. Conoscere la pianta rende il resto del setup più leggibile.",
          es: "Cada escritorio es un rol: alguien busca, alguien puntúa frente a tu CV, alguien escribe, alguien revisa. Conocer el plano hace más legible el resto de la configuración.",
          fr: "Chaque poste est un rôle : quelqu'un cherche, quelqu'un note par rapport à votre CV, quelqu'un rédige, quelqu'un relit. Connaître le plan rend la suite plus lisible.",
          de: "Jeder Schreibtisch ist eine Rolle: Jemand sucht, jemand bewertet gegen deinen Lebenslauf, jemand schreibt, jemand prüft. Wer den Grundriss kennt, versteht den Rest der Einrichtung leichter.",
          pt: "Cada secretária é um papel: alguém procura, alguém pontua face ao teu CV, alguém escreve, alguém revê. Conhecer a planta torna o resto da configuração mais legível.",
          hu: "Minden asztal egy szerep: valaki keres, valaki az önéletrajzodhoz mér, valaki ír, valaki ellenőriz. Ha ismered az elrendezést, a beállítás többi része is érthetőbb.",
        },
        screen: { screenId: "departments" },
      },
    ],
  },
  {
    id: "setup",
    title: {
      en: "Set up the team",
      it: "Configura il team",
      es: "Configura el equipo",
      fr: "Configurez l'équipe",
      de: "Team einrichten",
      pt: "Configura a equipa",
      hu: "Állítsd be a csapatot",
    },
    summary: {
      en: "The checklist, the provider, and the CV the team works from.",
      it: "La checklist, il provider e il CV da cui la squadra lavora.",
      es: "La lista, el proveedor y el CV con el que trabaja el equipo.",
      fr: "La liste, le fournisseur et le CV à partir duquel l'équipe travaille.",
      de: "Die Checkliste, der Anbieter und der Lebenslauf, mit dem das Team arbeitet.",
      pt: "A lista, o provedor e o CV a partir do qual a equipa trabalha.",
      hu: "Az ellenőrzőlista, a szolgáltató és az önéletrajz, amelyből a csapat dolgozik.",
    },
    phases: [
      {
        id: "open-checklist",
        os: "all",
        title: {
          en: "Open the setup checklist",
          it: "Apri la checklist di setup",
          es: "Abre la lista de configuración",
          fr: "Ouvrez la liste de configuration",
          de: "Öffne die Einrichtungs-Checkliste",
          pt: "Abre a lista de configuração",
          hu: "Nyisd meg a beállítási listát",
        },
        body: {
          en: "Choose to activate the team and the checklist appears: it lists every requirement and its state. Nothing here is irreversible — you can close and come back.",
          it: "Scegli di attivare il team e compare la checklist: elenca ogni requisito e il suo stato. Niente qui è irreversibile: puoi chiudere e tornare.",
          es: "Elige activar el equipo y aparece la lista: enumera cada requisito y su estado. Nada aquí es irreversible: puedes cerrar y volver.",
          fr: "Choisissez d'activer l'équipe et la liste apparaît : elle énumère chaque prérequis et son état. Rien n'est irréversible : vous pouvez fermer et revenir.",
          de: "Wähle, das Team zu aktivieren, und die Checkliste erscheint: Sie führt jede Voraussetzung und ihren Status auf. Nichts davon ist endgültig — du kannst schließen und zurückkommen.",
          pt: "Escolhe ativar a equipa e a lista aparece: enumera cada requisito e o seu estado. Nada aqui é irreversível: podes fechar e voltar.",
          hu: "Válaszd a csapat aktiválását, és megjelenik az ellenőrzőlista: felsorol minden követelményt és annak állapotát. Semmi nem visszafordíthatatlan — bezárhatod, és visszatérhetsz.",
        },
        screen: { screenId: "setup-checklist" },
      },
      {
        id: "docker-green",
        os: "all",
        title: {
          en: "Get the Docker row green",
          it: "Porta la riga Docker sul verde",
          es: "Pon en verde la fila de Docker",
          fr: "Passez la ligne Docker au vert",
          de: "Bring die Docker-Zeile auf Grün",
          pt: "Põe a linha do Docker a verde",
          hu: "Hozd zöldre a Docker sorát",
        },
        body: {
          en: "The checklist checks Docker for you. If the row is not green, start Docker and let it finish its own first run before coming back — on Windows it asks for its own consent.",
          it: "La checklist controlla Docker per te. Se la riga non è verde, avvia Docker e lascia che finisca il suo primo avvio prima di tornare qui — su Windows chiede un consenso suo.",
          es: "La lista comprueba Docker por ti. Si la fila no está verde, arranca Docker y deja que termine su propio primer inicio antes de volver — en Windows pide su propio consentimiento.",
          fr: "La liste vérifie Docker pour vous. Si la ligne n'est pas verte, démarrez Docker et laissez-le terminer son premier lancement avant de revenir — sous Windows, il demande son propre consentement.",
          de: "Die Checkliste prüft Docker für dich. Ist die Zeile nicht grün, starte Docker und lass seinen eigenen Erststart durchlaufen, bevor du zurückkommst — unter Windows fragt es nach eigener Zustimmung.",
          pt: "A lista verifica o Docker por ti. Se a linha não estiver verde, arranca o Docker e deixa-o terminar o seu primeiro arranque antes de voltares — no Windows pede o seu próprio consentimento.",
          hu: "Az ellenőrzőlista helyetted nézi meg a Dockert. Ha a sor nem zöld, indítsd el a Dockert, és hagyd befejezni a saját első indítását, mielőtt visszatérsz — Windowson külön hozzájárulást kér.",
        },
        // La stessa schermata della fase «Installa Docker»: qui però si
        // guarda lo stato verde, non l'installazione. Didascalia diversa,
        // asset unico.
        screen: {
          screenId: "docker-check",
          caption: {
            en: "Green means the container can start. Anything else stops the setup here.",
            it: "Verde vuol dire che il container può partire. Qualunque altro stato ferma il setup qui.",
            es: "Verde significa que el contenedor puede arrancar. Cualquier otro estado detiene aquí la configuración.",
            fr: "Vert signifie que le conteneur peut démarrer. Tout autre état arrête la configuration ici.",
            de: "Grün heißt: Der Container kann starten. Alles andere stoppt die Einrichtung hier.",
            pt: "Verde significa que o contentor pode arrancar. Qualquer outro estado trava aqui a configuração.",
            hu: "A zöld azt jelenti, hogy a konténer elindulhat. Bármi más itt megállítja a beállítást.",
          },
        },
        links: [
          {
            kind: "external",
            href: DOCKER_URL,
            label: {
              en: "Docker install page",
              it: "Pagina di installazione di Docker",
              es: "Página de instalación de Docker",
              fr: "Page d'installation de Docker",
              de: "Docker-Installationsseite",
              pt: "Página de instalação do Docker",
              hu: "A Docker telepítési oldala",
            },
          },
        ],
      },
      {
        id: "connect-provider",
        os: "all",
        title: {
          en: "Connect a provider",
          it: "Collega un provider",
          es: "Conecta un proveedor",
          fr: "Connectez un fournisseur",
          de: "Anbieter verbinden",
          pt: "Liga um provedor",
          hu: "Csatlakoztass egy szolgáltatót",
        },
        body: {
          en: "The provider is the team's brain: pick the one you already subscribe to and authorize it in the office terminal. The link opens in your browser, codes stay in the terminal.",
          it: "Il provider è il cervello del team: scegli quello a cui sei già abbonato e autorizzalo nel terminale dell'ufficio. Il link si apre nel browser, i codici restano nel terminale.",
          es: "El proveedor es el cerebro del equipo: elige aquel al que ya estás suscrito y autorízalo en el terminal de la oficina. El enlace se abre en el navegador, los códigos se quedan en el terminal.",
          fr: "Le fournisseur est le cerveau de l'équipe : choisissez celui auquel vous êtes déjà abonné et autorisez-le dans le terminal du bureau. Le lien s'ouvre dans le navigateur, les codes restent dans le terminal.",
          de: "Der Anbieter ist das Gehirn des Teams: Wähle den, den du bereits abonniert hast, und autorisiere ihn im Terminal des Büros. Der Link öffnet den Browser, Codes bleiben im Terminal.",
          pt: "O provedor é o cérebro da equipa: escolhe aquele que já subscreves e autoriza-o no terminal do escritório. O link abre no navegador, os códigos ficam no terminal.",
          hu: "A szolgáltató a csapat agya: válaszd azt, amelyre már előfizettél, és engedélyezd az iroda termináljában. A hivatkozás a böngészőben nyílik, a kódok a terminálban maradnak.",
        },
        screen: { screenId: "provider-auth" },
        links: [
          {
            kind: "internal",
            href: DOCS_PROVIDER,
            label: {
              en: "Which providers are supported",
              it: "Quali provider sono supportati",
              es: "Qué proveedores están soportados",
              fr: "Quels fournisseurs sont pris en charge",
              de: "Welche Anbieter unterstützt werden",
              pt: "Que provedores são suportados",
              hu: "Mely szolgáltatók támogatottak",
            },
          },
        ],
      },
      {
        id: "upload-cv",
        os: "all",
        title: {
          en: "Upload your CV",
          it: "Carica il tuo CV",
          es: "Sube tu CV",
          fr: "Téléversez votre CV",
          de: "Lade deinen Lebenslauf hoch",
          pt: "Carrega o teu CV",
          hu: "Töltsd fel az önéletrajzod",
        },
        body: {
          en: "The CV is what the team compares every position against. It stays on your machine — the score you will read comes from this file, so use the real one.",
          it: "Il CV è ciò con cui la squadra confronta ogni posizione. Resta sulla tua macchina: il punteggio che leggerai nasce da questo file, quindi usa quello vero.",
          es: "El CV es aquello con lo que el equipo compara cada posición. Se queda en tu ordenador: la puntuación que leerás nace de este archivo, así que usa el real.",
          fr: "Le CV est ce à quoi l'équipe compare chaque offre. Il reste sur votre machine : le score que vous lirez vient de ce fichier, utilisez donc le vrai.",
          de: "Der Lebenslauf ist das, womit das Team jede Stelle vergleicht. Er bleibt auf deinem Rechner: Die Bewertung, die du liest, stammt aus dieser Datei — nimm also die echte.",
          pt: "O CV é aquilo com que a equipa compara cada posição. Fica na tua máquina: a pontuação que vais ler nasce deste ficheiro, por isso usa o verdadeiro.",
          hu: "Az önéletrajz az, amihez a csapat minden pozíciót mér. A gépeden marad: a pontszám, amit majd olvasol, ebből a fájlból születik — használd a valódit.",
        },
        screen: { screenId: "cv-upload" },
        links: [
          {
            kind: "internal",
            href: DOCS_PRIVACY,
            label: {
              en: "Where your CV and keys live",
              it: "Dove finiscono il tuo CV e le tue chiavi",
              es: "Dónde acaban tu CV y tus claves",
              fr: "Où vivent votre CV et vos clés",
              de: "Wo dein Lebenslauf und deine Schlüssel liegen",
              pt: "Onde ficam o teu CV e as tuas chaves",
              hu: "Hol tárolódik az önéletrajzod és a kulcsaid",
            },
          },
        ],
      },
    ],
  },
  {
    id: "start",
    title: {
      en: "Start the team",
      it: "Avvia il team",
      es: "Arranca el equipo",
      fr: "Démarrez l'équipe",
      de: "Team starten",
      pt: "Arranca a equipa",
      hu: "Indítsd el a csapatot",
    },
    summary: {
      en: "From the last check to the first positions on screen.",
      it: "Dall'ultimo controllo alle prime posizioni a schermo.",
      es: "Desde la última comprobación hasta las primeras posiciones en pantalla.",
      fr: "De la dernière vérification aux premières offres à l'écran.",
      de: "Von der letzten Prüfung bis zu den ersten Stellen auf dem Bildschirm.",
      pt: "Da última verificação às primeiras posições no ecrã.",
      hu: "Az utolsó ellenőrzéstől az első pozíciókig a képernyőn.",
    },
    phases: [
      {
        id: "final-check",
        os: "all",
        title: {
          en: "Check the list once more",
          it: "Ricontrolla la lista",
          es: "Revisa la lista otra vez",
          fr: "Revérifiez la liste",
          de: "Prüfe die Liste noch einmal",
          pt: "Revê a lista mais uma vez",
          hu: "Nézd át még egyszer a listát",
        },
        body: {
          en: "Every row green means the team can start. If one is still red, that row tells you exactly what to fix — no need to guess.",
          it: "Tutte le righe verdi vuol dire che il team può partire. Se una è ancora rossa, quella riga dice esattamente cosa sistemare: non serve indovinare.",
          es: "Todas las filas en verde significa que el equipo puede arrancar. Si alguna sigue en rojo, esa fila dice exactamente qué arreglar: no hay que adivinar.",
          fr: "Toutes les lignes vertes signifient que l'équipe peut démarrer. Si l'une est encore rouge, elle indique exactement quoi corriger : rien à deviner.",
          de: "Alle Zeilen grün heißt: Das Team kann starten. Ist eine noch rot, sagt genau diese Zeile, was zu beheben ist — raten ist nicht nötig.",
          pt: "Todas as linhas a verde significa que a equipa pode arrancar. Se alguma ainda estiver a vermelho, essa linha diz exatamente o que corrigir: não é preciso adivinhar.",
          hu: "Ha minden sor zöld, a csapat indulhat. Ha valamelyik még piros, pontosan az a sor mondja meg, mit kell rendbe tenni — nem kell találgatni.",
        },
        // Terza comparsa della checklist: stesso file, terza lettura.
        screen: {
          screenId: "setup-checklist",
          caption: {
            en: "The same list you started from — now it should be all green.",
            it: "La stessa lista da cui sei partito: ora dovrebbe essere tutta verde.",
            es: "La misma lista con la que empezaste: ahora debería estar toda verde.",
            fr: "La même liste qu'au départ : elle devrait maintenant être toute verte.",
            de: "Dieselbe Liste wie am Anfang — jetzt sollte alles grün sein.",
            pt: "A mesma lista de onde partiste: agora deve estar toda verde.",
            hu: "Ugyanaz a lista, amiről indultál — most már mindennek zöldnek kell lennie.",
          },
        },
      },
      {
        id: "team-running",
        os: "all",
        title: {
          en: "Watch the first results",
          it: "Guarda i primi risultati",
          es: "Mira los primeros resultados",
          fr: "Regardez les premiers résultats",
          de: "Sieh dir die ersten Ergebnisse an",
          pt: "Vê os primeiros resultados",
          hu: "Nézd meg az első eredményeket",
        },
        body: {
          en: "The team starts searching and scoring on its own. The first positions take a few minutes; from here you can close the window and let it work.",
          it: "Il team inizia a cercare e a dare punteggi da solo. Le prime posizioni arrivano in qualche minuto; da qui puoi chiudere la finestra e lasciarlo lavorare.",
          es: "El equipo empieza a buscar y puntuar por su cuenta. Las primeras posiciones tardan unos minutos; desde aquí puedes cerrar la ventana y dejarlo trabajar.",
          fr: "L'équipe se met à chercher et à noter toute seule. Les premières offres arrivent en quelques minutes ; vous pouvez fermer la fenêtre et la laisser travailler.",
          de: "Das Team beginnt von selbst zu suchen und zu bewerten. Die ersten Stellen brauchen ein paar Minuten; ab hier kannst du das Fenster schließen und es arbeiten lassen.",
          pt: "A equipa começa a procurar e a pontuar sozinha. As primeiras posições demoram alguns minutos; a partir daqui podes fechar a janela e deixá-la trabalhar.",
          hu: "A csapat magától elkezd keresni és pontozni. Az első pozíciók néhány perc alatt megérkeznek; innentől bezárhatod az ablakot, és hagyhatod dolgozni.",
        },
        screen: { screenId: "team-running" },
      },
    ],
  },
  {
    id: "connect-web",
    title: {
      en: "Connect it to the web",
      it: "Collegalo al web",
      es: "Conéctalo a la web",
      fr: "Reliez-le au web",
      de: "Mit dem Web verbinden",
      pt: "Liga-o à web",
      hu: "Kösd össze a webbel",
    },
    summary: {
      en: "Read the same results from your phone — and decide what gets shared.",
      it: "Leggi gli stessi risultati dal telefono, e decidi cosa viene condiviso.",
      es: "Lee los mismos resultados desde el móvil y decide qué se comparte.",
      fr: "Consultez les mêmes résultats depuis votre téléphone et décidez de ce qui est partagé.",
      de: "Lies dieselben Ergebnisse vom Telefon — und entscheide, was geteilt wird.",
      pt: "Lê os mesmos resultados a partir do telemóvel e decide o que é partilhado.",
      hu: "Olvasd ugyanazokat az eredményeket telefonról — és döntsd el, mi kerül megosztásra.",
    },
    phases: [
      {
        id: "sign-in-google",
        os: "all",
        title: {
          en: "Sign in with Google",
          it: "Accedi con Google",
          es: "Inicia sesión con Google",
          fr: "Connectez-vous avec Google",
          de: "Mit Google anmelden",
          pt: "Inicia sessão com a Google",
          hu: "Jelentkezz be Google-fiókkal",
        },
        body: {
          en: "The link between your local team and this site is an account: sign in here with Google, and use the same account in the app.",
          it: "Il legame fra il team locale e questo sito è un account: accedi qui con Google e usa lo stesso account nell'app.",
          es: "El vínculo entre tu equipo local y este sitio es una cuenta: inicia sesión aquí con Google y usa la misma cuenta en la aplicación.",
          fr: "Le lien entre votre équipe locale et ce site est un compte : connectez-vous ici avec Google et utilisez le même compte dans l'application.",
          de: "Die Verbindung zwischen deinem lokalen Team und dieser Website ist ein Konto: Melde dich hier mit Google an und nutze dasselbe Konto in der App.",
          pt: "A ligação entre a tua equipa local e este site é uma conta: inicia sessão aqui com a Google e usa a mesma conta na aplicação.",
          hu: "A helyi csapat és ez a webhely közötti kapcsolat egy fiók: jelentkezz be itt a Google-lel, és használd ugyanazt a fiókot az alkalmazásban is.",
        },
        screen: { screenId: "google-sign-in" },
      },
      {
        id: "authorizations",
        os: "all",
        title: {
          en: "Choose what gets synced",
          it: "Scegli cosa si sincronizza",
          es: "Elige qué se sincroniza",
          fr: "Choisissez ce qui est synchronisé",
          de: "Wähle, was synchronisiert wird",
          pt: "Escolhe o que é sincronizado",
          hu: "Válaszd ki, mi szinkronizálódjon",
        },
        body: {
          en: "The app asks before sending anything: you grant the sync explicitly and you can revoke it later. Nothing leaves your machine until you say so.",
          it: "L'app chiede prima di mandare qualsiasi cosa: la sincronizzazione la autorizzi tu e puoi revocarla dopo. Niente lascia la tua macchina finché non lo dici tu.",
          es: "La aplicación pregunta antes de enviar nada: la sincronización la autorizas tú y puedes revocarla después. Nada sale de tu ordenador hasta que lo digas.",
          fr: "L'application demande avant d'envoyer quoi que ce soit : c'est vous qui autorisez la synchronisation et vous pouvez la révoquer ensuite. Rien ne quitte votre machine sans votre accord.",
          de: "Die App fragt, bevor sie irgendetwas sendet: Du erteilst die Synchronisierung ausdrücklich und kannst sie später widerrufen. Nichts verlässt deinen Rechner, bevor du es sagst.",
          pt: "A aplicação pergunta antes de enviar seja o que for: és tu que autorizas a sincronização e podes revogá-la depois. Nada sai da tua máquina até tu o dizeres.",
          hu: "Az alkalmazás megkérdez, mielőtt bármit elküldene: a szinkronizálást te engedélyezed, és később vissza is vonhatod. Semmi nem hagyja el a géped, amíg nem mondod.",
        },
        screen: { screenId: "sync-authorizations" },
        links: [
          {
            kind: "internal",
            href: DOCS_PRIVACY,
            label: {
              en: "What is stored, and where",
              it: "Cosa viene salvato, e dove",
              es: "Qué se guarda, y dónde",
              fr: "Ce qui est stocké, et où",
              de: "Was gespeichert wird, und wo",
              pt: "O que é guardado, e onde",
              hu: "Mi tárolódik, és hol",
            },
          },
        ],
      },
      {
        id: "read-dashboard",
        os: "all",
        title: {
          en: "Read the dashboard anywhere",
          it: "Leggi la dashboard ovunque",
          es: "Lee el panel desde donde quieras",
          fr: "Consultez le tableau de bord partout",
          de: "Lies das Dashboard überall",
          pt: "Lê o painel em qualquer lado",
          hu: "Olvasd az irányítópultot bárhonnan",
        },
        body: {
          en: "Once synced, the positions and scores appear on the site: the web is read-only, so you can look from your phone while the team keeps working at home.",
          it: "Dopo la sincronizzazione, posizioni e punteggi compaiono sul sito: il web è in sola lettura, quindi puoi guardare dal telefono mentre il team continua a lavorare a casa.",
          es: "Tras la sincronización, las posiciones y puntuaciones aparecen en el sitio: la web es de solo lectura, así que puedes mirar desde el móvil mientras el equipo sigue trabajando en casa.",
          fr: "Une fois synchronisé, les offres et les scores apparaissent sur le site : le web est en lecture seule, vous pouvez donc regarder depuis votre téléphone pendant que l'équipe travaille chez vous.",
          de: "Nach der Synchronisierung erscheinen Stellen und Bewertungen auf der Website: Das Web ist nur lesend, du kannst also vom Telefon aus schauen, während das Team zu Hause weiterarbeitet.",
          pt: "Depois da sincronização, as posições e pontuações aparecem no site: a web é só de leitura, por isso podes ver do telemóvel enquanto a equipa continua a trabalhar em casa.",
          hu: "A szinkronizálás után a pozíciók és pontszámok megjelennek a webhelyen: a web csak olvasható, így telefonról is nézheted, miközben a csapat otthon tovább dolgozik.",
        },
        screen: { screenId: "web-dashboard" },
        links: [
          {
            kind: "internal",
            href: DOCS_DASHBOARD,
            label: {
              en: "How to read the dashboard",
              it: "Come si legge la dashboard",
              es: "Cómo leer el panel",
              fr: "Comment lire le tableau de bord",
              de: "Wie man das Dashboard liest",
              pt: "Como ler o painel",
              hu: "Hogyan olvasd az irányítópultot",
            },
          },
        ],
      },
    ],
  },
];
